### ISSUE TITLE
Widget "ctrl - Icon Increment" Binding minmax

### ISSUE THREAD

**Issue by Blockmove** [ioBroker/ioBroker.vis-2#101]
Verwendet man für das Widget "ctrl - Icon Increment" für den minmax-Wert ein Bindung, dann funktioniert das zwar in der Editor-Runtime, aber nicht in der eigentlichen Runtime. In der eigentlichen Runtime wird der Datenpunkt nicht erhöht. Trägt man anstelle des Bindings einen statischen Wert ein, ist alles i.O.
Getestet mit Firefox und Edge.

VIS-2 Version 2.3.0

**Comment by GermanBluefox** [comment]
PLease retest with 2.4.0
