### ISSUE TITLE
Widget "Gestylt Zur URL springen" "Setze Wert" does not work

### ISSUE THREAD

**Issue by MK-66** [ioBroker/ioBroker.vis-2#104]
With all "Gestylt" dialog widgets no matter if with the old ones or the new widget "Gestylt Zur URL springen" "Setze Object-ID" "Setze Wert" does not work. Simply no value is written into the datapoint. It doesn't matter what kind of datapoint it is, bool, string, etc.

![Screenshot Dialog Wert Setzen](https://github.com/ioBroker/ioBroker.vis-2/assets/56516310/b885b93c-7803-4b9c-99a4-979fe4be222f)

System completely up to date:
- Linux Debian 12
- Web version: v6.1.3
- JS-Controller version: 5.0.12
- VIS version: 1.4.16
- Node version: v18.17.1

**Comment by foxriver76** [comment]
is it fixed for you in 2.3.3?
