### ISSUE TITLE
Staubsauger Widgets in allen Attributen

### ISSUE THREAD

**Issue by sigi2345** [ioBroker/ioBroker.vis-2#109]
**Describe the bug**  

Staubsauger Widgets sind in allen Attributen auch beim Widget Schalter oder Knöpfe

![Screenshot (382)](https://github.com/ioBroker/ioBroker.vis-2/assets/41079106/65afee1f-ddf2-4e2e-84ca-139e800c4e3b)

**Comment by foxriver76** [comment]
is it fixed for you in 2.3.3 @sigi2345 ?

**Comment by sigi2345** [comment]
> is it fixed for you in 2.3.3 @sigi2345 ?

Ja
