### ISSUE TITLE
Reihenfolge der Seiten ändern 

### ISSUE THREAD

**Issue by DaisyMaus** [ioBroker/ioBroker.vis-2#11]
Hallo

Ich würde gerne die Reihenfolge der Seiten ändern aber dies geht nicht. 
Wenn ich vorne auf den kleinen Zettel gehe wo ziehen steht, dann ist da nur ein durchgestrichener roter Kreis.

JS-Controller version : 4.0.24
Node version : v18.15.0
NPM : 9.5.0

![1684491185927-screenshot-2023-05-19-121050](https://github.com/ioBroker/ioBroker.vis/assets/40956210/da276763-4a16-4d38-bbb9-6632d497f714)

vis-2-beta.0 : v2.0.29

Gruss Sandy

PS: hier mal das Widget

[{"tpl":"tplValueStringRaw","data":{"oid":"daswetter.0.Wetter_2","g_fixed":false,"g_visibility":false,"g_css_font_text":false,"g_css_background":false,"g_css_shadow_padding":false,"g_css_border":false,"g_gestures":false,"g_signals":false,"g_last_change":false,"visibility-cond":"==","visibility-val":1,"visibility-groups-action":"hide","signals-cond-0":"==","signals-val-0":true,"signals-icon-0":"/vis/signals/lowbattery.png","signals-icon-size-0":0,"signals-blink-0":false,"signals-horz-0":0,"signals-vert-0":0,"signals-hide-edit-0":false,"signals-cond-1":"==","signals-val-1":true,"signals-icon-1":"/vis/signals/lowbattery.png","signals-icon-size-1":0,"signals-blink-1":false,"signals-horz-1":0,"signals-vert-1":0,"signals-hide-edit-1":false,"signals-cond-2":"==","signals-val-2":true,"signals-icon-2":"/vis/signals/lowbattery.png","signals-icon-size-2":0,"signals-blink-2":false,"signals-horz-2":0,"signals-vert-2":0,"signals-hide-edit-2":false,"lc-type":"last-change","lc-is-interval":true,"lc-is-moment":false,"lc-format":"","lc-position-vert":"top","lc-position-horz":"right","lc-offset-vert":0,"lc-offset-horz":0,"lc-font-size":"12px","lc-font-family":"","lc-font-style":"","lc-bkg-color":"","lc-color":"","lc-border-width":"0","lc-border-style":"","lc-border-color":"","lc-border-radius":10,"lc-zindex":0},"style":{"left":"200px","top":"1258px","width":"2200px","height":"120px","z-index":"3"},"widgetSet":"basic"}]

**Comment by kurt-k** [comment]
In Version 2.2.5 auch noch nicht möglich. Ziehen an dem Zettel ist zwar möglich und die Seite wird gegriffen, absetzten an einer anderen Stelle hat aber keine Auswirkung

**Comment by foxriver76** [comment]
Das Ziehen ist nur dafür da um von einem Ordner in den anderen zu ziehen. Die Sortierung erfolgt alphabetisch (mittlerweile).

**Comment by foxriver76** [comment]
The question for me is, why would you like to change the order? We would like to stick to this, as there is currently no information about any order and it also would not make sense to have one. In the global navigation, e.g. you can specify the order manually. If it you have a clear use case, feel free to reopen this and give more information.
