### ISSUE TITLE
basic HTML widget - small pen symbol missing for "HTML edit"

### ISSUE THREAD

**Issue by goesebrecht1** [ioBroker/ioBroker.vis-2#111]
The basic HTML widget is missing the small pen symbol in the “HTML” attribute that opens the “HTML edit” pop-up.

v2.3.2

Im basic-html-Widget fehlt beim Attribut „HTML“ das kleine Stift-Symbol, was das PopUp „HTML edit“ öffnet. 

![image](https://github.com/ioBroker/ioBroker.vis-2/assets/126241718/2687b512-696e-430b-891b-b02f502710f6)

**Comment by Feuer-sturm** [comment]
@goesebrecht1 please add the vis2 version you use

**Comment by goesebrecht1** [comment]
v2.3.2

**Comment by Feuer-sturm** [comment]
is fixed with vis2 2.3.3
![grafik](https://github.com/ioBroker/ioBroker.vis-2/assets/25422320/dfd2720e-c4f7-4ba2-80bc-3b2a3dd1b126)
