### ISSUE TITLE
Menü Darstellung

### ISSUE THREAD

**Issue by smilie108** [ioBroker/ioBroker.vis-2#112]
Wenn Ihr eventuell das Thema Menue angeht.
Eventuell ein Denkanstoß bzw. wenn ich meine Wünsche deponieren darf 😉
Es wäre ja echt super man die Reihenfolge Irgendwie defineren könnte und was ganz super wäre wenn es zb 1 Untermenuestufe geben würde.
Als Beispiel hat man eine Pv Anlage Übersicht und untergeordnet zb. die dazugehörigen Statistiken oder charts usw.
Das gleich natührlich für zb die Wärmepumpe usw.
😉
Mfg smilie108

**Comment by Feuer-sturm** [comment]
@smilie108 Die Änderung der Reihenfolge der Menüeinträge wird über dieses issue https://github.com/ioBroker/ioBroker.vis-2/issues/15 verfolgt.

Dieses issue können wir für den Vorschlag der weiteren Unterebene verwenden :-)

**Comment by foxriver76** [comment]
Da ich denke es geht hier um Navigation und Styling und Reihenfolge mittlerweile geht mache ich mal zu.

Geschachtelte Menüs werden hier bereits gefordert: https://github.com/ioBroker/ioBroker.vis-2/issues/253
