### ISSUE TITLE
gif image can not be selected in vis-2 editor in widget basic - image

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.vis-2#113]
**Describe the bug**  
It is not possible to select a gif image by using the vis-2 wizard if you click on the three dots beside "Quelle" of widget "basic - image". The gif image is not shown in the dialog box.
If you double check in admin -> files the gif image is stored correctly in the directory.

![grafik](https://github.com/ioBroker/ioBroker.vis-2/assets/25422320/feda5097-16fb-4dc0-9182-a50ff493fa1a)
![grafik](https://github.com/ioBroker/ioBroker.vis-2/assets/25422320/d4e07b82-ce91-47e0-8e1c-f96134766f30)

Current workaround:
If gif is stored in the directory of vis-2.0 then directly enter the path `/vis-2.0/xxx.gif` in field "Quelle"
If gif is stored in subdirectory of the vis-2 project then directly enter the path `_PRJ_NAME/Maus.gif` in field "Quelle"
![grafik](https://github.com/ioBroker/ioBroker.vis-2/assets/25422320/5dfaa39d-2da0-461a-96b9-7c040b30183c)

**Versions:**  
 - Adapter version:
   - admin 6.10.8
   - vis-2 version 2.3.2

**Comment by Feuer-sturm** [comment]
@GermanBluefox still the same behavior in new version 2.3.3 as descired in the first post

**Comment by foxriver76** [comment]
will be fixed in next version

**Comment by Feuer-sturm** [comment]
is working with vis 2.3.5 :-)
Thanks.
