### ISSUE TITLE
Seite > CSS-Hintergrund > "Kein Hintergrund" wird ignoriert, ist immer #000

### ISSUE THREAD

**Issue by RkcCorian** [ioBroker/ioBroker.vis-2#114]
**Describe the bug**  

**To Reproduce**  
1. Take project from VIS.1, where CSS-Hintergrund is set to "Kein Hintergrund" (and where this is working)
2. Set CSS-Hintergrund to "Kein Hintergrund"
3. Check in JARVIS the iFrame where the VIS.2 project is used

**Expected behavior**  
I use multiple VIS projects in Jarvis as iFrame. The background of the VIS is set to "Kein Hintergrund" and works fine with VIS.1. But in VIS.2 with the same (imported) project the background is set always to #000

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 2.3.2
 - JS-Controller version: 5.0.12 
 - Node version: v18.17.1
 - Operating system: docker

**Additional context**

**Comment by RkcCorian** [comment]
body.body-dark is what is shown at Edge > inspect as the trouble maker. I can manually set this to transparent and then it is fine, so the root-cause is expected by me there...
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/79741077/43210dd3-f4bc-4572-9bf8-8de68509f1cc)

**Comment by Feuer-sturm** [comment]
@RkcCorian please verify with version 2.3.3

**Comment by RkcCorian** [comment]
@Feuer-sturm: Vielen Dank! Unfortunately it is still the case...
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/79741077/3ace95d1-28f1-4266-8d56-dac561fb5d78)

**Comment by RkcCorian** [comment]
The background color is dependent on the selected VIS-2 Theme, but never transparent

**Comment by RkcCorian** [comment]
@Feuer-sturm : Moin! Anything that I can do here to support you? Greetings!

**Comment by foxriver76** [comment]
Yes, as far as I understand, the Project has a background defined by the theme. And Page backgrounds are placed in front of them. If you are making page background transparent, the parent background is shown instead, which is the project one in this case. What speaks against defining the correct background color? 

An alternative would be to not let the theme affect runtime, then you will end up with a white project background.

**Comment by RkcCorian** [comment]
@foxriver76 : I cannot simply define "the correct background color" as this is a responsive picture.... I use VIS 1 GUI at several places within JARVIS via iFrame (wherevere JARVIS is not capable to do this). Furtheremore I implemented the VIS 1 GUI responsive, so also a manual alignment would not work. So I need this feature as this was working in VIS 1 + in VIS 2 I can select transparency but it is not working. I hope this explains the background if this bug report better.

Many thanks!! :-)

Examples from my JARVIS, incl. VIS 1
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/79741077/cafef355-8f95-4b06-954a-2eb27013e761)

![image](https://github.com/ioBroker/ioBroker.vis-2/assets/79741077/e5c48d43-5fdc-4920-97ab-07d95c227acb)

**Comment by RkcCorian** [comment]
@foxriver76 : I send you per PM a OneDrive link for my VIS1 and VIS2 project. Both are the same, but was not sure if you need to check between them. When you have a JARVIS instance (or with another VIS) you can take this a iFrame. When you have a background picture for the "master" JARVIS or VIS you can check if the transparency is working as expected.
Contact me in case you need more (info).
Many thanks!!

**Comment by RkcCorian** [comment]
@foxriver76 : I checked with version 2.9.2 but it is still not solved. Can you pls. reopen this issue?! Many thanks!

**Comment by RkcCorian** [comment]
<img width="1310" alt="image" src="https://github.com/ioBroker/ioBroker.vis-2/assets/79741077/0a1d1d6d-71ad-4eee-b219-22b9bc5bd6dc">

**Comment by RkcCorian** [comment]
<img width="394" alt="image" src="https://github.com/ioBroker/ioBroker.vis-2/assets/79741077/09a42e62-221a-4db0-902e-cdcdcf479eab">

**Comment by RkcCorian** [comment]
@foxriver76 No. The screenshot is from an iFrame. My Master VIS is JARVIS
<img width="1175" alt="image" src="https://github.com/ioBroker/ioBroker.vis-2/assets/79741077/771892cc-8b4e-4b88-b7dd-3fe69b6d1e99">
<img width="937" alt="image" src="https://github.com/ioBroker/ioBroker.vis-2/assets/79741077/c82a798f-6f65-444f-bd70-684fb99ee002">

**Comment by foxriver76** [comment]
Hm okay weird I have tested it, will retest tomorrow

**Comment by RkcCorian** [comment]
@foxriver76 : Not relevant for me, but... when I select background = transparent I would like to have it allways transparent, even I'm not using within an iFrame. I do not understand where the dependency with the iFrame shall come from.

**Comment by RkcCorian** [comment]
> Hm okay weird I have tested it, will retest tomorrow

Many thanks!!

**Comment by foxriver76** [comment]
From the code that checks if it runs in an iFrame which someone implemented, so I would keep this functionality for now, but could be another issue.

**Comment by RkcCorian** [comment]
@foxriver76 : I'm really sorry, but the problem still exists, even with the latest version (2.3.2)

**Comment by foxriver76** [comment]
There was no new version after you last tested so in 2.9.2 it es expected to not fully work.
