### ISSUE TITLE
Widget Basic Number cannot be selected

### ISSUE THREAD

**Issue by afuerhoff** [ioBroker/ioBroker.vis-2#116]
**Describe the bug**  
Widget Basic Number kann im vis2 Editor nicht selektiert werden. Die Tags liegen direkt über dem Widget, nachdem man auf Play gedrückt hat. 
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/a98d4c01-4873-4c97-8793-4c7fb1ac6ccd)
Nach dem slektieren mit der Maus werden die Widgets wieder korrekt dargestellt und lassen sich selektieren.
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/4fb0b111-0340-446d-ad59-b76f3699f172)

**Versions:**  
 - Adapter version: 2.3.2
 - JS-Controller version:  5.0.12
 - Node version: 18.18.1
 - Operating system: Debian Armbian 23.8.1 bullsey with Armbian Linux 4.19.69-rockchip

**Comment by afuerhoff** [comment]
Im ersten Bild kann ich nicht mehr mit der Maus das Widget auswählen. Im zweiten geht es dann wieder.


`
[
  {
    "tpl": "tplVis-materialdesign-Button-Toggle-vertical",
    "data": {
      "oid": "hm-rpc.0.OEQ0699787.0.LOWBAT",
      "g_fixed": false,
      "g_visibility": false,
      "g_css_font_text": true,
      "g_css_shadow_padding": false,
      "g_css_border": false,
      "g_gestures": false,
      "g_signals": false,
      "g_last_change": false,
      "visibility-cond": "==",
      "visibility-val": 1,
      "visibility-groups-action": "hide",
      "buttonStyle": "text",
      "toggleType": "boolean",
      "stateIfNotTrueValue": "off",
      "vibrateOnMobilDevices": "50",
      "iconPosition": "top",
      "signals-cond-0": "==",
      "signals-val-0": true,
      "signals-icon-0": "/vis/signals/lowbattery.png",
      "signals-icon-size-0": 0,
      "signals-blink-0": false,
      "signals-horz-0": 0,
      "signals-vert-0": 0,
      "signals-hide-edit-0": false,
      "signals-cond-1": "==",
      "signals-val-1": true,
      "signals-icon-1": "/vis/signals/lowbattery.png",
      "signals-icon-size-1": 0,
      "signals-blink-1": false,
      "signals-horz-1": 0,
      "signals-vert-1": 0,
      "signals-hide-edit-1": false,
      "signals-cond-2": "==",
      "signals-val-2": true,
      "signals-icon-2": "/vis/signals/lowbattery.png",
      "signals-icon-size-2": 0,
      "signals-blink-2": false,
      "signals-horz-2": 0,
      "signals-vert-2": 0,
      "signals-hide-edit-2": false,
      "lc-type": "last-change",
      "lc-is-interval": true,
      "lc-is-moment": false,
      "lc-format": "",
      "lc-position-vert": "top",
      "lc-position-horz": "right",
      "lc-offset-vert": 0,
      "lc-offset-horz": 0,
      "lc-font-size": "12px",
      "lc-font-family": "",
      "lc-font-style": "",
      "lc-bkg-color": "",
      "lc-color": "",
      "lc-border-width": "0",
      "lc-border-style": "",
      "lc-border-color": "",
      "lc-border-radius": 10,
      "lc-zindex": 0,
      "colorBgFalse": "",
      "colorBgTrue": "",
      "colorPress": "",
      "valueOff": "false",
      "valueOn": "true",
      "pushButton": false,
      "image": "battery-90",
      "imageColor": "green",
      "iconHeight": "20",
      "imageTrue": "battery-alert",
      "imageTrueColor": "red",
      "g_label": true,
      "g_lock": false,
      "autoLockAfter": 10,
      "lockIconTop": "5",
      "lockIconLeft": "5",
      "lockFilterGrayscale": "30",
      "buttontext": "",
      "textFontFamily": "#mdwTheme:vis-materialdesign.0.fonts.button.vertical.text",
      "textFontSize": "#mdwTheme:vis-materialdesign.0.fontSizes.button.vertical.text",
      "alignment": "center",
      "mdwButtonPrimaryColor": "#mdwTheme:vis-materialdesign.0.colors.button.vertical.primary",
      "mdwButtonSecondaryColor": "#mdwTheme:vis-materialdesign.0.colors.button.vertical.secondary",
      "lockIconColor": "#mdwTheme:vis-materialdesign.0.colors.button.lock_icon",
      "readOnly": false,
      "debug": false
    },
    "style": {
      "left": 148,
      "top": 288,
      "width": "24px",
      "height": "33px",
      "z-index": "2",
      "cursor": "default",
      "color": ""
    },
    "widgetSet": "materialdesign",
    "_id": "i000001"
  },
  {
    "tpl": "tplValueFloat",
    "data": {
      "oid": "hm-rpc.0.OEQ1250416.4.BATTERY_STATE",
      "is_comma": "true",
      "g_extended": true,
      "factor": "1",
      "html_append_singular": "",
      "html_append_plural": " V",
      "name": null,
      "comment": null,
      "class": "{v:hm-rpc.0.OEQ1250416.0.LOWBAT;v == false ? 'mdui-label mdui-green' :: 'mdui-label mdui-white mdui-red-glow'}",
      "filterkey": null,
      "multi-views": null,
      "locked": null,
      "g_fixed": true,
      "g_css_font_text": true,
      "digits": "1"
    },
    "style": {
      "left": "200px",
      "top": 300,
      "width": "32px",
      "height": "14px",
      "font-size": "10px"
    },
    "widgetSet": "basic",
    "_id": "i000002"
  },
  {
    "tpl": "tplValueFloat",
    "data": {
      "oid": "hm-rpc.0.OEQ1255167.4.BATTERY_STATE",
      "is_comma": "true",
      "g_extended": true,
      "factor": "1",
      "html_append_singular": "",
      "html_append_plural": " V",
      "name": null,
      "comment": null,
      "class": "{v:hm-rpc.0.OEQ1255167.0.LOWBAT;v == false ? 'mdui-label mdui-green' :: 'mdui-label mdui-white mdui-red-glow'}",
      "filterkey": null,
      "multi-views": null,
      "locked": null,
      "g_fixed": true,
      "g_css_font_text": true,
      "digits": "1"
    },
    "style": {
      "left": "264px",
      "top": 300,
      "width": "32px",
      "height": "14px",
      "font-size": "10px"
    },
    "widgetSet": "basic",
    "_id": "i000003"
  },
  {
    "tpl": "tplValueFloat",
    "data": {
      "oid": "hm-rpc.0.OEQ1252985.4.BATTERY_STATE",
      "is_comma": "true",
      "g_extended": true,
      "factor": "1",
      "html_append_singular": "",
      "html_append_plural": " V",
      "name": null,
      "comment": "",
      "class": "{v:hm-rpc.0.OEQ1252985.0.LOWBAT;v == false ? 'mdui-label mdui-green' :: 'mdui-label mdui-white mdui-red-glow'}",
      "filterkey": null,
      "multi-views": null,
      "locked": null,
      "g_fixed": true,
      "g_css_font_text": true,
      "digits": "1"
    },
    "style": {
      "left": "232px",
      "top": 300,
      "width": "32px",
      "height": "14px",
      "font-size": "10px"
    },
    "widgetSet": "basic",
    "_id": "i000004"
  },
  {
    "tpl": "tplValueFloat",
    "data": {
      "oid": "hm-rpc.0.OEQ0699787.2.BATTERY_STATE",
      "is_comma": "true",
      "g_extended": true,
      "factor": "1",
      "html_append_singular": "",
      "html_append_plural": " V",
      "name": null,
      "comment": "{w1:hm-rpc.0.OEQ0699787.0.LOWBAT; w1 == false ? 0 : 100 }",
      "class": "{v:hm-rpc.0.OEQ0699787.0.LOWBAT;v == false ? 'mdui-label mdui-green' :: 'mdui-label mdui-white mdui-red-glow'}",
      "filterkey": null,
      "multi-views": null,
      "locked": null,
      "g_fixed": true,
      "g_css_font_text": true,
      "digits": "1",
      "visibility-oid": "0_userdata.0.Vis.WoZi_Battery_Status",
      "visibility-cond": "==",
      "visibility-val": "true",
      "visibility-groups": null,
      "visibility-groups-action": "hide",
      "g_visibility": true
    },
    "style": {
      "left": "168px",
      "top": 300,
      "width": "32px",
      "height": "14px",
      "font-size": "10px",
      "opacity": ""
    },
    "widgetSet": "basic",
    "_id": "i000005"
  },
  {
    "tpl": "tplImage",
    "data": {
      "g_fixed": true,
      "g_visibility": false,
      "g_css_font_text": false,
      "g_css_background": true,
      "g_css_shadow_padding": false,
      "g_css_border": true,
      "g_gestures": false,
      "g_signals": false,
      "g_last_change": false,
      "visibility-cond": "==",
      "visibility-val": 1,
      "visibility-groups-action": "hide",
      "refreshInterval": "0",
      "signals-cond-0": "==",
      "signals-val-0": true,
      "signals-icon-0": "/vis/signals/lowbattery.png",
      "signals-icon-size-0": 0,
      "signals-blink-0": false,
      "signals-horz-0": 0,
      "signals-vert-0": 0,
      "signals-hide-edit-0": false,
      "signals-cond-1": "==",
      "signals-val-1": true,
      "signals-icon-1": "/vis/signals/lowbattery.png",
      "signals-icon-size-1": 0,
      "signals-blink-1": false,
      "signals-horz-1": 0,
      "signals-vert-1": 0,
      "signals-hide-edit-1": false,
      "signals-cond-2": "==",
      "signals-val-2": true,
      "signals-icon-2": "/vis/signals/lowbattery.png",
      "signals-icon-size-2": 0,
      "signals-blink-2": false,
      "signals-horz-2": 0,
      "signals-vert-2": 0,
      "signals-hide-edit-2": false,
      "lc-type": "last-change",
      "lc-is-interval": true,
      "lc-is-moment": false,
      "lc-format": "",
      "lc-position-vert": "top",
      "lc-position-horz": "right",
      "lc-offset-vert": 0,
      "lc-offset-horz": 0,
      "lc-font-size": "12px",
      "lc-font-family": "",
      "lc-font-style": "",
      "lc-bkg-color": "",
      "lc-color": "",
      "lc-border-width": "0",
      "lc-border-style": "",
      "lc-border-color": "",
      "lc-border-radius": 10,
      "lc-zindex": 0,
      "stretch": false
    },
    "style": {
      "left": "0",
      "top": 0,
      "border-width": "1px",
      "border-style": "",
      "border-color": "#191f28",
      "border-radius": "2px",
      "width": "350px",
      "height": "370px",
      "background-color": "rgba(14,14,14,1)",
      "background": "",
      "z-index": "0",
      "cursor": "default"
    },
    "widgetSet": "basic",
    "_id": "i000006"
  }
]
`

**Comment by foxriver76** [comment]
Kann ich nicht nachstellen.

Neue Seite gemacht, deine Widgets importiert. Was meinst du mit Play drücken? Runtime öffnen? Hat bei mir keine Auswirkung gehabt.

**Comment by afuerhoff** [comment]
Ich bekomme den Fehler in der v2.9.2 auch nicht mehr hin. Könnte vielleicht auch mit dem Rendern zu tun gehabt haben.
Issue kann aus meiner Sicht geschlossen werden.
