### ISSUE TITLE
Nach dem Umbenennen einer Seite ist die Verbindung zur View im Widget nicht mehr vorhanden

### ISSUE THREAD

**Issue by afuerhoff** [ioBroker/ioBroker.vis-2#118]
**Is your feature request related to a problem? Please describe.**
Beim umbenennen einer Seite geht die Verbindung zur View im Widget verloren. Es steht noch der alte Name drin.

**Describe the solution you'd like**
Nach dem Umbenennen der Seite wird die Verwendung geprüft und der neue Name in den Widgets eingetragen,
wo der alte Name verwendet wurde.

**Comment by Feuer-sturm** [comment]
@afuerhoff welche vis2 Version hast du installiert?

**Comment by afuerhoff** [comment]
2.3.2

**Comment by foxriver76** [comment]
did this work in vis 1? I would say this ticket is an enhancement request not a bug but not 100% sure tbh

**Comment by afuerhoff** [comment]
Just tested. Don't work in vis1. It's an enhacement

**Comment by afuerhoff** [comment]
Funktioniert. Danke
