### ISSUE TITLE
Gruppe editieren funktioniert nicht

### ISSUE THREAD

**Issue by afuerhoff** [ioBroker/ioBroker.vis-2#119]
**Describe the bug**  
Nach Doppelklick auf die Gruppe oder auch über Kontextmenü kann die Gruppe nicht editiert werden.
Es wird eine leere Browserseite aufgerufen. Nach dem Aktualisieren des Browsers wird wieder der Editor angezeigt.

**Versions:**  
- Adapter version: 2.3.2
- JS-Controller version: 5.0.12
- Node version: 18.18.2
- Operating system: Debian Armbian 23.8.1 bullsey with Armbian Linux 4.19.69-rockchip

**Comment by Feuer-sturm** [comment]
@afuerhoff drücke bitte einmal F12 und poste die Fehler aus der Konsole.

**Comment by afuerhoff** [comment]
Browser ist Chrome.

Beim Gruppieren:
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/050bedfc-5de9-483b-89cc-b6bd378268d3)

Beim Editieren:
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/7c832f20-31f8-4902-bce2-67547ab7c7ff)

**Comment by afuerhoff** [comment]
@foxriver76: Dies funktioniert auch nicht. Beim Gruppe editieren aus dem Kontextmenü wird eine leere Webseite angezeigt.
Bitte wieder öffnen.

**Comment by Feuer-sturm** [comment]
@afuerhoff bitte wieder die Ausgabe der Konsole immer mit posten inkl der Angabe, welche vis Version installiert ist.

**Comment by afuerhoff** [comment]
Version: 2.3.5

![image](https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/63939389-a00b-49d1-bcbb-a57a297adf43)
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/11307290-91cc-45e3-b4fb-604a2b09260a)
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/4204f938-eeca-48fb-aeeb-51952faff785)

**Comment by afuerhoff** [comment]
Das Editieren funktioniert aber noch nicht mit der 2.6.1. Weiterhin leere Seite
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/b68625d7-5f57-4a68-b15d-fb9c27b97780)

**Comment by foxriver76** [comment]
Ich habe vorhin diesbezüglich nochmal was gepusht, sollte mit der nächsten Version hoffentlich gehen.

**Comment by afuerhoff** [comment]
@foxriver76: Geht leider immer noch nicht. Gruppe neu erstellt und dann bearbeiten gedrückt bzw. Doppelklick mit der Maus auf die Gruppe.
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/ec770350-717f-42e3-9ffc-a5e794b7523f)
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/ce56ede7-802d-481c-8626-ea2348e32ea8)

**Comment by foxriver76** [comment]
Ok das kommt durch die Umstrukturierung auf den Store, fixe ich

**Comment by foxriver76** [comment]
Bitte mit 2.6.3 neu testen und ob andere Fehlermeldung.

**Comment by afuerhoff** [comment]
Funktioniert noch nicht. 
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/48bd7de1-5906-457a-923a-36eefec50d66)
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/cefc6101-fc1a-4237-a05e-0335108fc1ad)

**Comment by foxriver76** [comment]
Hm okay, aber was du machst ist z. B. zwei Widgets anklicken, diese gruppieren per Kontextmenü, dann die Gruppe markieren und Gruppe editieren drücken im Kontextmenü? Bei mir trat der Fehler so bislang nicht auf, deshalb kann ich da leider nur iterativ fixen.

**Comment by foxriver76** [comment]
Bitte mit 2.8.0 probieren. Leider werden Gruppen die bislang kopiert wurden kaputt bleiben, aber ab sofort sollte es sauber laufen - hoffe ich ;-)

**Comment by afuerhoff** [comment]
Eine neue Gruppe angelegt und dann editiert. Es wird leider wieder eine leere Seite angezeigt
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/b002a324-0639-4537-8c2b-0dfa36ef60ed)
