### ISSUE TITLE
Bug bei group / ungroup in vis-2-beta 2.0.28 

### ISSUE THREAD

**Issue by Wurschtel** [ioBroker/ioBroker.vis-2#12]
**Describe the bug**  
Widgets werden bei "group" bzw. "ungroup" wahllos durcheinander gewürftelt.
Manchmal sind sie nach "ungroup" alle in einer Zeile.

**Versions:**  
 - Adapter version: <vis-2-beta 2.0.28>
 - JS-Controller version: <4.0.24>
 - Node version: <18.16.0>
 - Operating system: <Ubuntu 22.04.2 LTS>

**Comment by Feuer-sturm** [comment]
with vis-2 (https://forum.iobroker.net/topic/67676/vis-2-0-neuer-adapter-als-beta) version 2.2.2 group and ungroup looks ok on my system.

@Wurschtel please double check. If issue is still active, we can reopen the issue.
