### ISSUE TITLE
Cursor springt beim Einfügen eines Attributs z.B. CSS immer ans Ende der Zeichenkette 

### ISSUE THREAD

**Issue by afuerhoff** [ioBroker/ioBroker.vis-2#121]
**Describe the bug**  
Cursor springt beim Einfügen eines Attributs z.B. CSS immer ans Ende der Zeichenkette.

https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/aeae17f1-323b-4368-9d3e-0638cc1f5f07

**Versions:**  
- Adapter version: 2.3.2
- JS-Controller version: 5.0.12
- Node version: 18.18.2
- Operating system: Debian Armbian 23.8.1 bullsey with Armbian Linux 4.19.69-rockchip

**Comment by foxriver76** [comment]
Kann ich so erst mal nicht nachstellen, welcher Browser wird genutzt?

**Comment by afuerhoff** [comment]
Google Chrome

**Comment by MK-66** [comment]
@foxriver76 @afuerhoff 
Kann ich bestätigen, passiert bei mir z.B. grundsätzlich in allen Feldern mit Farbe oder color z.B. bei CSS Font & Text oder bei background-color o.ä. in allen Browsern: Chrome, Edge, Firefox.

**Comment by foxriver76** [comment]
Ok ich kann es nachstellen, bei manchen Attributen. z. B. SVG Shape widget -> Allgemein -> Linienfarbe

**Comment by foxriver76** [comment]
Note: has to be the ColorPicker component of adapter-react-v5

**Comment by MK-66** [comment]
Ok, but if you have a binding in the color field and the new binding editor cannot be called up or if you just want to modify the color without color picker, it is a little bit annoying if the crusor always jumps to the end of the field.

**Comment by foxriver76** [comment]
Of course it is a big and needs to be fixed

**Comment by MK-66** [comment]
@foxriver76 
Ok, thanks for your comment :thumbsup:

**Comment by afuerhoff** [comment]
@foxriver76: Hallo, das funktioniert immer noch nicht. Bitte wieder öffnen.

**Comment by foxriver76** [comment]
Hm but color fields now working?

**Comment by afuerhoff** [comment]
Bei mir funktionieren alle Eingaben über die Tastatur nicht korrekt. Der Cursor hat da immer ein Eigenleben. Es werden z.B. auch  Buchstaben verschluckt. Es ist auch eine Verzögerung feststellbar. Auch in den Farbfeldern macht sich das bemerkbar, wenn man die Farbe per Tastatur eingibt.

**Comment by MK-66** [comment]
@foxriver76 
Color fields sind nun ok, der Cursor springt nicht mehr ans Ende.
@foxriver76 @afuerhoff 
Aber das Verhalten mit den teilweise verschluckten Buchstaben und Verzögerungen bei Tastatureingaben, das afuerhoff im vorigen Post geschildert hat, kann ich in der Form auch bestätigen. Je größer das Projekt ist, desto mehr macht sich das in meinen Augen bemerkbar. Möglicherweise hängt dies mit der automatischen Speicherung (Diskettensymbol) zusammen. VIS versucht immer direkt nach einer Tastatureingabe zu speichern, dies dauert dann natürlich umso länger je größer das Projekt ist. So kommt es in meinen Augen dann zu diesen teilweise recht starken Verzögerungen oder auch zum Verschlucken von Buchstaben.

**Comment by Feuer-sturm** [comment]
Bei mir springt der Cursor auch, hab testweise einmal "Kommentar" und "Name" im Basic - number widget befüllt und hab dort auch den springenden Cursor oder die verschluckten Zeichen.

Es könnte was mit dem automatischen speichern zu tun haben. Wenn man ganz langsam tippt und nach jedem Buchstaben >1s Pause lässt, dann springt der Cursor nicht

**Comment by foxriver76** [comment]
Hm okay dann denke ich zwei issues sind hier gemischt, ich kenne die Logik nicht aus dem Kopf aber da sollte auf jeden Fall nicht nach jedem Buchstaben gespeichert werden sonst ist das zu erwarten, da braucht’s mindestens einen timeout 1 Sekunde keine Eingabe oder ähnliches

**Comment by MK-66** [comment]
@Feuer-sturm 
Könntest Du evtl. ein separates issue aus den zuletzt von uns geschilderten Problemen mit den verschluckten Buchstaben bei Tastatureingaben und dem automatischen Speichern erstellen?

**Comment by foxriver76** [comment]
Also ich kann es bei meinem Projekt was nur 2 Seiten hat nicht nachvollziehen, ich denke es liegt ziemlich sicher am automatischen Speichern. Wir werden mal einen kleinen Delay einbauen, dass bei einem 20 Zeichen Wort nicht 20 mal in 2 Sekunden ein riesiges JSON gespeichert wird.

**Comment by afuerhoff** [comment]
@foxriver76: Ich glaube auch, dass es mit dem Speichern zusammenhängt. Eigentlich reicht es ja aus, wenn das Feld den Fokus verliert zu speichern.

**Comment by foxriver76** [comment]
Bitte mit 2.3.6 checken.

**Comment by foxriver76** [comment]
Hm.. okay dann gerade leider keine idee. Falls jemand mal sein Projekt wo das Verhalten auftritt zur Verfügung stellen möchte, ich vermute damit lässt es sich nachstellen.

**Comment by afuerhoff** [comment]
Hab ein Testprojekt aufgesetzt mit zwei Seiten. Eine leer und die andere hat ein HTML Widget. 
Also nicht sehr groß. Dann habe ich versucht im Attribut CSS Klasse eine Zahl auszutauschen. siehe Video.
Dabei ist der Cursor wieder ans Ende gesprungen.
https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/85eaa452-01bb-40ed-b6ca-34a24768027f

**Comment by foxriver76** [comment]
ok kann es grob nachstellen, hängt wohl einfach mit dem timing des speicherns zusammen, da der timer nicht rechtzeitig resetted wird. Ich schaue morgen nochmal rein.

**Comment by foxriver76** [comment]
Bin nun relativ sicher, das Problem gefunden zu haben. Im Endeffekt, lag es daran auch für die Color Felder. Die Mischung aus controlled und uncontrolled Input resetted den Cursor beim rerender, bei schlechtem Timing. 

https://github.com/ioBroker/ioBroker.vis-2/blob/30f9773f5b0135daee4bc82b6b3ed4e940c8c19d/src/src/Attributes/Widget/index.jsx#L544

**Comment by foxriver76** [comment]
Sollte mit 2.6.2 gefixt sein. Allerdings hat das einige größere strukturelle Änderungen erfordert, weshalb es sein kann, dass ich Fälle übersehen habe in denen die Atrributsansicht im Edit Mode nicht aktualisiert werden. Dafür bitte Issues anlegen falls ihr das unter bestimmten Bedingungen wahr nehmt.

**Comment by afuerhoff** [comment]
@foxriver76: Ich hab nach dem Update die Meldung -> The vis is updating just now...
Nur das macht die Vis jetzt schon seit 20 Minuten. Im Log gibt es keine Fehlermeldungen.
Die Vis startet bei mir nicht mehr.

**Comment by afuerhoff** [comment]
@foxriver76: Hab es wieder zum Laufen bekommen. iob upload all hat es gebracht. Werde jetzt mal testen.

**Comment by afuerhoff** [comment]
Es scheint zu funktionieren. Danke

**Comment by afuerhoff** [comment]
@foxriver76: Hab nun wieder Probleme mit dem springenden Cursor. Scheint mit 2.9.5 gekommen zu sein.

**Comment by foxriver76** [comment]
In welchen Feldern?

**Comment by afuerhoff** [comment]
Ich war gerade in einer Gruppe am Editieren in der Objekt ID oder auch im CSS Feld.

**Comment by foxriver76** [comment]
auch bei anderen? Hatte es eben wieder probiert und bei mir ist er nicht gesprungen, aber kann Zufall sein. Falls du es konkretisieren kannst, gerne auch in ein neues Issue gießen.

**Comment by afuerhoff** [comment]
Ich mach dann ein neues Issue auf

**Comment by MK-66** [comment]
Also ich kann auch bestätigen, dass der Cursor wieder springt. Aufgefallen ist mir das z.B. beim Basic HTML Widget im Feld CSS Klasse und beim Gestylt zur URL springen im Feld dialog_class. 
VIS V2.9.5
Weitere Widgets oder Felder habe ich mir dann dahingehend aber nicht mehr konkret angeschaut.

**Comment by foxriver76** [comment]
Habe das im [Verdacht ](https://github.com/ioBroker/ioBroker.vis-2/commit/a574c2c5cf1bfa399e48dbfb47fe11c159ec8b2c#diff-88a358ba7ea7f3aa0320001c82b7b227aaebc829b7b43f5a3ab408c8be0ed4e7R1135)

**Comment by foxriver76** [comment]
Ok habe den Commit gefunden der wieder zu oft recalculated, ich checke mal warum das geändert wurde von BF. 

https://github.com/ioBroker/ioBroker.vis-2/commit/a574c2c5cf1bfa399e48dbfb47fe11c159ec8b2c#diff-88a358ba7ea7f3aa0320001c82b7b227aaebc829b7b43f5a3ab408c8be0ed4e7R1283

**Comment by foxriver76** [comment]
Hopefully fixed again with 2.9.6

**Comment by afuerhoff** [comment]
@foxriver76: Das Springen konnte ich jetzt nicht mehr feststellen. Scheint ok zu sein.

**Comment by MK-66** [comment]
@foxriver76: Das Springen und Verschlucken von Buchstaben ist seit V2.9.11 und V2.9.12 leider wieder da.

**Comment by afuerhoff** [comment]
@foxriver76: Habe ich auch gerade festgestellt.

**Comment by foxriver76** [comment]
Ohje.. nur css Felder oder wieder alle?

**Comment by afuerhoff** [comment]
@foxriver76: Bei mir war es im Basic String unescaped Widget. -> HTML Anhängen
Oder Badic Zeichenfolge -> Voranstellen HTML

**Comment by MK-66** [comment]
@foxriver76: Meiner Meinung nach ist das wieder in mehreren Feldern vorhanden, nicht nur bei der CSS Klasse. Habe zuletzt einiges mit den neuen Gestylt Widgets ausprobiert, da fiel mir das besonders auf. Bin aber der Meinung, dass dies auch bei den anderen Widgets wieder vermehr auftritt.

**Comment by foxriver76** [comment]
Wenn es auftritt, müsste in Browserkonsole `Recalculate fields` stehen. Ich kann es bei mir aktuell nicht nachstellen. Ein ganz konkretes Beispiel wäre hilfreich, also welches Widget, welches Feld davon. Gerne mit Export und gerne auch in einem neuen Issue, da das hier schon ziemlich lang ist und anfangs auch mehrere Probleme enthalten hat.

**Comment by MK-66** [comment]
@foxriver76: Seltsam, gestern hatte ich das Problem häufig (meistens tatsächlich im CSS Feld), heute bekomme ich es einfach nicht mehr nachgestellt, das verstehe ich jetzt gerade gar nicht... 

In der Firefox Browserkonsole kann ich beim Click in das CSS Feld außer einem Warning `Leerer String an getElementById() übergeben` und einer anschließenden Info `Rerender because of style.bindings:  !== ` auch nichts finden. 

Werde versuchen das weiter zu beobachten und vielleicht kann ich ja irgendwann etwas Konkreteres oder Nachstellbares herausfinden, dann erstelle ich gerne wie vorgeschlagen ein neues Issue.
