### ISSUE TITLE
Selektion mit STRG-Taste funktioniert nicht

### ISSUE THREAD

**Issue by afuerhoff** [ioBroker/ioBroker.vis-2#123]
**Describe the bug**  
Wenn man mit gedrückter STRG-Taste mit der Maus zwei Widgets selektieren möchte wird eine leere Seite aufgerufen.
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/c41bf66b-41f9-4956-8c2e-3d177a40b91b)

**Versions:**  
 - Adapter version: 2.3.3
- JS-Controller version: 5.0.12
- Node version: 18.18.2
- Operating system: Debian Armbian 23.8.1 bullsey with Armbian Linux 4.19.69-rockchip
- Browser: Google Chrome

**Comment by MK-66** [comment]
Auch beim Selektieren mehrerer Widgets über das Auswahlmenü wird ebenfalls nur eine leere weiße Seite angezeigt mit den gleichen Fehlermeldungen in der Browserkonsole wie bei afuerhoff.

Dieser Fehler hat sich erst in Version 2.3.3 eingeschlichen, in 2.3.2 funktioniert dies noch ganz normal.

![Screenshot Widgets Selektieren](https://github.com/ioBroker/ioBroker.vis-2/assets/56516310/19e34ad7-0475-4dba-bdd7-927792da39fd)

**Comment by foxriver76** [comment]
will be fixed in next release

**Comment by foxriver76** [comment]
please check with 2.3.4

**Comment by afuerhoff** [comment]
No problem anymore

**Comment by MK-66** [comment]
Yes, bug is fixed in 2.3.4  :thumbsup:

**Comment by foxriver76** [comment]
thanks for the feedback :+1:
