### ISSUE TITLE
App Leiste sollte modifiziert werden können

### ISSUE THREAD

**Issue by afuerhoff** [ioBroker/ioBroker.vis-2#125]
**Is your feature request related to a problem? Please describe.**
Der Titel "EG_Neu" in der App-Leiste wird vom Seitennamen abgeleitet. Dieser sollte einstellbar sein.
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/4dae9fff-e0d4-41d1-aae7-cf1f8b574c55)
Weiterhin wäre es schön, wenn man in der App-Leiste auch z.B. Buttons platzieren könnte. Hierzu könnte man
ein View in Widget benutzen, dass dann für die App-Leiste ausgewählt werden muss.

**Comment by Feuer-sturm** [comment]
@afuerhoff Welche vis2 version hast du installiert?
Was ist genau für dich die App Leiste? Meinst du die Navigationsleiste?
Den Namen vom Menü kannst du hier einstellen
![grafik](https://github.com/ioBroker/ioBroker.vis-2/assets/25422320/9903d6bd-1cb9-4368-80bd-66be2a82b7af)

Für welchen Use Case möchtest du im Menünamen einen Button hinterlegen?

**Comment by afuerhoff** [comment]
Inzwischen 2.3.5
Unter Navigation im Bild oben zu sehen: App-Leiste anzeigen. 
Der Titel der App- Leiste ist nicht einstellbar.
In der App-Leiste möchte ich z.B. Button hinterlegen. Habe ich heute mit dem Material Design von Uhula auch.

**Comment by afuerhoff** [comment]
Hier noch einen Auszug aus der Uhula Dokumentation als Beispiel.
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/d7524467-6adc-4585-b877-553049cd0bf0)

**Comment by afuerhoff** [comment]
Dieser Teil "_Der Titel "EG_Neu" in der App-Leiste wird vom Seitennamen abgeleitet. Dieser sollte einstellbar sein._" funktioniert jetzt mit v2.6.1. Der Rest ist noch nicht implementiert.
