### ISSUE TITLE
Dateien durchsuchen - Pfadtext zu dunkel

### ISSUE THREAD

**Issue by afuerhoff** [ioBroker/ioBroker.vis-2#127]
**Is your feature request related to a problem? Please describe.**
Der Pfadtext ist aufgrund des dunklen Hintergrunds nicht gut zu lesen. 
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/d79fa474-983e-4da7-932f-06d1be8992c0)

**Describe the solution you'd like**
Es sollte eine hellere Textfarbe oder ein hellerer Hintergrund  gewählt werden.

**Comment by foxriver76** [comment]
Note for myself: needs to be fixed in adapter-react-v5 `SelectFileDialog`  and only a problem for the `light` theme

**Comment by afuerhoff** [comment]
Hallo, funktioniert jetzt mit 2.3.5.
