### ISSUE TITLE
white area in vis2 editor on the right side

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.vis-2#131]
**Describe the bug**  
Since vis2 version 2.3.3 there is a space on the right side which can not be reduced
Bug is also in 2.3.5

**Versions:**  
 - Adapter version: vis2 2.3.5

**Additional context**  
![grafik](https://github.com/ioBroker/ioBroker.vis-2/assets/25422320/12741e3f-4983-4575-be73-35bb7012d696)

**Comment by sigi2345** [comment]
Dito

**Comment by foxriver76** [comment]
any special settings? For me it is not there in Chrome and Firefox.

**Comment by afuerhoff** [comment]
I have the same problem in Chrome.

**Comment by sigi2345** [comment]
> any special settings? For me it is not there in Chrome and Firefox.

Nach Umstellung im WEB Adapter auf Port 8095 funktioniert es wieder.

**Comment by afuerhoff** [comment]
Kann ich bestätigen. Port auf 8095 geändert alles ok. Port wieder zurück auf 8082 dann selbes Problem.

**Comment by foxriver76** [comment]
mal privaten Tab probiert? nicht das es iwas mit dem Cache ist

**Comment by afuerhoff** [comment]
Im Inkognitofenster funktioniert es auch mit der 8082. Cache löschen hat aber keinen Erfolg gebracht.

**Comment by GermanBluefox** [comment]
Ich kann das auch nicht reproduzieren. Ich vermute es ist irgendeine Chrom(FF)-Extention, die Klassen überlädt

**Comment by Feuer-sturm** [comment]
Im privaten Tab tritt das Problem bei mir auch nicht auf.

**Comment by Feuer-sturm** [comment]
after update to vis 2.7.0 everything is fine on my system.

**Comment by afuerhoff** [comment]
Bei mir funktioniert es ebenfalls mit der v2.7.0.

**Comment by patti9000** [comment]
Bei mir mit v2.9.4 tritt diese Problem auf.
MacOS:
- Safari: Erneutes Laden ohne Cache bringt nichts. Im privaten Modus passt alles.
- Edge Browser: auch keine Probleme

Es scheint für mich als hätte ich mich irgendwo verklickt und das lässt sich nicht mehr korrigieren, weil es irgendwo gespeichert bleibt.

**Comment by Feuer-sturm** [comment]
@patti9000 Bitte einmal auf 2.9.5 aktualisieren. Ändert sich das Verhalten?

**Comment by patti9000** [comment]
@Feuer-sturm: Gerade upgedatet - leider immer noch dasselbe. Kann ich mit irgendwelche weiteren Infos dienen?

**Comment by DaisyMaus** [comment]
habe es nur im Google Chrome Browser. Alle anderen Browser gehen
