### ISSUE TITLE
Suche STRG f funktioniert nicht im CSS Bereich

### ISSUE THREAD

**Issue by afuerhoff** [ioBroker/ioBroker.vis-2#133]
**Describe the bug**  
Im Vis1 Adapter kann man den CSS Bereich durchsuchen -> siehe Bild:
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/0b844d80-5f05-4770-99b5-276641b1b210)
Das funktioniert in Vis2 nicht. Da kommt dieser Fehler wenn man STRG f drückt. Der Fehlerzähler unten läuft hier ständig weiter hoch.
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/36a50bfa-e67b-4f8a-bdb3-cfeefcaf7c62)

**Versions:**  
- Adapter version: 2.3.5
- JS-Controller version: 5.0.12
- Node version: 18.18.2
- Operating system: Debian Armbian 23.8.1 bullsey with Armbian Linux 4.19.69-rockchip
- Browser: Google Chrome

**Comment by afuerhoff** [comment]
Ich habe es gerade nochmal in der Version 2.6.0 getestet. Jetzt funktioniert die Suche. 
Ich habe allerdings inzwischen auch den ioBroker Server gewechselt. Ist jetzt ein Proxmox basiertes Debian 12 System

**Comment by Feuer-sturm** [comment]
Suche im CSS Bereich funktioniert bei mir auch mit 2.6.0.
@afuerhoff Schließe das issue hier erstmal.

**Comment by afuerhoff** [comment]
Ist für mich ok
