### ISSUE TITLE
basic-html-widget: html scripts not working

### ISSUE THREAD

**Issue by goesebrecht1** [ioBroker/ioBroker.vis-2#136]
v2.3.5
basic-html-widget

Scripts in html are not executed. 
Example:

`<script>
     console.log('hi');
</script>`

In the example: There is no output in the console.

---

Skripte im html werden nicht ausgeführt. Im Beispiel: Es erfolgt keine Ausgabe in der Konsole.

**Comment by foxriver76** [comment]
Note for devs: 

https://stackoverflow.com/questions/35614809/react-script-tag-not-working-when-inserted-using-dangerouslysetinnerhtml

We would need to work around this limitation.
