### ISSUE TITLE
Seitennamen werden im Editor nur In Großschreibweise angezeigt

### ISSUE THREAD

**Issue by afuerhoff** [ioBroker/ioBroker.vis-2#137]
**Describe the bug**  
Seitennamen werden immer in Großschreibweise im Editor angezeigt. 
Im Bild der Name wurde contEG geschrieben. Aus meiner Sicht wird die Lesbarkeit dadurch verschlechtert.
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/8045ec89-5f79-4d28-9108-1c02647ca33b)

- Adapter version: 2.3.5
- JS-Controller version: 5.0.12
- Node version: 18.18.2
- Operating system: Debian Armbian 23.8.1 bullsey with Armbian Linux 4.19.69-rockchip
- Browser: Google Chrome

**Comment by afuerhoff** [comment]
Ich habe das Problem weiterhin.

![image](https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/b852b2df-a41f-4806-9901-e7c189a9249c)

![image](https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/cc8cc324-cf73-430a-a216-b4ff848328ef)

**Comment by foxriver76** [comment]
Ja das wird erst in die Version nach 2.4.0 kommen

**Comment by foxriver76** [comment]
Ist auf github gefixt aber nicht released
