### ISSUE TITLE
Basic Bool SVG lädt Bild beim ersten Aufruf nicht

### ISSUE THREAD

**Issue by afuerhoff** [ioBroker/ioBroker.vis-2#149]
**Describe the bug**  
Erst nach einem Wechsel der Seite mit dem SVG Widget wird das Bild geladen und dann beim Wechsel zurück auch angezeigt.

**Versions:**  
- Adapter version: 2.4.0
- JS-Controller version: 5.0.12
- Node version: 18.18.2
- Operating system: Debian Armbian 23.8.1 bullsey with Armbian Linux 4.19.69-rockchip
- Browser: Google Chrome

**Comment by foxriver76** [comment]
fixed with 2.5.0 @afuerhoff - can you confirm?

**Comment by afuerhoff** [comment]
Works with 2.5.0. Thank you
