### ISSUE TITLE
Basic Bar Widget - Bindings do not update in VIS runtime

### ISSUE THREAD

**Issue by MK-66** [ioBroker/ioBroker.vis-2#153]
**Describe the bug**  
With the Basic Bar widget, the bindings in the widget do not update when the page is loaded in VIS runtime resp. are not up to date. 

Only when the data point of the binding is updated again in the course of time by an adapter or similar (after the page has been loaded), the binding then is also up-to-date in the runtime. 

In the Binding Editor the "Calculated value: green" is displayed correctly , but not in the VIS runtime when the page is loaded.

With a normal Basic HTML Widget bindings work correctly, so far I have only noticed this error with the Basic Bar Widget, regardless of whether it is a binding in the colour field or  in the min. max. field.

**Expected behavior**  
Bindings should be analysed immediately when the page is loaded, not only when the binding data point is updated.

**Screenshots**  

Basic Bar Widget - VIS Editor
![Basic Bar Widget](https://github.com/ioBroker/ioBroker.vis-2/assets/56516310/d5eb4e74-3d50-419b-8e5e-dbc168570476)

Basic Bar Widget - Binding Editor
![Basic Bar Binding](https://github.com/ioBroker/ioBroker.vis-2/assets/56516310/734eb9c9-3c7f-4b18-b283-94b84f6fe62a)4

Basic Bar Widget - VIS Runtime
![Basic Bar Runtime](https://github.com/ioBroker/ioBroker.vis-2/assets/56516310/873a1012-dac1-4a7f-95f4-95f4fec872bb)

**Versions:**  
 - Adapter version: 2.4.0
 - JS-Controller version: 5.0.16
 - Node version: 18.18.2
 - Operating system: Debian 12

**Additional context**  
This error in the bindings of the basic bar widget was also present in previous versions.

**Comment by MK-66** [comment]
V2.5.0 - Basic Bar Widget - Bindings no longer work at all

In new Version VIS V2.5.0 the bindings of the Basic Bar Widget no longer work at all. In the Binding Editor "Calculated value" is displayed correctly, in the Editor or the Runtime it is unfortunately displayed incorrectly resp. is no longer evaluated at all. Even after updating the data point from the binding, this remains displayed incorrectly and does not change.

Bindings no longer work at all in the Basic Number widget either.

I'll have a look to see which widgets are also affected by the bindings that no longer work.

**Comment by foxriver76** [comment]
This is still a problem with 2.6.0 I guess?

**Comment by MK-66** [comment]
@foxriver76 
Yes, you are right. Bindings in "normal" widgets work again with V2.6.0, but the problem with the basic bar widgets described in my first post still exists with V2.6.0.

**Comment by foxriver76** [comment]
Dev note: The bindings are correctly calculated, but somehow he often does not update the widget. As this is a old widget, we should migrate it first, maybe bug is then fixed anyway.

**Comment by MK-66** [comment]
@foxriver76 
Ok, would be great if I could get a message when the old Basic Bar Widget is migrated so that I could test it on my VIS-2.

**Comment by foxriver76** [comment]
Please try with 2.7.0

**Comment by MK-66** [comment]
@foxriver76 
Great work, Basic Bar Widget now works, with V.2.7.0, thank you very much!
