### ISSUE TITLE
V2.5.0 - Bindings no longer work

### ISSUE THREAD

**Issue by MK-66** [ioBroker/ioBroker.vis-2#154]
**Describe the bug**  
With version V2.5.0, bindings in most basic widgets (number, string, etc.) no longer work. Neither in the HTML fields "Voranstellen HTML", etc., nor e.g. in the colour field.

Calculated value is displayed correctly in the Binding Editor, but in the VIS runtime or in the editor itself, the bindings are displayed incorrectly or are apparently no longer evaluated at all. Datapoints in the binding are displayed as NaN in the widget.

Apparently the bindings only work in the Basic HTML widget and in the Basic string widget. However, I have not checked every single widget with its fields for working bindings.

**Expected behavior**  
Bindings should work again as in the previous VIS-2 versions or even better as it is in VIS1.

**Screenshots**  

Basic Number Widget - Editor

![Basic Number Widget Bindings 600](https://github.com/ioBroker/ioBroker.vis-2/assets/56516310/62d2959a-f218-4b68-975d-ca324cfae447)

Basic Number Widget - Binding Editor

![Basic Number Widget Binding Editor](https://github.com/ioBroker/ioBroker.vis-2/assets/56516310/d65b5729-03f1-4b15-89a3-4330fde1cf3b)

Basic Number Widget - Runtime
![Basic Number Widget Bindings Runtime](https://github.com/ioBroker/ioBroker.vis-2/assets/56516310/df950a6d-5beb-4c46-bfad-71a0a5f7cd1e)
**Versions:**  
 - Adapter version: 2.5.0
 - JS-Controller version: 5.0.16
 - Node version: 18.18.2
 - Operating system: Debian 12

**Additional context**  
In V2.4.0 bindings still worked with the basic widgets, here there were only problems with the basic bar widget.

**Comment by smilie108** [comment]
Hi in my  case i have html strings in objekt and in editor it schows all ok but on live ther is message File undefined not found: {}
In Editor 
Calculate value:http://192.168.1.91:3000/d-solo/bdd7c3c0-1916-434a-ab00-e6af63dfe84d/netzdaten?orgId=1&from=1699734900024&to=1699832100024&panelId=3width="450" height="200" frameborder="0"
0_userdata.0.timeselctor.Wechselrichter_Charts.Chart_1.Fertige_Url.val:http://192.168.1.91:3000/d-solo/bdd7c3c0-1916-434a-ab00-e6af63dfe84d/netzdaten?orgId=1&from=1699734900024&to=1699832100024&panelId=3width="450" height="200" frameborder="0" [string]
Old style
New style

**Comment by afuerhoff** [comment]
Bei mir funktioniert es noch nicht. Es müsste der erste Eintrag gewählt werden.
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/6b812812-b343-4599-a0ca-52568a71c513)

Vor der Änderung wurde der richtige Value und das richtige Ergebnis angezeigt. Nur die Auswirkung im Editor war falsch.
Jetzt stimmt der Editor nicht und das Binding auch nicht.

**Comment by smilie108** [comment]
glaube wir müssen auf 2.5.1 oder so warten ;)

**Comment by afuerhoff** [comment]
Guter Tipp. Hatte ich beim Rumprobieren in Anführungszeichen gesetzt und dann nicht wieder rausgenommen. Ohne Anführungszeichen passt es. Danke

**Comment by smilie108** [comment]
;) jop passt wieder 2.6 ist erst grad bei mir aufgeschlagen ;)
