### ISSUE TITLE
2.5.0 Darstellungsprobleme beim Widget Basic Zeichenfolge

### ISSUE THREAD

**Issue by Spike08122** [ioBroker/ioBroker.vis-2#156]
**Describe the bug**  
neben dem Widget ist ein Balken zu sehen

**Screenshots & Logfiles**  

![Screenshot 2023-11-11 201019](https://github.com/ioBroker/ioBroker.vis-2/assets/147330127/a1018958-fe1d-46d3-8228-41cdd7d5c779)

**Versions:**  
 - Adapter version: 2.5.0
 - JS-Controller version: v18.18.0
 - Node version: v18.18.0
 - Operating system: Debian 10

**Comment by MK-66** [comment]
@Spike08122 
Diese kleinen grauen Felder kommen von der Einstellung "Zeige letzte Änderung" ganz unten bei den Widgets. Also Haken dort rausnehmen, dann sind die kleinen grauen Felder weg. Bin ich auch anfangs drüber gestolpert und habe gedacht das wäre ein scrollbalken o.ä. und ich müsste beim widget overflow auf hidden setzen.

**Comment by Spike08122** [comment]
@MK-66 Danke für die Info. Wollte auch was beitragen und dann war es doch kein Bug, was ja grundsätzlich gut ist
