### ISSUE TITLE
Active Widgets - Add checkboxes for select all and deselect all widgets

### ISSUE THREAD

**Issue by MK-66** [ioBroker/ioBroker.vis-2#157]
**Description**
When selecting the active widgets in the editor, checkboxes for select all widgets and deselect all widgets would be very helpful, as it was in VIS1.

Or is there perhaps a key combination for this that I don't know at the moment?

**Screenshots**
Select Widgets VIS2

![Select Widgets VIS2](https://github.com/ioBroker/ioBroker.vis-2/assets/56516310/f150fbed-45d5-4fa1-93c4-36527ed67196)

Select Widgets VIS1

![Select Widgets VIS1](https://github.com/ioBroker/ioBroker.vis-2/assets/56516310/9659dc65-aa0d-4703-818c-31d053d106da)

**Comment by afuerhoff** [comment]
@MK-66: Als Workaround kannst Du im Editor selbst STRG-A benutzen.

**Comment by MK-66** [comment]
@afuerhoff 
Ah ok, vielen Dank für die Info.
