### ISSUE TITLE
Bei der Auswahl eines eCharts wird eine falsche Ordnerstruktur dargestellt

### ISSUE THREAD

**Issue by afuerhoff** [ioBroker/ioBroker.vis-2#158]
**Describe the bug**  
Die Auswahl echarts_echart_oid im Widget E-CHarts zeigt eine falsche Ordnerstruktur. Auch nach Aktualisierung der Webseite
ändert sich das nicht.

Vis-2:
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/d7ee1700-0d8e-492a-9d83-362e4b19bc3e)
eChart:
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/84d77161-99d1-47e1-beed-e2aa141cde3b)

**Versions:**  
Adapter version: 2.5.0
JS-Controller version: 5.0.12
Node version: 18.18.2
Operating system: Proxmox LXC Container Debian 12
Browser: Google Chrome

**Comment by foxriver76** [comment]
> Vis-2:
> ![image](https://user-images.githubusercontent.com/50245893/282289540-d7ee1700-0d8e-492a-9d83-362e4b19bc3e.png)

Silly question: How do I open this editor?

**Comment by afuerhoff** [comment]
Bei der Auswahl des eCharts:
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/69dd76f7-9dab-4cd0-aaa8-9c529958ba0c)

**Comment by foxriver76** [comment]
Ah okay, dann schaue ich nochmal - ich habe da eben nur nen normalen Object Browser bekommen

**Comment by foxriver76** [comment]
Habe gerade ein bisschen rumgespielt und es scheint bei mir zu passen. Wenn ich etwas hinzufüge, muss ich das Browserfenster allerdigns neu laden, damit die Änderungen sichtbar werden.

Da das Widget vom echarts Adapter bereitgestellt wird, welche echarts Version ist installiert?
Und hast du mal ein privaten Tab probiert?

**Comment by afuerhoff** [comment]
Aktualisiert hatte ich auch nachdem ich die Ordner in eCharts angelegt habe.
Im Inkognito Fenster das gleiche Problem.
eCharts v1.6.1 ist installiert.

PS: Ich habe die eCharts Namen mit Punkten versehen. z.B. EG_Flur/EG.Flur.Bew
Vielleicht ist dass das Problem?

**Comment by foxriver76** [comment]
ich vermute fast, dass eine alte echarts version die Punkte im Namen nicht richtig ersetzt hat. Laut der ID vom ersten Post würde ich sogar sagen, dass eher das in ECHarts selbst falsch ist statt das im Widget.

Ich meine hier `echarts.0.EG_Flur.Bew` was dann in echarts als `EG_Flur/EG Flur Bew` angezeigt wurde, da hätte ich eigentlich `EG_Flur/Bew` wie im Widget erwartet.

**Comment by foxriver76** [comment]
evtl. kann @GermanBluefox was zu sagen, ob da zwischenzeitlich was gefixt wurde, was aber nur bei neu anlegen funktioniert.

**Comment by afuerhoff** [comment]
@foxriver76: Es wurde scheinbar dieser eChart-Name "EG.Flur.Bew" in zwei Ordner EG und Unterordner EG_Flur zerlegt. Das Chart selber hieß ja nur noch Bew. Nach dem umbenennen hab ich jetzt leider einen Ordner EG als Leiche, den ich im eCharts nicht löschen kann. Der ist jetzt nach dem Aktualisieren verschwunden. Jetzt scheint die Objektstruktur zu passen.

**Comment by foxriver76** [comment]
im Zweifel kannst du ihn vermutlich über den Objektbaum löschen, aber ist sicher ein Issue in echarts wert

**Comment by afuerhoff** [comment]
Der Ordner wurde nur noch angezeigt. War dann nach dem Aktualisieren verschwunden. Issue habe ich schon erstellt.

**Comment by afuerhoff** [comment]
@foxriver76 : Wenn von @GermanBluefox keine weitere Info kommt, könnte aus meiner Sicht das Ticket geschlossen werden.
Ich denke, dass der eCharts Adapter die Struktur sauber bereitstellen muss.
