### ISSUE TITLE
V2.5.0 jqui widget missing // crtl - Icon State

### ISSUE THREAD

**Issue by Knallix** [ioBroker/ioBroker.vis-2#159]
**Describe the bug**  
I work a lot with the "crtl - Icon State" widget. Unfortunately I can't find it in the overview. 
Does this no longer exist or is it called something different now?

**To Reproduce**  

Here is an export:
`[{"tpl":"tplIconState","data":{"oid":"nothing_selected","g_fixed":true,"g_visibility":false,"g_css_font_text":false,"g_css_background":false,"g_css_shadow_padding":true,"g_css_border":false,"g_gestures":false,"g_signals":false,"visibility-cond":"==","visibility-val":1,"visibility-groups-action":"hide","signals-cond-0":"==","signals-val-0":true,"signals-icon-0":"/vis/signals/lowbattery.png","signals-icon-size-0":0,"signals-blink-0":false,"signals-horz-0":0,"signals-vert-0":0,"signals-hide-edit-0":false,"signals-cond-1":"==","signals-val-1":true,"signals-icon-1":"/vis/signals/lowbattery.png","signals-icon-size-1":0,"signals-blink-1":false,"signals-horz-1":0,"signals-vert-1":0,"signals-hide-edit-1":false,"signals-cond-2":"==","signals-val-2":true,"signals-icon-2":"/vis/signals/lowbattery.png","signals-icon-size-2":0,"signals-blink-2":false,"signals-horz-2":0,"signals-vert-2":0,"signals-hide-edit-2":false,"src":"","class":"mdui-navitem mdui-lnavbutton mdui-tooltip?text:Öffnet+und+schließt+die+linke+Navigation","lc-type":"last-change","lc-is-interval":true,"lc-is-moment":false,"lc-format":"","lc-position-vert":"top","lc-position-horz":"right","lc-offset-vert":0,"lc-offset-horz":0,"lc-font-size":"12px","lc-font-family":"","lc-font-style":"","lc-bkg-color":"","lc-color":"","lc-border-width":"0","lc-border-style":"","lc-border-color":"","lc-border-radius":10,"lc-zindex":0,"text":"<i class=\"material-icons\">menu</i>"},"style":{"left":"2px","top":"2px","width":"36px","height":"36px","padding":"6"},"widgetSet":"jqui"}]`

**Expected behavior**  

**Screenshots & Logfiles**  
VIS 1
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/42406048/055983dd-ee53-44ad-a4f9-6780c9f2aa52)
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/42406048/499fe9c8-a828-48c9-9332-1247d33290c5)

**Versions:**  
 - Adapter version: V2.5.0
 - JS-Controller version: 5.0.12 
 - Node version: v16.19.1
 - Operating system: debian

**Comment by foxriver76** [comment]
Schau mal unter "Gestylt" "ctrl - Icon State"

**Comment by Homezecke** [comment]
Ich hänge das hier mal ran:

 "Gestylt": Navigationstaste und Navigationssymbol. Wenn bei diesen Widgets  "jqui widget" ein Haken gemacht wird, verschwindet die Möglichkeit ein Symbol festzulegen. War eines angelegt, wird dies auch nicht mehr angezeigt.

**Comment by foxriver76** [comment]
@Knallix dein Widget lässt sich auch erfolgreich importieren bei mir 

![grafik](https://github.com/ioBroker/ioBroker.vis-2/assets/25484431/beaf5ed9-22c5-447c-8fb9-aa2a62d30b4b)
