### ISSUE TITLE
Add possibility to sort pages in alphabetical order

### ISSUE THREAD

**Issue by MK-66** [ioBroker/ioBroker.vis-2#163]
### No existing issues.

- [X] There is no existing issue for my request.

### Related problems

Add possibility to sort pages in alphabetical order.

### Description

Is it possible to sort pages in VIS-2 alphabetically again instead of by the last page added?
This would allow each user to determine the order of the pages themselves by naming them accordingly, as is the case in VIS1. This would make it much easier to select the relevant page when searching for a page in a large project. 

**Screenshot Teil einer Seitenauswahl**

![Seitensortierung](https://github.com/ioBroker/ioBroker.vis-2/assets/56516310/3e10883b-2783-479f-a241-123deb2262be)

### Additional context

**Versions:**

- Adapter version: 2.6.0
- JS-Controller version: 5.0.16
- Node version: 18.18.2
- Operating system: Debian 12

**Comment by foxriver76** [comment]
From my point of view it should simply be sorted alphabetically, no ability to resort it. Correct?

**Comment by MK-66** [comment]
Yes, exactly, I think that's quite sufficient. 
As I said, each user can then determine the order of the pages themselves by naming them accordingly.
This could possibly also be an advantage when using the navigation.

**Comment by Feuer-sturm** [comment]
reference to https://github.com/ioBroker/ioBroker.vis-2/issues/15
@foxriver76 Is it possible to change the order by drag and drop?

**Comment by afuerhoff** [comment]
Hab hier gerade getestet. p müsste doch vor v kommen. 
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/45afc91d-f762-406f-8a18-2380ff5824a2)

**Comment by foxriver76** [comment]
Ja sollte, privater Tab dasselbe?

**Comment by afuerhoff** [comment]
Privater Tab dasselbe Ergebnis. Auch Cache löschen hat nichts verändert.

**Comment by ammawel** [comment]
> Yes, exactly, I think that's quite sufficient.
> As I said, each user can then determine the order of the pages themselves by naming them accordingly.

Diese Verallgemeinerung für alle Nutzer finde ich etwas gewagt - zumal man die Seiten in der Auswahl zwar schon ziehen, aber nicht ablegen kann.
Eine Sortierung mit "drag and drop" scheint also ursprünglich vorgesehen zu sein und sollte alle Möglichkeiten bieten.

**Comment by MK-66** [comment]
@ammawel 
Sorry, wollte niemanden zu Nahe treten oder für alle Nutzer sprechen. Ich dachte nur das die alphabetische Sortierung die einfachste Möglichkeit für die Entwickler wäre die Seiten überhaupt sortierbar zu machen.

**Comment by afuerhoff** [comment]
Sortierung über eine Benennung finde ich auch nicht so optimal.

**Comment by foxriver76** [comment]
Falles es um das navigationswidget geht, ack.

Aber die Sortierung in diesem Menu finde ich alphabetisch vollkommen i. O., war soweit ich weiß in vis 1 genau so.

**Comment by MK-66** [comment]
@afuerhoff @ammawel 
Ok, ganz optimal wäre das vielleicht auch nicht. Dachte wie gesagt halt nur, dass dies ggf. schnell umsetzbar wäre für die Entwickler. Zumindest für mich hat es in VIS1 auch sehr gut funktioniert und ich konnte meine Seiten im Dropdown Menü durch die alphabetische Sortierung recht schnell wiederfinden.

**Comment by afuerhoff** [comment]
@foxriver76: Frage ist, ob es für die Menüsortierung dann noch einen separaten Dialog gibt?

**Comment by foxriver76** [comment]
> @foxriver76: Hab hier gerade getestet. p müsste doch vor v kommen. ![image](https://user-images.githubusercontent.com/50245893/283760573-45afc91d-f762-406f-8a18-2380ff5824a2.png)

In welchem Fenster ist das denn bei dir? Habe eben zuerst `vWohnzimmer` erstellt, dann `pWohnzimmer` und es wurde korrekt einsortiert. 

![grafik](https://github.com/ioBroker/ioBroker.vis-2/assets/25484431/51417f9c-89fe-49e8-9c09-c94d0b81bc89)

**Comment by afuerhoff** [comment]
Das ist schon das Fenster. Ich habe aber auch Ordner erstellt.

**Comment by MK-66** [comment]
@foxriver76 
Thank you, alphabetical sorting does work to some extent, but only when renaming the page for the first time. If you then rename the same page a second time, it is unfortunately no longer sorted to the correct position, but the page remains where it was (deleting the browser cache does not help).

Unfortunately, the pages in an existing project (imported from VIS1) are not yet sorted alphabetically in the correct position. Perhaps this can be improved again in one of the next versions. 

I also exported my project to VIS-2 and imported it again, but the pages are still not sorted correctly alphabetically.

**Screenshot of first renaming - correct sorting**

![RenamePages1](https://github.com/ioBroker/ioBroker.vis-2/assets/56516310/a022c357-cf60-4b82-89de-ed8bba7f4a93)

**Screenshot of renaming again - incorrect sorting**

![RenamePages2](https://github.com/ioBroker/ioBroker.vis-2/assets/56516310/16011cf2-fb7a-45e4-9b65-d491a63fdc80)

Could you possibly mark the issue as open again, somehow I can't find out how to do this on Github...?

**Comment by afuerhoff** [comment]
@foxriver76: Same here.

**Comment by foxriver76** [comment]
Commit was after 2.7.0, but only fixing folders

**Comment by foxriver76** [comment]
[Bildschirmaufzeichnung vom 23.11.2023, 08:13:40.webm](https://github.com/ioBroker/ioBroker.vis-2/assets/25484431/b16882cc-bd77-4a1a-bf47-30e979a4c5e2)

but should be fixed with upcoming version or is it another scenario to replicate it?

**Comment by afuerhoff** [comment]
@foxriver76 : Mit Seiten funktioniert es bei mir. Die Ordner sind nicht sortiert. Gerade in einem neuen Projekt getestet.

https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/c3b5d0f3-d0f7-4e1c-9e32-6706515a5ff6

**Comment by foxriver76** [comment]
Hm villt liegt es noch an folder in folder wenn du’s if ebene von eg anlegst wird es da sortiert?

**Comment by afuerhoff** [comment]
Im EG wird es auch nicht sortiert.
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/81deb9df-1242-462d-992b-84e6086c7905)

**Comment by foxriver76** [comment]
Kann es nicht nachstellen, bei mir werden alle Ebenen sortiert. Kannst du nochmal privaten Tab probieren nur um das unwarscheinliche auszuschließen. 

@MK-66 wie ist denn das Verhalten bei dir?

**Comment by afuerhoff** [comment]
Inkognito Tab ist das gleiche Bild. Keine Änderung

**Comment by foxriver76** [comment]
Kannst du mal das Projekt exportieren und hier posten (gerne auch anonymer Export) möchte das gerne nachvollziehen und kann es leider nicht nachstellen.

**Comment by afuerhoff** [comment]
[2023-11-25-HomeAF.zip](https://github.com/ioBroker/ioBroker.vis-2/files/13464416/2023-11-25-HomeAF.zip)

**Comment by MK-66** [comment]
@foxriver76 
Also ich hab mit V2.8.0 immer noch das Problem, dass beim erstmaligen Umbenennen die Seite richtig einsortiert wird, beim zweiten Umbenennen aber nicht mehr, wie ich das ein paar Posts zuvor in Englisch geschildert hatte. Ordner habe ich im Übrigen derzeit noch nicht erstellt oder ausprobiert. 

Hier noch der Anfangstext von dem Post, den ich meinte:
*Thank you, alphabetical sorting does work to some extent, but only when renaming the page for the first time. If you then rename the same page a second time, it is unfortunately no longer sorted to the correct position, but the page remains where it was (deleting the browser cache does not help)...*

**Comment by foxriver76** [comment]
> [2023-11-25-HomeAF.zip](https://github.com/ioBroker/ioBroker.vis-2/files/13464416/2023-11-25-HomeAF.zip)

Also die Seiten des Projektes sind bei mir komplett korrekt sortiert und wenn ich Seite oder Ordner umbenenne wird es auch korrekt einsortiert.

**Comment by afuerhoff** [comment]
Ich habe nochmal einen neuen Container unter Proxmox aufgesetzt und die Adapter nicht per Backitup eingespielt. Gleiches Verhalten. Da ist mir nur der Unterschied mit dem js-controller aufgefallen. 
Kann es am Debian 12 liegen?

**Comment by MK-66** [comment]
@foxriver76 
Welchen Browser verwendest Du? Ich habe es gerade mit Firefox ausprobiert, da werden bei mir dann doch tatsächlich alle Seiten in der korrekten Reihenfolge angezeigt. 

Bei Chrome und Edge hingegen bleibt es bei mir wie geschildert falsch sortiert, auch nach Browsercache löschen.

**Comment by Feuer-sturm** [comment]
Ich sehe bei mir auch das Verhalten das in Firefox die Sortierung automatisch richtig funktioniert und in Chrome nicht

Links Chrome, Rechts Firefox. Neu Laden des Editors hift bei Chrome auch nicht (in der Hoffnung, das nach einem Reload die Ordner/Seiten neu sortiert sind)

![grafik](https://github.com/ioBroker/ioBroker.vis-2/assets/25422320/091ec545-7a3f-4439-a1c4-56c9154acc64)

**Comment by foxriver76** [comment]
in Chrome konnte ich es nachstellen und fixen danke

**Comment by MK-66** [comment]
@foxriver76 
Super, in dem Zusammenhang einmal vielen Dank für Deine unermüdliche Arbeit :thumbsup: :blush:
