### ISSUE TITLE
[bug]: Vis 2 Beta startet nicht komplet durch / linke Seite läuft Ladebalken durchgängig. Nicht zu verwenden

### ISSUE THREAD

**Issue by ps-neotrace** [ioBroker/ioBroker.vis-2#165]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Moin in die Runde, keine Ahnung in wie weit ich das selber beheben kann, 
Liezens ist geprüft und OK
VIS 1 läuft nach wie vor super. Ohne Einschränkungen. 
Vor knapp einem Jahr als die VIS 2 Beta auf den Markt kam hatte ich bereits so ein Problem und habe es damals auf das System geschoben. Mitlerweile ist es aber ein PI 4 mit 8Gb. Das Problem ist schlimmer. Ich kann mit dem System so gar nichts machen. Ich habe den Adapter nun schonmal deinstalliert und neu installiert. Ohne Erfolg. 

VIS 2 kann ich leider so gar nicht verwenden, denn es läuft dieser Ladebalken durchgängig 

System ist ein Raspi 4 8GB / 

### To Reproduce

Da ich nur installiert habe, und das System nicht richtig lädt... Was soll ich erwartet haben. Das es läuft?
Wird im Adapter auch ohne Probleme dargestellt. 
![Vis2 02](https://github.com/ioBroker/ioBroker.vis-2/assets/96009604/c6b5295f-e471-4eee-bb98-65ab989d7a03)

### Expected behavior

Einschalten, Installieren und so wie beschrieben, Nutzten

### Screenshots & Logfiles

![VIS2](https://github.com/ioBroker/ioBroker.vis-2/assets/96009604/87dd81f6-663a-45d7-a06b-fafec7c796f8)

### Adapter version

v2.0.16

### js-controller version

5.0.16

### Node version

v18.18.2

### Operating system

Pi

### Additional context

Bin noch ein kleiner Anfänger in der Linuxwelt. Kein Programmierer. Updates vom System mache ich strickt nach Anleitung. Man hangelt sich halt so durch. 
Wäre schön wenn es dazu eine Info / Fix gibt, würde es gern verwenden.
Browser wurden bereits Chrome, Mozilla und Opera angeschaut. Überall selbes Proglem

LG Patrik

**Comment by afuerhoff** [comment]
Hallo, bitte mit diesem Adapter aus dem Latest repository versuchen.
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/b1dfc32f-b673-45e0-952e-21f01d4b3413)

**Comment by Feuer-sturm** [comment]
@ps-neotrace vis-2-beta wird nicht weiter entwickelt. Dies war die erste Alpha Version von vis-2
Die aktuelle Entwicklung findet über den vis-2 Adapter statt, welchen @afuerhoff gepostet hat.
