### ISSUE TITLE
[bug]: Kopieren von Attribut Werten auf ein anderes Widget funktioniert nicht mehr

### ISSUE THREAD

**Issue by afuerhoff** [ioBroker/ioBroker.vis-2#168]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Wenn man auf den Kopierstift drückt, wurde sonst der Cursor verändert und man konnte Attributwerte auf ein anderes Widget übertragen.

### To Reproduce

keine zusätzliche Info

### Expected behavior

So wie vorher

### Screenshots & Logfiles

![image](https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/1aa7b057-afaf-4a4e-b4c3-facfbebe2daa)

### Adapter version

2.6.0

### js-controller version

5.0.12

### Node version

18.18.2

### Operating system

Debian 12 - Proxmox

### Additional context

Browser Chrome

**Comment by foxriver76** [comment]
Hat das in einer vorherigen vis-2 Version schon mal funktioniert? Oder meinst du im Vergleich zu vis-1. Nur damit ich weiß ob wir es letztens kaputt gemacht haben oder es noch gar nicht ging.

**Comment by afuerhoff** [comment]
Das ging in einer Vorgängerversion. Ich weiß jetzt nicht welche. Aber es könnte der Fix mit dem Binding-Editor gewesen sein.

**Comment by foxriver76** [comment]
Hm okay habe es eben mal probiert und bei mir scheint es zu funktionieren. Cursor wird zu einem Fadenkreuz und ich kann die css Eigenschaften erfolgreich auf das Widget übertragen.

**Comment by afuerhoff** [comment]
Ich habe es auch noch einmal mit einem neuen Projekt versucht. Da funktioniert es auch. In dem eigentlichen Projekt nicht. 
Ich teste nochmal etwas.

**Comment by afuerhoff** [comment]
Diese Meldungen kommen in dem Projekt wo es nicht funktioniert. In dem Testprojekt kommen die nicht.
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/020e2c79-fcbc-4db4-ae60-ef4beedbd6c4)

**Comment by afuerhoff** [comment]
**Ich habe auf der Seite wo es nicht ging, die Attribute Signalbilder komplett von allen Widgets entfernt.** Jetzt geht es wieder.

**Comment by afuerhoff** [comment]
Was mir noch aufgefallen ist, das die Basic HTML Widgets eine Eigenschaft "SRC" besitzen, die mit einem FLOT Link befüllt ist.
In der Oberfläche wird mir das Attribut aber nicht angezeigt. Ist da mal etwas entfernt worden? Durch den Import des alten Projektes vielleicht entstanden? Vielleicht bringt das ja auch Probleme. 
`[
  {
    "tpl": "tplHtml",
    "data": {
      "g_fixed": true,
      "g_css_font_text": true,
      "g_css_background": true,
      "g_css_shadow_padding": true,
      "g_css_border": false,
      "g_gestures": false,
      "refreshInterval": "0",
      "html": "CCU3",
      "class": "",
      "src": "http://192.168.2.2:8082/flot/index.html?l%5B0%5D%5Bid%5D=hm-rpc.1.JEQ0703647.1.BRIGHTNESS&l%5B0%5D%5Binstance%5D=history.0&l%5B0%5D%5Boffset%5D=0&l%5B0%5D%5Baggregate%5D=minmax&l%5B0%5D%5Bcolor%5D=%23CDDC39&l%5B0%5D%5Bmin%5D=0&l%5B0%5D%5Bmax%5D=255&l%5B0%5D%5Bthickness%5D=2&l%5B0%5D%5Bshadowsize%5D=0&l%5B0%5D%5Bunit%5D=Lux&l%5B0%5D%5Bname%5D=Helligkeit+T%C3%BCr&l%5B0%5D%5Byaxe%5D=rightColor&l%5B0%5D%5Bxaxe%5D=bottom&l%5B0%5D%5BignoreNull%5D=&l%5B0%5D%5BafterComma%5D=1&l%5B0%5D%5Bxticks%5D=5&l%5B0%5D%5Bpoints%5D=false&l%5B1%5D%5Bid%5D=hm-rpc.1.JEQ0703741.1.BRIGHTNESS&l%5B1%5D%5Binstance%5D=history.0&l%5B1%5D%5Boffset%5D=0&l%5B1%5D%5Baggregate%5D=minmax&l%5B1%5D%5Bcolor%5D=%2300FF00&l%5B1%5D%5Bmin%5D=0&l%5B1%5D%5Bmax%5D=255&l%5B1%5D%5Bthickness%5D=2&l%5B1%5D%5Bshadowsize%5D=0&l%5B1%5D%5Bunit%5D=Lux&l%5B1%5D%5Bname%5D=Helligkeit+Einfahrt&l%5B1%5D%5Bxaxe%5D=off&l%5B1%5D%5Byaxe%5D=off&l%5B1%5D%5BafterComma%5D=2&l%5B1%5D%5Bpoints%5D=false&l%5B1%5D%5BchartType%5D=line&l%5B2%5D%5Bid%5D=hm-rpc.1.JEQ0703647.1.MOTION&l%5B2%5D%5Binstance%5D=history.0&l%5B2%5D%5Boffset%5D=0&l%5B2%5D%5Baggregate%5D=minmax&l%5B2%5D%5Bcolor%5D=%23ff0000&l%5B2%5D%5Bmin%5D=0&l%5B2%5D%5Bmax%5D=10&l%5B2%5D%5Bthickness%5D=3&l%5B2%5D%5Bshadowsize%5D=3&l%5B2%5D%5Bname%5D=Bew.+T%C3%BCr&l%5B2%5D%5BchartType%5D=steps&l%5B2%5D%5BcommonYAxis%5D=3&l%5B2%5D%5BignoreNull%5D=false&l%5B2%5D%5BafterComma%5D=2&l%5B2%5D%5Byaxe%5D=off&l%5B2%5D%5Bxaxe%5D=off&l%5B2%5D%5Bpoints%5D=false&l%5B2%5D%5ByOffset%5D=4&l%5B3%5D%5Bid%5D=hm-rpc.1.JEQ0703741.1.MOTION&l%5B3%5D%5Binstance%5D=history.0&l%5B3%5D%5Boffset%5D=0&l%5B3%5D%5Baggregate%5D=onchange&l%5B3%5D%5Bcolor%5D=%230000ff&l%5B3%5D%5Bmin%5D=0&l%5B3%5D%5Bmax%5D=10&l%5B3%5D%5Bthickness%5D=3&l%5B3%5D%5Bshadowsize%5D=3&l%5B3%5D%5Bname%5D=Bew.+Einfahrt&l%5B3%5D%5BchartType%5D=steps&l%5B3%5D%5Bxaxe%5D=off&l%5B3%5D%5Byaxe%5D=off&l%5B3%5D%5Bpoints%5D=false&l%5B3%5D%5BcommonYAxis%5D=3&l%5B3%5D%5BignoreNull%5D=&l%5B3%5D%5BafterComma%5D=2&l%5B3%5D%5ByOffset%5D=2&timeType=relative&relativeEnd=now&range=1440&aggregateType=count&aggregateSpan=100&width=720&height=360&noBorder=noborder&window_bg=%23212121&bg=%23212121&x_labels_color=%23e0e0e0&y_labels_color=%23e0e0e0&border_color=%23808080&grid_color=%23606060&barColor=%23f0f0f0&barLabels=topover&barFontColor=%23f0f0f0&title=Bewegungsmelder&titlePos=top%3A35%3Bleft%3A65&titleColor=%23a0a0a0&titleSize=16&legend=sw&hoverDetail=true&useComma=false&zoom=false&noedit=true&animation=0&legColumns=2&legBgOpacity=1&legBg=rgba(255%2C255%2C255%2C0.5)&timeFormat=%25H%3A%25M+%25d.%25m",
      "name": "Überschrift",
      "comment": "",
      "bindings": []
    },
    "style": {
      "left": 15,
      "top": 2,
      "height": "auto",
      "width": "374px",
      "z-index": "10",
      "font-family": "",
      "font-size": "24px",
      "background": "",
      "margin-left": "",
      "text-align": "left",
      "padding-top": "",
      "padding": "",
      "color": "#d7cec1",
      "opacity": "",
      "font-variant": "normal",
      "font-weight": "",
      "text-shadow": "rgba(0, 0, 0, 0.9) 3px 3px 4px",
      "bindings": [],
      "cursor": "default"
    },
    "widgetSet": "basic",
    "_id": "i000001"
  }
]`

**Comment by afuerhoff** [comment]
Ich hab mal die ganzen src Attribute (wo Flot referenziert war) des Basic HTML Widgets aus dem Projekt entfernt. Ich habe das Gefühl, dass jetzt auch die Oberfläche performanter funktioniert.
Evtl. wäre ein Checkprogramm für Views sinnvoll, damit man solche Fehler besser erkennen kann.

**Comment by afuerhoff** [comment]
@foxriver76: Aus meiner Sicht kann dieser Issue geschlossen werden. Nach der Bereinigung im Projekt ist der Fehler nicht wieder aufgetreten. Es könnte an den Attributen für Signale gelegen haben. Vielleicht eine Altlast.
