### ISSUE TITLE
[enhancement]: Beim Selektieren mit der Maus und STRG Taste können Widgets nicht abgewählt werden

### ISSUE THREAD

**Issue by afuerhoff** [ioBroker/ioBroker.vis-2#178]
### No existing issues.

- [X] There is no existing issue for my request.

### Related problems

Beim Selektieren mit der Maus und der Taste STRG können Widgets nur ausgewählt werden.

### Description

Beim Selektieren mit der Maus und der Taste STRG sollten Widgets auch abgewählt werden können. 
Wie unter Windows üblich.

**Comment by foxriver76** [comment]
will be implemented in next version

**Comment by afuerhoff** [comment]
Mit 2.8.0 funktioniert es. Danke
