### ISSUE TITLE
[bug]: Seiten können nicht gewechselt werden -> Leere Seite

### ISSUE THREAD

**Issue by afuerhoff** [ioBroker/ioBroker.vis-2#179]
### No existing issues.

- [X] There is no existing issue for my problem

### Describe the bug

Beim Anzeigen des Seiten-Dialogs wird eine leere Seite angezeigt.
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/6bd75f49-5fee-4db9-81bb-305ba17c1943)

### To Reproduce

Beim Klicken auf den Button entsteht der Fehler

### Expected behavior

Seitendialog wird angezeigt

### Screenshots & Logfiles

![image](https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/1887f50a-9464-425b-bd99-52ff8cd14560)

### Adapter version

2.6.2

### js-controller version

5.0.12

### Node version

18.18.2

### Operating system

Debian 12 - Proxmox

### Additional context

Mit der neuen v2.6.2 aufgetreten

**Comment by foxriver76** [comment]
Bitte mit 2.6.3 neu testen
