### ISSUE TITLE
[bug]: Nach Klicken auf CSS Scripte kommt eine leere Seite

### ISSUE THREAD

**Issue by afuerhoff** [ioBroker/ioBroker.vis-2#181]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Nach dem Klicken auf CSS Scripte kommt die leere Seite und der Vis Editor kann nicht mehr geladen werden. Cache löschen bringt keine Verbesserung. Auf der Inkognito Seite kann Vis wieder geladen werden. Aber auch hier kommt die leere Seite.

### To Reproduce

Klicken auf CSS Scripte

### Expected behavior

Scriptbereich wird angezeigt

### Screenshots & Logfiles

![image](https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/9d41defa-9db6-4f8e-96a3-3070f2cc13e7)

### Adapter version

2.6.2

### js-controller version

5.0.12

### Node version

18.18.2

### Operating system

Debian 12 - Proxmox

**Comment by foxriver76** [comment]
Bitte mit 2.6.3 neu testen

**Comment by afuerhoff** [comment]
Funktioniert wieder mit 2.6.3. Danke
