### ISSUE TITLE
[bug]: Update auf 2.6.3 blockiert System

### ISSUE THREAD

**Issue by Horgul123** [ioBroker/ioBroker.vis-2#184]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Beim Versuch von 2.6.1 auf 2.6.3 zu updaten wird der Systemspeicher komplett ausgelastet und das System kommt zum Stillstand.
Mehrfach versucht.

### To Reproduce

Im Admin Adapter das Update auf 2.6.3 starten

### Expected behavior

Update läuft problemlos durch

### Screenshots & Logfiles

![2023-11-21_08-16-30](https://github.com/ioBroker/ioBroker.vis-2/assets/45976162/91863de5-ed1f-41ce-ad6d-fce96416be1e)

### Adapter version

2.6.3

### js-controller version

5.0.16

### Node version

18.18.2

### Operating system

Debian Bookworm

### Additional context

npm 9.8.1
Nach erneutem Restart des Systems lief das Update jetzt durch.
Das Problem trat bei anderen VIS2 Updates auch schon auf

**Comment by Feuer-sturm** [comment]
Ist ein js-controller issue: https://github.com/ioBroker/ioBroker.js-controller/issues/2538
