### ISSUE TITLE
[bug]: Runtime im neuen Fenster startet nicht mehr

### ISSUE THREAD

**Issue by afuerhoff** [ioBroker/ioBroker.vis-2#187]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Runtime startet nicht. Es ist nur das drehende ioBroker Symbol zu sehen.

### To Reproduce

Nach drücken auf Play startet die Runtime nicht. 

### Expected behavior

Runtime wird im neuen Fenster korrekt angezeigt.

### Screenshots & Logfiles

![image](https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/871c536f-ce22-4b57-b308-927ace5ef326)

![image](https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/1a05f519-6851-4c50-a59e-20d631d1c1c6)

### Adapter version

2.6.4

### js-controller version

5.0.12

### Node version

18.18.2

### Operating system

Debian 12 - Proxmox

### Additional context
Im Inkognitofenster selbes Verhalten

**Comment by DerTom1978** [comment]
same Problem

Adapter version
2.6.4

js-controller version
5.0.12

Node version
18.18.2

Operating system
Windows 11

testet Browser:
Chrome, Edge

**Comment by hombach** [comment]
same, roll back to 2.6.1 fixed my issue

**Comment by foxriver76** [comment]
issue still present with 2.7.0?

**Comment by Papjurek** [comment]
Mein Adapter zeigt mir kein Update an. 
Aktuelleste ist die 2.6.4, aber mit dem bekannten Problem das die Runtime nicht Startet.

**Comment by afuerhoff** [comment]
Du kannst über die Katze im Expertmodus per NPM installieren. Über den normalen Weg dauert es länger

**Comment by hombach** [comment]
> With 2.7.0 runtime is starting correctly. Many thanks

Same here, everything fixed again with 2.7.0

**Comment by Papjurek** [comment]
Hat geklappt und geholfen, vielen Dank.
Habe jetzt ein anderes Problem, und zwar speichert vis-2 keine änderungen mehr.
Ich kann Widget verschieben oder löschen, im Editor auch alles weg. In der Runtime jedoch nicht. Egal ob ich was lösche oder verschiebe. Das Speichersymbol oben rechts leuchtet einmal auf, dann verschwindet er wieder und dann kommt es wieder und leuchtet dauerhaft.
Hat das Problem sonst noch jemand seit dem update?

**Comment by patricknitsch** [comment]
Das Problem habe ich auch. Nach Aktualisierung der Seite sind die Änderungen wieder weg.

**Comment by Feuer-sturm** [comment]
@Papjurek @patricknitsch  bitte legt für euer Thema ein  neues issue an.
