### ISSUE TITLE
[bug]: Fehlermeldungen im Protokoll nach Nutzung von Gruppierungen in VIS-2 mit inventwo Widgets

### ISSUE THREAD

**Issue by patricknitsch** [ioBroker/ioBroker.vis-2#188]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Hallo,

ich nutze in VIS-2 inventwo Widgets. Die Übernahme des Projektes aus VIS-1 ging nur, nachdem ich alle Gruppierungen aufgehoben habe. Davor kam ein weißer Bildschirm. Nun wollte ich meine Navigationsliste wieder gruppieren und als mulit-view auf mehreren Seiten darstellen. Nach Aufruf einer Seite kamen folgende Fehlermeldungen.

siehe Auszug Log-File.

Die Darstellung der Leiste auf den anderen Seiten funktioniert nicht. Der Aufruf der Navigation funktioniert richtig. 

### To Reproduce

1. Hauptseite
2. Erstellung Gruppierung
3. Auswahl multi-view und die entsprechenden Seiten
4. Öffne Runtime
5. Wähle Seite über Navigation aus

### Expected behavior

Benutzung der Gruppierung ohne Fehler
Unterstützung, falls eine Fehlbedienung meinerseits vorliegt

### Screenshots & Logfiles

Auszug-Log-File:
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/114565561/949d5bc0-9a2c-4fb0-925d-0a76756b03bb)

Home-Seite:
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/114565561/3f996e02-63cb-429b-8ba0-ea27bba535bf)

Wetter-Seite:
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/114565561/2c46fa74-f994-4a17-ad97-0902aa2d6dfb)

### Adapter version

2.6.1

### js-controller version

5.0.16

### Node version

18.17.1

### Operating system

Debian Bookworm

**Comment by patricknitsch** [comment]
Update:

Nach Update auf 2.7.0 erscheinen keine Fehler mehr. Nach Nutzung des multi view bleibt die aufgerufene Seite einfach weiß.
Folgendes zeigt die Ausgabe des Browsers:

![image](https://github.com/ioBroker/ioBroker.vis-2/assets/114565561/fc9787d6-c77b-4283-9b4e-23ca669db357)

**Comment by Feuer-sturm** [comment]
@patricknitsch Der Inventwo Widgets Adapter muss nach Aussage vom Entwickler (https://forum.iobroker.net/topic/71786/vis2-ab-morgen-im-stable/128?_=1705832236683) komplett neu für vis-2 entwickelt werden.

Wenn es hier sich rein um ein Problem mit Inventwo Widgets handelt, schlage ich vor das issue zu schließen.

**Comment by patricknitsch** [comment]
Gut zu wissen,

dann werde ich abwarten, bis die Neuentwicklung auf einem neuen Stand ist. Das hat dann erstmal nichts mit VIS-2 zu tun.

Danke für die Information.
