### ISSUE TITLE
[bug]: Seiten werden überlagert zusammen mit der Navigation angezeigt

### ISSUE THREAD

**Issue by afuerhoff** [ioBroker/ioBroker.vis-2#198]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Es wird nicht die ausgewählte Seite angezeigt, sondern die Überlagerung mit der Navigation.

### To Reproduce

Seite auswählen

### Expected behavior

Nur die ausgewählte Seite wird angezeigt

### Screenshots & Logfiles

![image](https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/46b4d322-c10e-4ce0-89fe-e3c9fd1746d9)

### Adapter version

2.8.0

### js-controller version

5.0.12

### Node version

18.18.2

### Operating system

Debian 12 - Proxmox

### Additional context

Chrome

**Comment by afuerhoff** [comment]
Erweiterung: Es betrifft nicht nur den Editor sondern auch die Runtime. Hier funktioniert die Navigation nicht mehr

**Comment by Feuer-sturm** [comment]
@afuerhoff Kann ich bei mir mit der Version 2.8.0 nicht bestägiten. Bei mir kann ich die Seiten im Editor und in der Runtim korrekt durchschalten ohne das etwas überlagert wird.

**Comment by afuerhoff** [comment]
Mit 2.7.0 alles wieder ok. 
2.8.0 funktioniert bei mir nicht.

**Comment by thps1990** [comment]
Ich kann den Fehler mit 2.8.0 genau so bestätigen. Die erste Seite funktioniert. die restlichen Seiten werden entweder gar nicht oder sehr weit unten auf dem Screen angezeigt.

**Comment by Feuer-sturm** [comment]
@afuerhoff @thps1990 Gibt es Fehler in der Konsole (F12)? Wenn ja bitte mal hier posten.

**Comment by afuerhoff** [comment]
@Feuer-sturm: Bei mir gibt es keinen Fehler in der Konsole

**Comment by afuerhoff** [comment]
Ich habe jetzt alle Haken im Projekt bei "immer rendern" entfernt. Danach gibt es die Überlagerung nicht mehr.
Siehe hierzu auch https://github.com/ioBroker/ioBroker.vis-2/issues/192
