### ISSUE TITLE
[bug]: Mit Mausklick auf Seite können selektierte Widgets nicht abgewählt werden.

### ISSUE THREAD

**Issue by afuerhoff** [ioBroker/ioBroker.vis-2#199]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Selektierte Widgets können mit einem Mausklick nicht wieder abgewählt werden. Dies funktioniert nur noch mit der STRG Taste. 
Oder man selektiert ein anderes Widget.

### To Reproduce

Mehrere Widgets selektieren und danach in einen freien Bereich auf der ausgewählten Seite im Editor klicken.  

### Expected behavior

Alle selektierten Widgets werden abgewählt

### Screenshots & Logfiles

https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/305c7235-97b0-404d-a995-8c07932256a3

### Adapter version

2.8.0

### js-controller version

5.0.12

### Node version

18.18.2

### Operating system

Debian 12 - Proxmox

### Additional context

Chrome

**Comment by iAgrippa** [comment]
seltsam, hier geht das:
 
![sel](https://github.com/ioBroker/ioBroker.vis-2/assets/151877956/780e736e-3781-4a8f-82ea-b3093666e05a)

**Comment by MK-66** [comment]
@afuerhoff 
Also bei mir geht das Abwählen auch ganz normal, wenn ich in einen freien Bereich klicke (V2.8.0).

**Comment by afuerhoff** [comment]
Ich glaube inzwischen, dass in meinem Projekt irgendeine Definition zerschossen ist und dadurch seltsame Zustände entstehen. Kann aber noch nicht identifizieren, was es sein könnte. Bin noch am Suchen.

**Comment by afuerhoff** [comment]
Ich hab jetzt nochmal auf 2.7.0 zurückgesetzt. Jetzt kann ich auch wieder abwählen. Also es muss mit der 2.8.0 zusammenhängen.

**Comment by afuerhoff** [comment]
Ich habe alle Haken im Projekt bei "immer rendern" entfernt. Danach funktioniert auch das abwählen mit der Maus. 
siehe auch Issue https://github.com/ioBroker/ioBroker.vis-2/issues/192 hierzu.

**Comment by foxriver76** [comment]
Mit aktueller Version noch reproduzierbar?

**Comment by afuerhoff** [comment]
Siehe Post vor Deinem. Alles ok jetzt. Danke
