### ISSUE TITLE
css-Übertragung von vis-2-beta auf vis-2 fehlerhaft

### ISSUE THREAD

**Issue by AndrewSteel** [ioBroker/ioBroker.vis-2#2]
**Describe the bug**  
Bei der automatischen Übertragung der Daten von vis-2-beta auf vis-2 wurden bei mir die css-Einträge nicht übernommen.

**To Reproduce**  
* Installation von vis-2
* Start von vis-2 Editor
* Projekte werden übernommen
* css-Daten der Projekte fehlen
* 
**Expected behavior**  
Auch die css-Daten sollten übertragen werden.

**Versions:**  
- Adapter version: vis-2 V 2.2.2
- JS-Controller version: 4.0.24
- Node version: v16.19.1
- Operating system: aarch64 GNU/Linux 6.1.21-v8+

**Comment by foxriver76** [comment]
Geht es um eine automatische ÜBernahme oder war das ein manueller Import/Export?

**Comment by AndrewSteel** [comment]
Das kann ich Dir nicht mehr genau sagen, aber ich meine, dass bei der Installation die Projekte automatisch übernommen wurden und dabei die Daten im CSS Reiter verloren gingen. Ich kann es auch nicht mehr reproduzieren, da bei mir die alte VIS nicht mehr läuft.

**Comment by foxriver76** [comment]
I think the problem should be fixed now. There was a problem that on upload css was deleted in older versions.
