### ISSUE TITLE
[bug]: reactivity problem mit v2.8.0

### ISSUE THREAD

**Issue by Steiger04** [ioBroker/ioBroker.vis-2#202]
### No existing issues.

- [x] There is no existing issue for my problem.

### Describe the bug

Nach Version v2.6.1 mit Einführung von Redux verhält sich vis-2 nach meinem Verständnis bei der Reactivity nicht immer "richtig".
Beispiel: Du ziehst im Editor ein Widget (z.B. das Batterie-Widget) auf die View und hast gleichzeitig die Runtime geöffnet. Bis Version v2.6.1 hat sich die Runtime dann sofort selbst aktualisiert, was aus meiner Sicht auch so seien muss. Gleiches gilt für Änderungen des Widgets (z.B. Änderung der Größe der Batterie). Auch hier erfolgt keine Aktualisierung in der Runtime. Erst mit expliziter Aktualisierung des Browserfensters (z.B. mit F5), erfolgt auch die Übernahme der Werte in der Runtime. 
Einen ähnlichen Effekt habe ich bei einer Custom-Component:

![image](https://github.com/ioBroker/ioBroker.vis-2/assets/17086944/2173392f-f6a8-4788-a524-9a9ea8900c1a)

Rufe ich onDataChange in `<VisRadarMapSelect>` auf und ändere dort den Wert data[fieldName], erfolgt kein Rerendering von `<VisRadarMapSelect>` im Editor, was eigentlich erfolgen müsste. 

Bis v2.6.1 hat aus meiner Sicht aber alles "richtig" funktioniert, ein Rerendering hat also stattgefunden.

### To Reproduce

---

### Expected behavior

---

### Screenshots & Logfiles

---

### Adapter version

v2.8.0

### js-controller version

v5.0.16

### Node version

v18.18.2

### Operating system

Linux / Docker Container

**Comment by foxriver76** [comment]
Ich vermute da fehlt uns noch ein subscribe danke ich schaue mal rein

**Comment by foxriver76** [comment]
Bitte mal mit 2.9.0 rechecken, habe es nicht explizit getestet.

**Comment by Steiger04** [comment]
@foxriver76 Habe gerade mit der v2.9.1 getestet. Die Sync-Probleme in der Runtime sind weg (perfekt). Der Custom-Widget Fehler ist noch da, Mit v2.6.1 funktioniert das noch richtig.

**Comment by foxriver76** [comment]
Hast du evtl. ein Link zu dem Widget-Code auf GitHub?

**Comment by Steiger04** [comment]
@foxriver76 Habe gerade mit der v2.9.1 getestet. Die Sync-Probleme in der Runtime sind weg (perfekt). Der Custom-Widget Fehler ist noch da, Mit v2.6.1 funktioniert das noch richtig.

**Comment by Steiger04** [comment]
@foxriver76 Hier der [Link](Link: [](url))

**Comment by Steiger04** [comment]
@foxriver76 Zum besseren Verständnis vielleicht noch einmal folgender Screenshot:
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/17086944/8d7dc9df-a443-45a4-aa89-7d88b17be279)

Das Feld "Route oder Gebiet" bleibt bei der ersten Auswahl immer Leer, das Widget aktualisiert sich aber sofort (mit v2.9.1 jetzt auch in der Runtime). Erst wenn ich den Editor aktualisiere, oder aber neben das Widget klicke und es danach wieder anwähle wird in dem Feld "Route oder Gebiet" der richtige Eintrag auf (in diesem Fall: "Gebiet um Köln") aktualisiert.

**Comment by foxriver76** [comment]
Kann man das auch ohne Token nachstellen? :D

**Comment by Steiger04** [comment]
@foxriver76 Du brauchst für den Adapter einen MAPBOX-Token, sonnst kannst Du keine Routen oder Gebiete anlegen. Der Fehler ist in ähnlicher Weise schon [hier](https://github.com/ioBroker/ioBroker.vis-2/issues/210) aufgetreten. Vielleicht hilft das ja noch. 
Eigentlich müsste der Fehler aber immer dann auftreten, wenn Du an eine beliebige Custom-Component einen data-Wert als Property übergibst, diesen in der Component anzeigst und mit  onDataChange(...) aktualisierst (z.B. wie bei mir in einem select).

**Comment by Steiger04** [comment]
Das sieht doch gut aus. Hast Du Lust eine v2.9.2 zu spendieren  :-) ?

**Comment by foxriver76** [comment]
ist released

**Comment by Steiger04** [comment]
@foxriver76 Mit v2.9.2 funktioniert jetzt alles perfekt. Besten Dank für das super schnelle Bugfixing.
