### ISSUE TITLE
[bug]: Attribute "links" und "oben" einer Gruppe sind falsch

### ISSUE THREAD

**Issue by afuerhoff** [ioBroker/ioBroker.vis-2#211]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Beim Verschieben einer Gruppe ändern sich die Attribute **links** und **oben** nicht.

### To Reproduce

Eine Gruppe bilden. Danach werden die Attribute mit negativen Werten angezeigt.

### Expected behavior

Die Attribute repräsentieren die Position der Gruppe.

### Screenshots & Logfiles

![image](https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/23bb5f1b-66af-42db-972c-3a8f416cd433)

### Adapter version

2.9.0

### js-controller version

5.0.16

### Node version

18.18.2

### Operating system

Debian 12 - Proxmox

**Comment by foxriver76** [comment]
Ja ich denke hier sollte die Gruppe selektiert sein, nach dem bilden der Gruppe.

**Comment by afuerhoff** [comment]
Gruppe ist jetzt auch selektiert und die entsprechenden Werte werden angezeigt. Danke
