### ISSUE TITLE
[bug]: Gruppe kann nicht von einer Seite auf die andere kopiert werden

### ISSUE THREAD

**Issue by afuerhoff** [ioBroker/ioBroker.vis-2#212]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Eine Gruppe kann per copy/paste nur innerhalb einer Seite  kopiert werden. Von einer Seite auf eine andere funktioniert nicht.
Auch der Widget Export und dann Import auf der neuen Seite funktioniert ebenfalls nicht. Die Gruppe ist nicht vollständig.

### To Reproduce

Gruppe kopieren. Seite wechseln und einfügen oder Widget exportieren und dann wieder importieren.

### Expected behavior

Kopieren funktioniert auch von einer Seite auf die andere oder der Import einer Gruppe.

### Screenshots & Logfiles
Fehler beim copy/paste
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/97d023fb-343d-4352-a7ca-a2e84b7b0617)
Fehler beim Import:
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/76e32ba7-344d-4d46-a339-a137940eba00)

### Adapter version

2.9.0

### js-controller version

5.0.16

### Node version

18.18.2

### Operating system

Debian 12 - Proxmox

**Comment by afuerhoff** [comment]
Copy / Paste von Seite zu Seite funktioniert mit 2.9.1
@foxriver76: Soll ich für den Export/Import ein neues Ticket aufmachen?

**Comment by Feuer-sturm** [comment]
@afuerhoff für das import Thema gibt es das issue #14

**Comment by foxriver76** [comment]
>  Auch der Widget Export und dann Import auf der neuen Seite funktioniert ebenfalls nicht. Die Gruppe ist nicht vollständig.

oh das habe ich komplett übersehen.

Ich schreibe mal das #14 auf meine Agenda

**Comment by afuerhoff** [comment]
@Feuer-sturm: Danke für die Info. Hatte ich nicht gesehen.
@foxriver76: Schon mal danke im Voraus

**Comment by afuerhoff** [comment]
@Feuer-sturm, @foxriver76: Ich habe mir #14 eben angesehen. da geht es um den Import von Seiten. Ich habe oben den Import von Widgets beschrieben, der bei Gruppen nicht funktioniert.

**Comment by foxriver76** [comment]
Ich vermute dass der Export das Problem ist aber schaue es mir demnächst an.

**Comment by foxriver76** [comment]
closed in https://github.com/ioBroker/ioBroker.vis-2/commit/dbcdd1be7d71670e825d0f53c51f808906958b30

**Comment by afuerhoff** [comment]
Der Export funktioniert jetzt auch. Danke
