### ISSUE TITLE
Scrolling dont work in Runtime

### ISSUE THREAD

**Issue by dos1973** [ioBroker/ioBroker.vis-2#22]
**Describe the bug**  
i can't scroll to the bottom of the site in runtime.

**To Reproduce**  
1. create display size 1024x1365px
2. add a Basic border, 100px x 1365px (left 0px, top:0px) add color
3. add a second Basic border 100px x 100px (left 50px, top:1250px)  other color 
4. editor scrolling is possible. 
5. scrolling in runtime don't work. 

error happen on MacOsx 12.3 with safari 
and chrome (Version 107.0.5304.121 )

**Expected behavior**  
scrolling enabled

**Screenshots & Logfiles**  
see project export

**Versions:**  
Adapter version: vis2 v2.0.7

[2022-11-27-vis2-beta.zip](https://github.com/ioBroker/ioBroker.vis/files/10097258/2022-11-27-vis2-beta.zip)

**Comment by kailausberg** [comment]
Scrolling only works, if in SETTINGS / BODY OVERFLOW > SCROLL is activated.  This seems to be not the default value...

![grafik](https://github.com/ioBroker/ioBroker.vis-2/assets/60115355/cae22927-b163-407d-8c4e-6e39e9488010)


[https://forum.iobroker.net/topic/67676/vis-2-0-neuer-adapter-als-beta/150?_=1693742939972](url)

**Comment by foxriver76** [comment]
yes it mentions standard is auto but it applied hidden if not given, will look into it
