### ISSUE TITLE
[bug]: Problem mit ignoreInVersions

### ISSUE THREAD

**Issue by Steiger04** [ioBroker/ioBroker.vis-2#226]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Für meinen Adapter habe ich separate vis-2 Widgets entwickelt. Die "alten" vis-Widgets sollen bei Nutzung von vis-2 nicht verfügbar sein, da sie nur mit vis funktionieren. Dazu gibt es ja sei der v5.0.17 des js-controller und der v2.4.0 von vis-2 die Möglichkeit den ignoreInVersions-Key zu verwenden. Das habe ich in der io-package.js meines Adapters, also da wo die vis-Widgets auch abgelegt sind (im Adapterordner widgets), gemacht.

![grafik](https://github.com/ioBroker/ioBroker.vis-2/assets/17086944/93aa9678-2210-4ecd-b0e4-5ba67d4639a9)

Das hat aber leider keinen Effekt in vis-2, da die vis-Widgets immer noch angeboten werden.
Frage dazu: ist das noch ein Bug, oder nutze ich den Key ggf. falsch?

### To Reproduce

s.o.

### Expected behavior

 s.o.

### Screenshots & Logfiles

 s.o.

### Adapter version

v2.9.2

### js-controller version

v5.0.17

### Node version

v18

### Operating system

Windows

**Comment by Steiger04** [comment]
> Um welchen Adapter handelt es sich?

Um den radar-trap Adapter. Du findest die angepasste io-package.js aber noch nicht auf GitHub. Ich habe erstmal lokal getestet, indem ich im Objektbaum system.repositories entsprechend angepasst habe (ohne common) und dann meinen Adapter und  vis-2 neu installiert habe.

**Comment by Steiger04** [comment]
@foxriver76 Ich bin gerade etwas lost, weil ich einfach nicht raffe, woher sich vis-2 das "ignoreInVersions" Attribut zieht. Ich möchte ja, bevor es eine neue Version auf GitHub gibt lokal testen. Dazu habe ich das "ingnoreInVersions"-Attrribut an zwei Stellen ergänzt.
1) in der io-package.js des radar-trap-Adapters und danach eine neue Instanz angelegt. -> Hat nicht funktioniert.
2) im Objektbaum unter system.repositories beim Eintrag radar-trap ergänzt und danach eine neue Instanz angelegt.-> Hat nicht funktioniert.

Danach wieder neue radar-trap Instanz angelegt -> Hat nicht funktioniert und jeweil immer die vis-2 Instanz neu gestartet, obwohl vis-2 sich auch automatisch aktualisiert.

Wenn ich mir den Code anschaue: 

![image](https://github.com/ioBroker/ioBroker.vis-2/assets/17086944/e337674f-fa0a-445a-80f9-35ffce898de8)

geht die Abfrage über getObjectViewSystem. Habe ich dann mal für die Instanz system.adapter.radar-trap.0 mit dem Code:

![image](https://github.com/ioBroker/ioBroker.vis-2/assets/17086944/5988d57c-805d-49bc-aecf-91b24471843a)

gemacht. Ergebnis ist:

![image](https://github.com/ioBroker/ioBroker.vis-2/assets/17086944/e14dd564-b7a4-45af-bf22-f7aa89f73a69)

Also kein:

![image](https://github.com/ioBroker/ioBroker.vis-2/assets/17086944/493e8f31-9a52-4e18-b133-037759cf03f1)

im common-Object.

Wird vielleicht irgendwo noch was gecacht, oder hast Du eine Idee wo der Denkfehler bei mir ist?

**Comment by foxriver76** [comment]
Io pack muss nach der Änderung auf jeden Fall geuploaded werden. Sonst wird sich das nicht im Objekt widerspiegeln. Also `iob u deinAdapter`

**Comment by Steiger04** [comment]
Das wars, danke! 
Zum besseren Verständnis: durch den upload wird ignoreInVersions in die Object-DB (bei mir objects.jsonl) geschrieben und mit getObjectViewSystem über die ws-Implementierung abgefragt, richtig? D.h. in system.repositories brauche ich gar nichts zu ändern, um zu testen. Ist das so ungefähr richtig verstanden? Besten Dank.
