### ISSUE TITLE
[bug]: Navigationsseiten werden nach Update auf 2.9.3 nur noch klein angezeigt

### ISSUE THREAD

**Issue by afuerhoff** [ioBroker/ioBroker.vis-2#230]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Nach Update auf 2.9.3 werden die Navigationsseiten nicht korrekt angezeigt.
Das Menü ist folgendermaßen aufgebaut: Auf der Navigationsseite ist ein View im Widget, dass auf 100% Breite und 100% Höhe eingestellt ist. Die Responsive-Einstellungen wie unten im Bild. Vor dem Update wurde 

### To Reproduce

Update auf 2.9.3 durchführen und Navigationsseiten aufrufen

### Expected behavior

Seiten werden in korrekter Breite angezeigt.

### Screenshots & Logfiles

v2.9.3:
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/2be194ba-9380-4c55-adbd-2d6dbfa0c260)
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/0611bd33-51cf-46ca-9722-a12b3dcec216)
v2.9.2:
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/d963bd06-04e8-4362-ba5d-edeaf1c79f09)

### Adapter version

2.9.3

### js-controller version

5.0.16

### Node version

18.18.2

### Operating system

Debian 12 - Proxmox

**Comment by MK-66** [comment]
Ich hänge mich mal hier dran: 
Offenbar werden in V2.9.3 bei diversen Widgets die Höhe und Breite der Widgets falsch dargestellt, wenn diese als Prozentwert in den Feldern eingetragen sind. Es werden die Prozentwerte anscheinend immer als px interpretiert, so zumindest mein Eindruck.

Bemerkt habe ich diesen Fehler bei den Wigdets "Basic - View in widget, Basic - HTML, Gestylt - Zur URL springen". Weitere Widgets habe ich dahingehend dann nicht mehr getestet.

Wenn man in den Feldern statt 100% calc(100%) einträgt, werden Breite und Höhe wieder korrekt dargestellt, dies kann man aber nur als temporären workaround sehen.

Bei der V2.9.3 wird bei mir darüber hinaus auch die CSS Angabe float: left nicht mehr korrekt interpretiert, dies aber nur am Rande.

**Comment by hombach** [comment]
Hänge mich auch an, in meinem Fall sind alle Widgets ohne Ausnahme "defekt". Ja, ich würde auch sehr sicher davon ausgehen dass die % als px interpretiert werden. calc(100%) als Workaround funktioniert.

**Comment by foxriver76** [comment]
their were some changes regarding size calculations in https://github.com/ioBroker/ioBroker.vis-2/commit/30fcaacff6b645872b7c1a6e9cefc4b3ee7d439d

Need to look into it.

**Comment by afuerhoff** [comment]
Mit 2.9.4 alles wieder ok. Danke
