### ISSUE TITLE
[bug]: V 2.9.3 Widgetbreite in Prozent funktioniert nicht mehr

### ISSUE THREAD

**Issue by ammawel** [ioBroker/ioBroker.vis-2#232]
Die Angabe der Widgetbreite in Prozent funktioniert nicht mehr, vermutlich wird die Prozentzahl als Anzahl Pixel interpretiert. Bis 2.9.2 einschließlich war die Auswertung richtig.

**Comment by foxriver76** [comment]
duplicate of https://github.com/ioBroker/ioBroker.vis-2/issues/230 please use 2.9.4 and please don't try your best to evade the issue template, because it seems like you have not searched existing issues ;-)
