### ISSUE TITLE
Unknown Widgettype after update

### ISSUE THREAD

**Issue by FlexerJR** [ioBroker/ioBroker.vis-2#235]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

After Updating to version Vis2 2.9.4 the widget which worked before the update has now unkown type. See Screeshot

![photo_2023-12-04_23-03-16](https://github.com/ioBroker/ioBroker.vis-2/assets/40354380/5ee006ac-e923-48bf-9a9e-d3839efc69bb)

Did also update to the Web Server version 6.2.1 at the same time. I guess it is more a vis2 issue

### To Reproduce

Well did an update. Downgrade to previous version did not solve the problem 

### Expected behavior

Well 

### Screenshots & Logfiles

![photo_2023-12-04_23-03-16](https://github.com/ioBroker/ioBroker.vis-2/assets/40354380/3b802877-2b8a-4fd5-a5af-8629f3ba0c15)

### Adapter version

2.9.4

### js-controller version

5.0.17

### Node version

v18.16.1

### Operating system

Ubuntu

**Comment by foxriver76** [comment]
Please delete cache for the page. Or validate easily with a private tab, it is most likely a caching issue.

**Comment by FlexerJR** [comment]
![IMG_8201](https://github.com/ioBroker/ioBroker.vis-2/assets/40354380/9729a58b-49cb-4bf8-b19b-c32c235be1b0)

Deleting Cache doesn‘t help but i realised that ther is an other error message. 

File widgets.html not found: §}

You can see it in the lower left corner

**Comment by foxriver76** [comment]
Same message in a private browser tab?

**Comment by FlexerJR** [comment]
Habe es hinbekommen. Vis 2 läuft wieder. Issue kann geschlossen werden. Fehler lag an mir. Sorry

**Comment by gaggerler** [comment]
hi, woran lag es denn? habe das gleiche problem
