### ISSUE TITLE
[bug]: Signalbilder - Nur das Erste [0] Signalbild funktioniert - die anderen nicht.

### ISSUE THREAD

**Issue by eberproducts** [ioBroker/ioBroker.vis-2#237]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Es funktionier NUR das erste Signalbild.
Ich habe alle drei Felder belegt. Die Bedingungen für die Anzeige der Signalbilder funktionieren nur beim ersten Signlbild [0] - aber die Signalbilder 2-3 werden nicht angezeigt. 

### To Reproduce

Fehler ist jederzeit reproduzierbar durch die Eingabe der Bedingungen für die Anzeige der Signalbilder - diese werden nicht angezeigt.  

### Expected behavior

Die Signalbilder sollten ALLE 3 angezeiugt werden, und nicht nur das Erste Signalbild.

### Screenshots & Logfiles

N/A

### Adapter version

2.9.4 und früher

### js-controller version

5.0.17

### Node version

18.19.0

### Operating system

Raspberry OS Debian (Kernal 6.1.21-v8+ #1642)

**Comment by foxriver76** [comment]
Kann ich nicht nachstellen, kannst du ein betroffenes Widget exportieren?

**Comment by foxriver76** [comment]
> Kann ich nicht nachstellen, kannst du ein betroffenes Widget exportieren?

@eberproducts

**Comment by eberproducts** [comment]
Ups - da kam wohl die Antwort per Mail an hier nicht an... - hier der Export des Widgets:
Hier der Quelltext vom Widget.

[
  {
    "tpl": "tplImage",
    "data": {
      "bindings": [],
      "signals-count": "2",
      "undefined": null,
      "signals-oid-0": "ical.0.events.0.today.Altpapier",
      "signals-cond-0": "==",
      "signals-val-0": true,
      "signals-icon-0": "_PRJ_NAME/img/abfall-blau.png",
      "signals-smallIcon-0": null,
      "signals-color-0": null,
      "signals-icon-size-0": 60,
      "signals-icon-style-0": null,
      "signals-text-0": null,
      "signals-text-style-0": null,
      "signals-text-class-0": null,
      "signals-blink-0": null,
      "signals-horz-0": null,
      "signals-vert-0": null,
      "signals-hide-edit-0": null,
      "g_signals": true,
      "signals-oid-1": "ical.0.events.1.Altpapier",
      "signals-icon-1": "_PRJ_NAME/img/abfall-blau.png",
      "signals-icon-size-1": 60,
      "signals-blink-1": true
    },
    "style": {
      "bindings": [],
      "left": "630",
      "top": "340",
      "width": "60",
      "height": "60",
      "z-index": 4
    },
    "widgetSet": "basic",
    "_id": "i000001"
  }
]

Scheint so, als ob hier NUR alle Parameter für das -0 Bild erstellt werden - Die Parameter für -1 Bild und -2 Bild fehlen / sind unvollständig... Obwohl ich alle Werte in der Eingabemaske ausgefüllt habe.

**Comment by foxriver76** [comment]
Ja beim hinzufügen eines Signals wird zwar `==` visuell vorausgewählt sowie `true` aber nicht gespeichert, wenn du das neu tippst kannst du es direkt fixen, ansonsten schaue ich mal das wir das in Zukunft direkt hinzufügen bzw als Fallback nutzen.

**Comment by eberproducts** [comment]
Aktuell habe ich mit "Copy-Paste" einfach die -0 Parameter als -1 und -2 Paramter hinzugefügt und das Widget so wieder importiert. dadurch funktioniert es jetzt bei mir, aber das ist ein "Workaround" - Wäre gut, wenn Du das gefixt bekommst.

**Comment by foxriver76** [comment]
wird in nächster version behoben sein https://github.com/ioBroker/ioBroker.vis-2/pull/302
