### ISSUE TITLE
[bug]: Basic Bulb on/off reagiert nicht korrekt auf Mausklick

### ISSUE THREAD

**Issue by afuerhoff** [ioBroker/ioBroker.vis-2#243]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Das WIdget reagiert nicht korrekt auf Mausklick. Der Aktor lässt sich entweder nicht einschalten oder ausschalten.

### To Reproduce

Wenn man unter min und max gar nichts einträgt kann man per Mausklick ausschalten. Trägt man true und false ein kann man einschalten.

### Expected behavior

Bei jedem Mausklick wird an oder ausgeschaltet

### Screenshots & Logfiles

![image](https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/c25b55a7-d21a-4a0e-bc31-8e088931393a)

### Adapter version

2.9.5

### js-controller version

5.0.16

### Node version

18.18.2

### Operating system

Debian 12 - Proxmox

**Comment by foxriver76** [comment]
It seems like once someone has entered something in `min/max` and deletes it, in `vis2` it remains a empty string in `vis1` it was `undefined` then. We need to consider this in the widget code.

**Comment by afuerhoff** [comment]
Funktioniert wieder. Danke
