### ISSUE TITLE
[bug]: javascript function in Html widget does not find

### ISSUE THREAD

**Issue by gokturk413** [ioBroker/ioBroker.vis-2#248]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

i want to create function inside Html widget and connect function name button onclick event.But the console is written "function is not defined"

### To Reproduce

1

### Expected behavior

I want to create functon and use it in the HTML Widget

### Screenshots & Logfiles

![Screenshot 2023-12-12 094016](https://github.com/ioBroker/ioBroker.vis-2/assets/38206629/833d9460-6bda-414c-bca3-4ae466653d64)
![Screenshot 2023-12-12 094057](https://github.com/ioBroker/ioBroker.vis-2/assets/38206629/b1f0d4cd-f733-4ff6-9c65-ea733d6ac314)
![Screenshot 2023-12-12 094549](https://github.com/ioBroker/ioBroker.vis-2/assets/38206629/421b55c8-79d4-48be-92e0-381ceba0563b)

### Adapter version

v2.9.5

### js-controller version

5.0.16

### Node version

18.19.0

### Operating system

windows11 23h2

**Comment by foxriver76** [comment]
The references are currently only available inside the same script tag. 

I think currently the only possibility is to define them globally or for short stuff inline 

![grafik](https://github.com/ioBroker/ioBroker.vis-2/assets/25484431/d5bc6e19-c230-434f-b847-4d5efd73a9d2)
