### ISSUE TITLE
[bug]: Timeout during Project import. >200MB Import of Vis1 project

### ISSUE THREAD

**Issue by FlexerJR** [ioBroker/ioBroker.vis-2#254]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Hallo und guten Tag. Ich habe ein Vis1 Projekt, dass ca 200mb groß ist. Wenn ich das versuche in Vis2 zu importieren bekomme ich die Meldung 

Cannot upload project timeout.

Gibt es keine Möglichkeit das Projekt zu importieren?

Viele Grüße

### To Reproduce

Import of project

### Expected behavior

Sucessful import

### Screenshots & Logfiles

![image](https://github.com/ioBroker/ioBroker.vis-2/assets/40354380/08cef184-4811-49b6-84bb-7d2e2c97f689)

### Adapter version

2.9.6

### js-controller version

5.0.17

### Node version

18.17.1

### Operating system

Ubuntu

**Comment by foxriver76** [comment]
Can you send me the project somewhere so I can test it?

**Comment by foxriver76** [comment]
The websocket server had a default size limit of 100 MB it is now increased with `iobroker.ws@2.5.10` and `iobroker.web@2.5.3`.

I was able to successfully import your project, however you have to be patient it takes a around 30 seconds and there is currently no loading indicator.

**Comment by FlexerJR** [comment]
Thank you so much!!! Awesome!
