### ISSUE TITLE
[bug]: Hintergrundfarbe horizontaler Navigation nicht konfigurierbar

### ISSUE THREAD

**Issue by iAgrippa** [ioBroker/ioBroker.vis-2#256]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Attribut "Hintergrundfarbe" von Navigation wird bei Auswahl von Orientierung "Vertikal" ausgeblendet. Früher zugewiesene Farben  horizontaler Menüpunkte können nicht geändert werden.

### To Reproduce

wie beschrieben, siehe kurzes GIF.

### Expected behavior

Bei Anwahl horizontaler sowie vertikaler Navigationspunkte kann Hintergrundfarbe zugewiesen, aber auch geändert werden können.

### Screenshots & Logfiles

![color](https://github.com/ioBroker/ioBroker.vis-2/assets/151877956/442d3fc6-f925-4b62-ae84-ad7b417b8a4e)

### Adapter version

2.9.6

### js-controller version

5.0.17

### Node version

v18.19.0

### Operating system

 Debian GNU/Linux 12, W10 - Edge ..

**Comment by foxriver76** [comment]
It is explicitly only available for the vertical version, so not really a bug. And it should also not be applied to the vertical version. So works as intended currently.

**Comment by iAgrippa** [comment]
Vorgesehen ja, aber ich habe in irgendeiner Version die Farbe des horizontales Menus testweise verändert, dabei gewundert, das die Schriftfarbe nicht der Hintergrundfarbe anpassbar war.

**Comment by iAgrippa** [comment]
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/151877956/649e18ba-1a0e-4ad8-a4be-a08ed14f2c68)

**Comment by iAgrippa** [comment]
.. aber ok, ich kann die Seite neu aufbauen und bin die Farbe damit los.

**Comment by foxriver76** [comment]
okay mysteriös, dass da noch etwas angezogen wird oder kannst du das mit der aktuellen Version reproduzieren?

**Comment by iAgrippa** [comment]
bin noch einmal zu **v2.9.1** zurück, aber auch hier ist Farbgebung nur vertikal möglich. Ich kann es leider nicht tiefer reproduzieren und gebe auf, das Bild oben ist kein Fake. Manchmal schafft man das Unmögliche :-) 

Ich würden den Punkt gerne schließen, kann ich das selbst ? - versuche das mal - bin hier auf unsicherem Boden.
