### ISSUE TITLE
[bug]: "Basic Image" Widgets werden nicht mehr ausgeblendet, wenn Objekt ID von Signalbild und Sichtbarkeit ungleich sind

### ISSUE THREAD

**Issue by Pechi1** [ioBroker/ioBroker.vis-2#258]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Seit dem Update auf die Version 2.9.6 werden manche "Basic Image" Widgets nicht mehr korrekt ausgeblendet. Nach einem Vergleich einiger Widget exports habe ich bemerkt, dass nur jene Widgets nicht korrekt ausgeblendet werden, die eine unterschiedliche Objekt ID für das erste Signalbild und die Sichtbarkeit verwenden. Das Widget wird eingeblendet obwohl auch das Signalbild nicht aktiv ist. 
Wenn man etwas an dem Widget verändert egal ob es die Position oder irgend eine andere Eigenschaft ist wird es danach im Browser ausgeblendet. Jedoch nach einem Wechsel der View ist es wieder sichtbar. 

### To Reproduce

Basic Image Widget erstellen mit unterschiedlichen Werten für Objekt ID von Signalbild und Sichtbarkeit

### Expected behavior

Widget sollte immer ausgeblendet werden wenn Bedingung für Sichtbarkeit nicht erfüllt ist. 
Dies war auch vor dem Update der Fall. Leider habe ich aber die vorherige Versionsnummer nicht notiert. 

### Screenshots & Logfiles

kein Logfile oder Screenshot sinnvoll.

### Adapter version

2.9.6

### js-controller version

5.0.16

### Node version

16.17.0

### Operating system

Raspbian GNU/Linux 11 (bullseye)

**Comment by foxriver76** [comment]
Konnte ich eben leider nicht nachstellen, magst du das Widget mal exportieren.

**Comment by Pechi1** [comment]
Ich habe das Widget testweise nochmals kopiert und die Objekt ID für das Signalbild gleich dem der Sichtbarkeit gestellt.

Der Export des Orignial Widget welches nicht ausgeblendet wird:
`[
  {
    "tpl": "tplImage",
    "data": {
      "g_fixed": false,
      "g_visibility": true,
      "g_css_font_text": false,
      "g_css_background": false,
      "g_css_shadow_padding": false,
      "g_css_border": false,
      "g_gestures": false,
      "g_signals": true,
      "g_last_change": false,
      "visibility-cond": "==",
      "visibility-val": "1",
      "visibility-groups-action": "hide",
      "refreshInterval": "0",
      "signals-cond-0": "==",
      "signals-val-0": true,
      "signals-icon-0": "/icons-open-icon-library-png/status/weather-showers-scattered-2.png",
      "signals-icon-size-0": "45",
      "signals-blink-0": true,
      "signals-horz-0": 0,
      "signals-vert-0": 0,
      "signals-hide-edit-0": false,
      "signals-cond-1": "==",
      "signals-val-1": true,
      "signals-icon-1": "/vis/signals/lowbattery.png",
      "signals-icon-size-1": 0,
      "signals-blink-1": false,
      "signals-horz-1": 0,
      "signals-vert-1": 0,
      "signals-hide-edit-1": false,
      "signals-cond-2": "==",
      "signals-val-2": true,
      "signals-icon-2": "/vis/signals/lowbattery.png",
      "signals-icon-size-2": 0,
      "signals-blink-2": false,
      "signals-horz-2": 0,
      "signals-vert-2": 0,
      "signals-hide-edit-2": false,
      "lc-type": "last-change",
      "lc-is-interval": true,
      "lc-is-moment": false,
      "lc-format": "",
      "lc-position-vert": "top",
      "lc-position-horz": "right",
      "lc-offset-vert": 0,
      "lc-offset-horz": 0,
      "lc-font-size": "12px",
      "lc-font-family": "",
      "lc-font-style": "",
      "lc-bkg-color": "",
      "lc-color": "",
      "lc-border-width": "0",
      "lc-border-style": "",
      "lc-border-color": "",
      "lc-border-radius": 10,
      "lc-zindex": 0,
      "src": "/vis.0/Icons/DoorOpen.svg",
      "visibility-oid": "knx.0.Allgemein_EG.Fenster.Wintergarten_Türe_Carport",
      "signals-oid-0": "knx.0.Allgemein.Wetter.Regensensor_neu",
      "bindings": [],
      "signals-count": "1"
    },
    "style": {
      "left": "104px",
      "top": "201px",
      "width": "48px",
      "height": "89px",
      "bindings": []
    },
    "widgetSet": "basic",
    "_id": "i000001"
  }
]`

Der Export der Test Kopie (wird ausgeblendet):
`[
  {
    "tpl": "tplImage",
    "data": {
      "g_fixed": false,
      "g_visibility": true,
      "g_css_font_text": false,
      "g_css_background": false,
      "g_css_shadow_padding": false,
      "g_css_border": false,
      "g_gestures": false,
      "g_signals": true,
      "g_last_change": false,
      "visibility-cond": "==",
      "visibility-val": "1",
      "visibility-groups-action": "hide",
      "refreshInterval": "0",
      "signals-cond-0": "==",
      "signals-val-0": true,
      "signals-icon-0": "/icons-open-icon-library-png/status/weather-showers-scattered-2.png",
      "signals-icon-size-0": "45",
      "signals-blink-0": true,
      "signals-horz-0": 0,
      "signals-vert-0": 0,
      "signals-hide-edit-0": false,
      "signals-cond-1": "==",
      "signals-val-1": true,
      "signals-icon-1": "/vis/signals/lowbattery.png",
      "signals-icon-size-1": 0,
      "signals-blink-1": false,
      "signals-horz-1": 0,
      "signals-vert-1": 0,
      "signals-hide-edit-1": false,
      "signals-cond-2": "==",
      "signals-val-2": true,
      "signals-icon-2": "/vis/signals/lowbattery.png",
      "signals-icon-size-2": 0,
      "signals-blink-2": false,
      "signals-horz-2": 0,
      "signals-vert-2": 0,
      "signals-hide-edit-2": false,
      "lc-type": "last-change",
      "lc-is-interval": true,
      "lc-is-moment": false,
      "lc-format": "",
      "lc-position-vert": "top",
      "lc-position-horz": "right",
      "lc-offset-vert": 0,
      "lc-offset-horz": 0,
      "lc-font-size": "12px",
      "lc-font-family": "",
      "lc-font-style": "",
      "lc-bkg-color": "",
      "lc-color": "",
      "lc-border-width": "0",
      "lc-border-style": "",
      "lc-border-color": "",
      "lc-border-radius": 10,
      "lc-zindex": 0,
      "src": "/vis.0/Icons/DoorOpen.svg",
      "visibility-oid": "knx.0.Allgemein_EG.Fenster.Wintergarten_Türe_Carport",
      "signals-oid-0": "knx.0.Allgemein_EG.Fenster.Wintergarten_Türe_Carport",
      "bindings": [],
      "signals-count": "1"
    },
    "style": {
      "left": 35,
      "top": 197,
      "width": "48px",
      "height": "89px",
      "bindings": []
    },
    "widgetSet": "basic",
    "_id": "i000001"
  }
]`

Links der Editor und rechts die Runtime Seite.
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/154329503/53058322-9181-4bd6-a8fd-50aadea705cd)

**Comment by foxriver76** [comment]
Irgendwas stimmt da jedenfalls nicht, ist das bei dir auch so wenn du in einem der beiden Widgets das Feld `Wert für Bedingung` änderst, sich das auch im anderen ändert?
