### ISSUE TITLE
Bindings always work with strings (instead of real value)

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.vis-2#26]
1. Create a new state ``0_userdata.0.myNumber`` of type number
2. Set a value
3. Create a new html widget with the following content: ``{x:0_userdata.0.myNumber;typeof x}``
4. Result: ``string`` (instead of number)

Why is every value casted to a string? Same for

``{x:0_userdata.0.myNumber.val;typeof x}``

------

For a boolean state, the result is e.g. ``"true"`` or ``"false"``

**Comment by foxriver76** [comment]
as it was the same in vis1 I think it is probably intended to not break bindings. 

https://github.com/ioBroker/ioBroker.vis#bindings-of-objects

> Take care about types. All of them are defined as strings. To be sure, that value will be treated as number use parseFloat function.

@GermanBluefox won't do or planned?

**Comment by foxriver76** [comment]
It seems like the new vis-2 bindings are now supporting the correct data types. Please re-check
