### ISSUE TITLE
[bug]: Umzug von einem Gerät zu einem anderen nicht möglich

### ISSUE THREAD

**Issue by Duffy987** [ioBroker/ioBroker.vis-2#264]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Ich habe meine Commuity online Lizenz von Vis zu Vis 2 umgewandelt für mein Testsystem.
Nachdem der Test erfolgreich verlief wollte ich die Vis2 auch auf meinem Aktivsystem installieren und aktivieren.
Dabei wurde mir bei der Aktivierung, je nach Vorgehen, mitgeteilt das die Lizenz schon für ein anderes Device vergeben ist.
Daraufhin habe ich Vis2 vom Testsystem deinstalliert. Leider bekomme ich Vis2 auf dem Aktivsystem dennoch nicht aktiviert. 

Wie kann mach die Lizenz umziehen oder muss man eine neue käuflich erwerben?

### To Reproduce

1. In den Instanzen am Aktivsystem in die Vis2 gehen
2. Schraubenschlüssel anklicken
3. Lizenzmanager verwenden anklicken
4. Lizenz prüfen klicken
5.
![Screenshot 2023-12-22 111910](https://github.com/ioBroker/ioBroker.vis-2/assets/120317770/8fbb3b0f-ba9e-4ffd-a849-84e88f29ea00)

6. Ja, anklicken
7. Es dreht sich ein Ring bei "Lizenz prüfen" weiter passieret aber nichts mehr.

weiterer Versuch:
Wenn ich die Lizenz vom Testsystem in das Aktivsystem kopiere kommt folgender Fehler:

![Screenshot 2023-12-22 111212](https://github.com/ioBroker/ioBroker.vis-2/assets/120317770/746a812d-9c19-4e7b-8a87-bce5694e6948)

### Expected behavior

Ich hätte erwartet, gehofft, das man entweder auf beiden Geräten die Vis2 laufen lassen kann oder zumindest eine möglichkeit hat die Lizenz von einem zum anderen Gerät umzuziehen.

### Screenshots & Logfiles

![Screenshot 2023-12-22 111212](https://github.com/ioBroker/ioBroker.vis-2/assets/120317770/fed2c8a1-286a-4e06-ada0-c1417ef14d53)
![Screenshot 2023-12-22 111910](https://github.com/ioBroker/ioBroker.vis-2/assets/120317770/558e5da6-6f4a-4d9d-bc34-e35dea47ef16)

### Adapter version

2.6.1

### js-controller version

5.0.17

### Node version

18.19.0

### Operating system

Raspberry Pi OS Bookworm

**Comment by foxriver76** [comment]
Bitte Mail mit neuer UUID an info@iobroker.net

**Comment by Duffy987** [comment]
Gelöst. 

Vielen Dank.
