### ISSUE TITLE
[bug]: Auschneiden eines Widgets innerhalb einer Gruppe geht nicht

### ISSUE THREAD

**Issue by afuerhoff** [ioBroker/ioBroker.vis-2#267]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Ausschneiden innerhalb einer Gruppe funktioniert nicht. Es wird einen leere Seite angezeigt.

### To Reproduce

Innerhalb einer Gruppe wird beim Ausschneiden eines Widgets mit Strg X oder auch Ausschneiden im Menü eine leere Seite angezeigt.

### Expected behavior

Das Widget wird ausgeschnitten und in die Zwischenablage kopiert.

### Screenshots & Logfiles

keine

### Adapter version

2.9.8

### js-controller version

5.0.17

### Node version

18.18.2

### Operating system

Debian 12 - Proxmox

**Comment by Feuer-sturm** [comment]
@afuerhoff Bitte den Inhalt von der Konsole (F12) speziell die Errors hier posten.

**Comment by afuerhoff** [comment]
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/f902df5f-50c3-4dfc-a872-c07f3711bc0e)
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/94c5e432-bc23-4042-b4a0-b102367c9c99)

**Comment by afuerhoff** [comment]
Mit v2.9.12 kann man das Widget innerhalb einer Gruppe ausschneiden, aber es bleibt ein Bild des Widget zurück, das erst nach Aktualisierung verschwindet. Das Widget "zu" außerhalb der Gruppenumrandung wurde ausgeschnitten, wird aber noch angezeigt. Kann aber nicht mehr selektiert werden.
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/50245893/444d9cab-a718-409c-b480-ab076558db60)

**Comment by foxriver76** [comment]
Ok ich mache nochmal auf hier um das anszuschauen warum das bis zur Aktualisierung zurück bleibt

**Comment by afuerhoff** [comment]
Funktioniert jetzt mit v2.9.13. Danke
