### ISSUE TITLE
Bulb on/off

### ISSUE THREAD

**Issue by programmcs** [ioBroker/ioBroker.vis-2#271]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Bulb on/off wechselt das hinterlegte Svg nicht mehr. Konkret handelt es sich um eine Status anzeige wenn ich die Heizungsbetriebsart ändere ist das sozusagen die Rückmeldung das auf knx Seite alles übernommen worden ist. Es kommt z.B. eine 2 als Status und beim Bulb on/off ist min 2 und max 2 hinterlegt. es reagiert aber nicht. Bei der beta Version ging diese Funktion bzw geht noch.

### To Reproduce

Das kann ich nicht sagen alle Status Meldungen die über eine Nummer kommen gehen nicht die gesendeten befehle werden hingegen angezeigt.

### Expected behavior

Das wenn eine 2 als Status kommt das SVG gewechselt wird.

### Screenshots & Logfiles

![image](https://github.com/ioBroker/ioBroker.vis-2/assets/55063928/0fd95417-5a45-4292-98c5-58a76cbbd71d)

### Adapter version

2.9.8

### js-controller version

5.0.16

### Node version

18.19.0

### Operating system

docker container

**Comment by foxriver76** [comment]
hm aber min und max 2? mir ist nicht klar, wie definiert ist, dass sich das Widget mit dieser Konfiguration verhalten sollte.

**Comment by programmcs** [comment]
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/55063928/1f43e05a-26e2-42d1-98fc-0361a77d2b8c)
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/55063928/84064cfb-033f-4d76-815a-759d86880917)
Hallo beim ersten Bild zeigt es das verhalten von der beta Version beim zweiten das verhalten von der vis 2 next generation.

es ist so das es beim knx eine Betriebsartenumschaltung für die Heizung gibt sowie einen Rückmeldung das die Betriebsart gewechselt wurde. Die Betriebsarten sind 1,2,3,4 klicke ich auf z.B. das Haus was blau leuchtet, wird eine zwei zum KNX Gerät gesendet sobald eine Rückmeldung kommt das er gewechselt hat was auch eine zwei ist geht die blaue Markierung wieder weg, obwohl sie weiterhin beibehalten bleibt.

![image](https://github.com/ioBroker/ioBroker.vis-2/assets/55063928/35eb1062-663f-4c9f-8cdf-74e937b59613)
Das ist die Einstellung vom knx Adapter.
ich hoffe ich konnte helfen

**Comment by programmcs** [comment]
Hallo man kann es recht gut nachstellen wenn man eine Variable (type number) unter Objekte erstellt, diese an den Bulb on/off unter Object ID anschließt die min und max grenze auf 2 setzt und die Variable dann im IObroker manuell auf auf zwei setzt schaltet das Icon nicht um. Es ist so das variablen mit number wenn es nicht  über die Vis geschalten wird nicht aktualisiert wird. 

Bool Variablen werden aktualisiert in der Vis

ich hoffe das kann weiterhelfen
