### ISSUE TITLE
[bug]: Angabe von Breite und Höhe via Css nicht Maßstabsgetreu

### ISSUE THREAD

**Issue by peoples0815** [ioBroker/ioBroker.vis-2#273]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Ich verwende das "Basic-HTML-Widget" für die Navigation und habe das in meiner alten Visualisierung über CSS gestaltet was problemlos möglich war.
In Vis 2 werden nur Teile des CSS übernommen (Höhe und Breite nicht) deklariere ich die Buttons aber im Editor direkt funktioniert es.
![1703698144050-buttons](https://github.com/ioBroker/ioBroker.vis-2/assets/39387321/433a24f5-3787-4144-b615-b3293c3ce346)

Die Höhe und Breite des linken Buttons wurde im Editor angegeben (auch Lineheigt wird aber ignoriert), bei den beiden rechten Buttons stehen die Angaben in CSS und die Editorfelder sind leer.

`.button_site_navigation_grey
    {
        height:194px;
    	width:150px;
    	line-height:94px;
        text-align:center;
        vertical-align:middle;
    	border:#85888a solid 3px;
        border-radius: 5px;
    	font-size:22px;
    	background: #0079FF;
        background: -webkit-gradient(linear, 0% 0%, 0% 100%, from(#676a6e), to(#1f2122));
        background: -webkit-linear-gradient(0% 0%, 0% 100%, from(#676a6e), to(#1f2122));
        background: -moz-linear-gradient(center top, #676a6e, #1f2122);
        color:white;
    }`

### To Reproduce

1. Das Basic-HTML-Widget einfügen
2. Css im Reiter Css einfügen
3. Dem Widget die Klasse zuweisen
4. Fertig

### Expected behavior

Ich erwartete durch die Größenangabe im CSS und im Editor die gleiche Größe der Ausgabe

### Screenshots & Logfiles

Siehe Bild im Text oben 

### Adapter version

Vis2.9.8

### js-controller version

5.0.17

### Node version

18.19.12

### Operating system

Debian 12

### Additional context

.

**Comment by foxriver76** [comment]
without checking, have you checked if specifying the affected attributes with `!important` helps?

**Comment by peoples0815** [comment]
If you put !important behinde the command "height" and "width" it works, but "vertical-align: middle" is still ignored

**Comment by foxriver76** [comment]
Some widgets from vis-1 got migrated and optimized code wise, it can be that they now consist of different html tags in detail. So most likely you will simply need to adjust your css for the new structure. The css defined by you is correctly applied, so I do not really see an issue here which we should tackle in code.

**Comment by peoples0815** [comment]
The adjustment is no problem, i just wanted to inform about this. 
But still "vertical-align: middle" is still ignored.

If this is no issue, you can close it
