### ISSUE TITLE
[bug]: Sichtbarkeit von Widgets – Haken muss im Feld zwingend gesetzt werden

### ISSUE THREAD

**Issue by MK-66** [ioBroker/ioBroker.vis-2#280]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Bei der Version V2.9.9 gibt es ein Problem mit der Sichtbarkeit von Widgets: Wenn der Haken im Feld „Sichtbarkeit“ nicht gesetzt wird, werden diese in der VIS runtime auch nicht mehr angezeigt.

### To Reproduce

Der Haken im Feld „Sichtbarkeit“ muss jetzt offenbar bei jedem Widget zwingend gesetzt werden (auch mit leerer Objekt ID), sonst werden die Widgets in der VIS runtime einfach nicht mehr angezeigt.

### Expected behavior

Widgets sollen in der VIS runtime nur ausgeblendet werden, wenn der Haken im Feld "Sichtbarkeit" gesetzt ist und dann dort die Bedingung nicht erfüllt ist.

### Screenshots & Logfiles

![Screenshot Sichtbarkeit](https://github.com/ioBroker/ioBroker.vis-2/assets/56516310/be00ed04-b05a-4c8c-9978-d99f9814d21d)

### Adapter version

2.9.9

### js-controller version

5.0.17

### Node version

18.19.0

### Operating system

Debian 12

**Comment by Risiko98** [comment]
Bei mir ist das gleiche Problem.
Danke für den Tipp mit der "Sichtbarkeit", so kann ich mir jetzt wenigstens helfen.
Adapter 2.9.10
js-controller: 5.0.17
NPM: 10.2.3
Node.js: v18.19.0
docker (official image - v9.0.1)
