### ISSUE TITLE
[bug]: Editor-Menü verschiebt sich und lässt sich nicht korrigieren

### ISSUE THREAD

**Issue by peoples0815** [ioBroker/ioBroker.vis-2#282]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

![Editor_vis2](https://github.com/ioBroker/ioBroker.vis-2/assets/39387321/16582609-bf9c-47d9-86a8-a66f0095527d)

Den Bereich der Widgetangaben / Seitenangaben / CSS (Rote Pfeile) habe ich um den kompletten Pfad des eingebetteten Bildes zu sehen nach links aufgezogen, dabei vergrößerte sich auch der "gelbe Bereich" automatisch. Nun kann ich zwar den Bereich der roten Pfeile wieder verkleinern, jedoch nicht den Bereich der gelben Pfeile.

**Der Fehler lässt sich durch löschen des Browsercache und der Cookies zurücksetzen.**

### To Reproduce

Css Menü im Editor nach links aufziehen und der Bereich in gelb wurde bei mir größer

Der Fehler lässt sich durch löschen des Browsercache und der Cookies zurücksetzen.

### Expected behavior

Ich hätte erwartet, dass der Bereich sich wieder verkleinert

### Screenshots & Logfiles

Siehe Bild oben

### Adapter version

Vis 2.9.8

### js-controller version

5.0.17

### Node version

18.19.12

### Operating system

Debian 12

### Additional context

Im Forum habe ich auch nachgefragt, hier zeigte sich dass der Fehler schon bei mehreren aufgetreten ist:
https://forum.iobroker.net/topic/67676/vis-2-0-neuer-adapter-als-beta/652

Die hier gefundene Lösung ist das löschen des Browser Cache / Cookies

**Comment by MK-66** [comment]
**Ergänzung zu dem issue von peoples0815:**
Bei mir tritt dieser Fehler mit dem verschobenen Menü im Editor auch auf und zwar anscheinend immer dann, wenn ich den genannten Bereich vergrößern/verkleinern möchte und genau zu dem Zeitpunkt das Speichern Symbol noch aktiv ist.

**Comment by foxriver76** [comment]
Lässt sich wie folgt gut nachstellen: 

1. Änderung am View vornehmen
2. Die Attribute-Ansicht mit der Maus größer/kleiner ziehen und weiterhin in diesem Zustand halten
3. Mit `strg + z` während Maus immer noch gehalten die Änderung rückgänig machen
