### ISSUE TITLE
[bug]: Bindings of objects  

### ISSUE THREAD

**Issue by eisbaer721** [ioBroker/ioBroker.vis-2#288]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Wenn in einem Binding {object.id} eingetragen wird sollte eigentlich der Datenpunkt aus dem Object id  verwendet werden.

### To Reproduce

1. Widget Basic HTML State  
2. Karte Allgemein   Objekt ID :   0_userdata.0.Z-Test_Objekte.Testbutton
3. Karte CSS Font & Text  Farbe : {myvar:{object.id}; myvar==true ? "#008000" : "#ff0000"}

### Expected behavior

Nach der Anleitung verstehe ich das so das {objekt.id}  eine Variable ist und den Datenpunkt von Pos.2 nimmt.
Trage ich den Wert direkt in das Binding ein funktioniert es.

### Screenshots & Logfiles

![1704492310406-a817c2b7-d17a-4401-b91f-a53b4cfd869c-image](https://github.com/ioBroker/ioBroker.vis-2/assets/46114394/cda3d465-65a9-47f6-8cbc-225f6fc7bd54)
![Screenshot 2024-01-06 180519](https://github.com/ioBroker/ioBroker.vis-2/assets/46114394/583d0c5e-05a9-45ed-8f91-0952ea236f7b)

### Adapter version

2.9.12

### js-controller version

5.0.17

### Node version

v18.19.0

### Operating system

Debian

**Comment by foxriver76** [comment]
In deinem Screenshot schreibst du Objekt mit k, habs nich gerätst aber nicht dass e smut das ist..

**Comment by eisbaer721** [comment]
Sorry. Es war schon sehr spät gestern.....   Ich habe es noch mal getestet und oben korrigiert. 
Der Fehler ist wohl leider.
