### ISSUE TITLE
[bug]: Zeige letzte Änderung, Offset y 

### ISSUE THREAD

**Issue by Smarthome-66** [ioBroker/ioBroker.vis-2#289]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Offset y kann nur 2 Darstellungen. Eine davon bei Wert 0 und die andere bei jedem anderen Wert als 0. Dies ist in Version 1.x anders. die Darstellung der "letzten Änderung" kann in Y-Richtung individuell verschoben werden. Die gilt sowohl für positive, als auch für negative Werte.

### To Reproduce

1. Irgend ein Widget auswählen
2. Bei Attribute auf "Zeige letzte Änderung"
3. Eine Objekt-ID auswählen
4. Offset y Einstellung verändern. Verschiedene Werte außer 0 mit dem Ergebnis das die Darstellung sich nicht ändert.

### Expected behavior

Bei verschiedenen Werten in "Offset y" sollte die Darstellung der letzten Änderung im Widget an andere Position wandern. Das ist für positive und negative Werte möglich

### Screenshots & Logfiles

Ein Beispiel: 
Darstellung bei VIS 1.4.16 
![grafik](https://github.com/ioBroker/ioBroker.vis-2/assets/155836222/d5271134-c17a-4e63-a203-7bd7be75fcff)
![grafik](https://github.com/ioBroker/ioBroker.vis-2/assets/155836222/42298bed-8a6b-486e-92cf-962084015e3c)

Darstellung bei VIS 2
![grafik](https://github.com/ioBroker/ioBroker.vis-2/assets/155836222/197ead4f-12bf-4345-a5c6-9757ef786533)
![grafik](https://github.com/ioBroker/ioBroker.vis-2/assets/155836222/5784c188-07e2-441a-a5ae-a58bc4dea48f)

### Adapter version

2.9.11

### js-controller version

5.0.16

### Node version

18.17.1

### Operating system

Linux

**Comment by foxriver76** [comment]
Kann ich nicht nachstellen (siehe Video) oder es betrifft nur spezielle widgets. Magst du das betroffene Widget mal exportieren und hier posten?

[Bildschirmaufzeichnung vom 08.01.2024, 10:19:07.webm](https://github.com/ioBroker/ioBroker.vis-2/assets/25484431/4adc1ead-3867-4314-a2ae-544227dc8a3e)

**Comment by Smarthome-66** [comment]
Hallo Max,
Danke für die schnelle Antwort.
Anbei ein Export des Beispielwidget.

[{"tpl":"tplHqInTemp","data":{"g_fixed":false,"g_visibility":false,"g_css_font_text":false,"g_css_background":false,"g_css_shadow_padding":false,"g_css_border":false,"g_gestures":false,"g_signals":true,"g_last_change":true,"visibility-cond":"==","visibility-val":1,"visibility-groups-action":"hide","oid":"shelly.1.SHTRV-01#xxxxxx#1.tmp.temperatureTargetC","unit":"°C","min":"4","max":"31","digits":"1","step":"0.5","is_comma":"true","iconName":"/icons-mfd-svg/sani_heating_temp.svg","btIconWidth":"65","offsetAuto":"true","leftOffset":"25","topOffset":"55","circleWidth":"50","showValue":"true","timeAsInterval":"true","infoLeftFontSize":"12","infoFontRightSize":"12","infoLeftPaddingLeft":"10","infoLeftPaddingRight":"40","infoRightPaddingRight":"10","styleNormal":"hq-button-base-intemp","signals-cond-0":"==","signals-val-0":true,"signals-icon-0":"/vis.0/update-icon.svg","signals-icon-size-0":"","signals-blink-0":false,"signals-horz-0":"70","signals-vert-0":"-35","signals-hide-edit-0":false,"signals-cond-1":"==","signals-val-1":"false","signals-icon-1":"/vis/signals/wifiColorRed.png","signals-icon-size-1":0,"signals-blink-1":false,"signals-horz-1":"-100","signals-vert-1":"-50","signals-hide-edit-1":false,"signals-cond-2":"==","signals-val-2":true,"signals-icon-2":"/vis/signals/wifiColor.png","signals-icon-size-2":0,"signals-blink-2":false,"signals-horz-2":"-100","signals-vert-2":"-50","signals-hide-edit-2":false,"lc-type":"timestamp","lc-is-interval":false,"lc-is-moment":true,"lc-format":"DD.MM.YYYY hh:mm","lc-position-vert":"bottom","lc-position-horz":"right","lc-offset-vert":"-22","lc-offset-horz":"-90","lc-font-size":"12px","lc-font-family":"","lc-font-style":"","lc-bkg-color":"#bbbbbb","lc-color":"","lc-border-width":"0","lc-border-style":"","lc-border-color":"","lc-border-radius":"","lc-zindex":0,"descriptionLeft":"Heizung<br>Schlafzimmer","oid-actual":"shelly.1.SHTRV-01#xxxxx#1.tmp.temperatureC","oid-drive":"shelly.1.SHTRV-01#xxxxx#1.tmp.valvePosition","lc-oid":"shelly.1.SHTRV-01#xxxxx#1.tmp.valvePosition","oid-battery":"0_userdata.0.Heizung_Batterie.Batterie_Schlafzimmer","infoRightPaddingLeft":"5","signals-oid-0":"shelly.1.SHTRV-01#xxxxx#1.firmware","signals-oid-1":"shelly.1.SHTRV-01#xxxxx#1.online","signals-text-1":"Wifi off","signals-text-style-1":"color: red; font-size: 10px; font-weight: bold; text-align: left; margin-top: -25px","signals-icon-style-0":"width: 20px; margin-left: 10px","signals-text-0":"Update","signals-text-style-0":"color: red; font-size: 10px; font-weight: bold; text-align: left; margin-top: -20px","signals-text-style-2":"color: #027ec2; font-size: 10px; font-weight: bold; text-align: left; margin-top: -25px","signals-oid-2":"shelly.1.SHTRV-01#xxxxx#1.online","signals-text-2":"{shelly.1.SHTRV-01#xxxxx#1.rssi}dBm","signals-icon-style-1":"width: 33px; margin-left: 40px","signals-icon-style-2":"width: 33px; margin-left: 40px"},"style":{"left":"780px","top":"170px"},"widgetSet":"hqwidgets"}]
