### ISSUE TITLE
Vis2 Browserlog beim öffnen der vis und neu laden der Viewesseite beim umschalten der Palette

### ISSUE THREAD

**Issue by crunchip77** [ioBroker/ioBroker.vis-2#29]
Vis2.0.9
es sind noch keine neuen vis2 widgets installiert

Nachdem öffnen  erscheint im Browserlog
`Failed to load resource: the server responded with a status of 404 (Not Found)
VM1841:4 Uncaught TypeError: Cannot read properties of undefined (reading 'localization')
    at <anonymous>:4:39
    at Xe.<anonymous> (697.7c00624a.chunk.js:29:37779)
    at Generator.next (<anonymous>)
    at 697.7c00624a.chunk.js:29:16218
    at new Promise (<anonymous>)
    at wi (697.7c00624a.chunk.js:29:16038)
    at Xe.setInnerHTML (697.7c00624a.chunk.js:29:37201)
    at Xe.<anonymous> (697.7c00624a.chunk.js:29:38260)
    at Generator.next (<anonymous>)
    at r (697.7c00624a.chunk.js:29:16076)
widgets/info/js/info.js:84 Uncaught SyntaxError: Unexpected end of input
DevTools failed to load source map: Could not load content for http://10.1.1.10:8082/vis-2-beta/static/js/main.1426430e.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://10.1.1.10:8082/vis-2-beta/static/js/398.c8d8d1e7.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://10.1.1.10:8082/vis-2-beta/static/js/26.e8dea23d.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://10.1.1.10:8082/vis-2-beta/static/js/697.7c00624a.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://10.1.1.10:8082/vis-2-beta/static/js/78.756f4070.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://10.1.1.10:8082/vis-2-beta/widgets/material-webfont/css/materialdesignicons.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://10.1.1.10:8082/vis-2-beta/static/css/697.79098e54.chunk.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
3DevTools failed to load source map: Could not load content for http://10.1.1.10:8082/vis-2-beta/widgets/material-webfont/css/materialdesignicons.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

schliest bzw öffnet man links die Palette, verschwindet die View und wird neu geladen, was mehrerer Sekunden andauert, dabei wird diese Zeile im Browserlog hochgezählt
`3DevTools failed to load source map: Could not load content for http://10.1.1.10:8082/vis-2-beta/widgets/material-webfont/css/materialdesignicons.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

beim öffnen des Reiters materialdesign in der Palette erscheint folgendes
`VM1839:2242 Uncaught TypeError: Cannot read properties of undefined (reading 'pressed')
    at HTMLDocument.<anonymous> (<anonymous>:2242:29)
    at HTMLDocument.dispatch (jquery-1.11.2.min.js:3:8549)
    at r.handle (jquery-1.11.2.min.js:3:5252)
(anonymous) @ VM1839:2242
dispatch @ jquery-1.11.2.min.js:3
r.handle @ jquery-1.11.2.min.js:3
DevTools failed to load source map: Could not load content for http://10.1.1.10:8082/vis-2-beta/widgets/material-webfont/css/materialdesignicons.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
9Failed to decode downloaded font: <URL>
9OTS parsing error: Failed to convert WOFF 2.0 font to SFNT`

**Comment by Feuer-sturm** [comment]
@crunchip77 please check with new adapter vis-2 version 2.2.2 and current version of vis-2 widget adapters.
If this issue is still active we can reopen it.
