### ISSUE TITLE
Widget "jqui-input" saves numbers as strings - see also issue #372

### ISSUE THREAD

**Issue by WillyIoBrok** [ioBroker/ioBroker.vis-2#30]
Issue: the "jqui-input" widget will save an entered value as string even though the checkbox "As string" is not selected.

Steps to reproduce:

    create a new state of type "number"
    create a new vis view containing 1 jqui-input widget that is linked to the new state. save the view.
    Make sure, that in the configuration of this widget the switch "as string:" is untagged/switched off.
    -> by this, I would expect, that numbers entered by hand are written into the DP as number

    open the view and enter a number in that input field (ex: 100).
    
    look into the log - you will see a warning like this, telling you, that a string has been written into the DP
    <html><body>

web.0 | 2023-07-23 10:25:15.752 | info | State value to set for "new state" has to be type "number" but received type "string"
-- | -- | -- | --

</body>
</html>

**Expected behavior**  
if "As string:" is untagged, I would expect, that a number will be sent to the linked DPs, not a string

**Additional context**  
this issue seems to be very old (at least since 2017) and has been raised by many people, but there seems to be no change on this behaviour. It has been issued in 2017 as issue ioBroker/ioBroker.vis#372

As long as you don't rely on the fact, that you have a number type, everything seems to work perfect (except the warning in the log). But if to do mathematical calculations on the data, the result of these calculations on strings will be nonsense. If you do those calculations only under certain cases, you get very hard to find errors.

**Comment by foxriver76** [comment]
still happening @Feuer-sturm?

For me it works, setting numbers correctly

![grafik](https://github.com/ioBroker/ioBroker.vis-2/assets/25484431/9f8e5a19-e6d9-470f-9803-8823eb43b014)

**Comment by foxriver76** [comment]
Or is it another widget? Mayne you can provide an export @Feuer-sturm

**Comment by WillyIoBrok** [comment]
Hello,
I tested it once more (with vis1). The situation remains unchanged (see initial topic). Everything seems to work, but there is still a string sent to the DP instead of a number which creates at least a warning in the log.

**Comment by foxriver76** [comment]
The question is: is the State value previously a String or a number. Maybe someone can provide an Export of the Widget.

**Comment by Feuer-sturm** [comment]
@Feuer-sturm I can't reproduce the behavior any more. From my point of view it is fine now
tested widget: Gestylt Eingabe
vis-2: 2.9.6


@WillyIoBrok Do you have the problem with vis-2 as well? vis-1 is not in focus here.

**Comment by WillyIoBrok** [comment]
as mentioned above I don't use vis-2 (yet). 
In vis-1 I reproduced the erroneous behaviour some minutes ago.

**Comment by Feuer-sturm** [comment]
@WillyIoBrok vis-1 is not in focus of this repository. Here we track only issues for vis-2 :-)

**Comment by WillyIoBrok** [comment]
ok, no problem. I don't have a real problem any more since I know the behaviour and have workarounds in place ...
