### ISSUE TITLE
Weißer Startbildschirm [bug]: 

### ISSUE THREAD

**Issue by TripleX1978** [ioBroker/ioBroker.vis-2#303]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Nachdem ich die VIS starte ploppt der Startbildschirm kurz auf bevor man dann nur noch einen weißen Bildschirm hat.

### To Reproduce

VIS installiert, VIS gestartet

### Expected behavior

VIS-Startseite sollte zu sehen sein.

### Screenshots & Logfiles
```
<html>
<body>
<!--StartFragment-->
2024-01-11 19:04:24.987 | warn | Force build done! Restarting...
-- | -- | --
web.0 | 2024-01-11 19:04:35.556 | error | can't render tplMetroDect200TileSwitchDialog w00005 on "01-Startseite":
web.0 | 2024-01-11 19:04:35.559 | error | 0 - TypeError: Cannot read properties of undefined (reading 'tile')TypeError: Cannot read properties of undefined (reading 'tile')
web.0 | 2024-01-11 19:04:35.561 | error | 1 - at Object.eval (tplMetroDect200TileSwitchDialog.js:156:77)
web.0 | 2024-01-11 19:04:35.562 | error | 2 - at Function.<anonymous> (http://192.168.178.71:8082/vis-2/lib/js/can.custom.js:1728:17)
web.0 | 2024-01-11 19:04:35.564 | error | 3 - at a.each (http://192.168.178.71:8082/vis-2/lib/js/can.custom.js:343:211)
web.0 | 2024-01-11 19:04:35.566 | error | 4 - at http://192.168.178.71:8082/vis-2/lib/js/can.custom.js:1727:17
web.0 | 2024-01-11 19:04:35.567 | error | 5 - at HTMLDivElement.<anonymous> (http://192.168.178.71:8082/vis-2/lib/js/can.custom.js:1419:98)
web.0 | 2024-01-11 19:04:35.569 | error | 6 - at a.each (http://192.168.178.71:8082/vis-2/lib/js/can.custom.js:343:211)
web.0 | 2024-01-11 19:04:35.571 | error | 7 - at Function.hookup (http://192.168.178.71:8082/vis-2/lib/js/can.custom.js:1418:19)
web.0 | 2024-01-11 19:04:35.573 | error | 8 - at Function.frag (http://192.168.178.71:8082/vis-2/lib/js/can.custom.js:1405:22)
web.0 | 2024-01-11 19:04:35.574 | error | 9 - at r (http://192.168.178.71:8082/vis-2/lib/js/can.custom.js:1370:22)
web.0 | 2024-01-11 19:04:35.576 | error | 10 - at Function.renderTo (http://192.168.178.71:8082/vis-2/lib/js/can.custom.js:1449:63)
web.0 | 2024-01-11 19:04:35.577 | error | 11 - at Function.renderAs (http://192.168.178.71:8082/vis-2/lib/js/can.custom.js:1465:39)
web.0 | 2024-01-11 19:04:35.579 | error | 12 - at e.view.e.template (http://192.168.178.71:8082/vis-2/lib/js/can.custom.js:1401:47)
web.0 | 2024-01-11 19:04:35.580 | error | 13 - at vt.renderWidget (http://192.168.178.71:8082/vis-2/static/js/600.223f177a.chunk.js:1:283490)
web.0 | 2024-01-11 19:04:35.582 | error | 14 - at vt.componentDidMount (http://192.168.178.71:8082/vis-2/static/js/600.223f177a.chunk.js:1:263321)
web.0 | 2024-01-11 19:04:35.583 | error | 15 - at xi (http://192.168.178.71:8082/vis-2/static/js/main.e642d05b.js:2:6648181)
web.0 | 2024-01-11 19:04:35.585 | error | 16 - at Hi (http://192.168.178.71:8082/vis-2/static/js/main.e642d05b.js:2:6647954)
web.0 | 2024-01-11 19:04:35.586 | error | 17 - at Mi (http://192.168.178.71:8082/vis-2/static/js/main.e642d05b.js:2:6647490)
web.0 | 2024-01-11 19:04:35.587 | error | 18 - at http://192.168.178.71:8082/vis-2/static/js/main.e642d05b.js:2:6659327
web.0 | 2024-01-11 19:04:35.589 | error | 19 - at Vl (http://192.168.178.71:8082/vis-2/static/js/main.e642d05b.js:2:6659842)
web.0 | 2024-01-11 19:04:35.590 | error | 20 - at ol (http://192.168.178.71:8082/vis-2/static/js/main.e642d05b.js:2:6652300)
web.0 | 2024-01-11 19:04:35.592 | error | 21 - at V (http://192.168.178.71:8082/vis-2/static/js/main.e642d05b.js:2:8046628)
web.0 | 2024-01-11 19:04:35.593 | error | 22 - at MessagePort.T (http://192.168.178.71:8082/vis-2/static/js/main.e642d05b.js:2:8047162)

<!--EndFragment-->
</body>
</html>
```

### Adapter version

2.9.11

### js-controller version

5.0.17

### Node version

18.19.0

### Operating system

Linux

**Comment by foxriver76** [comment]
Schaut aus als wäre irgendwas an einem Metro Widget inkompatibel mit vis-2. Ich weiß nicht ob die grundsätzlich funktionieren mit vis-2 - evtl. weiß @Feuer-sturm was.

**Comment by Feuer-sturm** [comment]
@foxriver76 @TripleX1978 Ich selbst habe metro nicht produktiv im Einsatz. Ich hab testweise mal einige Elemente in die VIS-2 gezogen und es gab erstmal keine wirklichen Fehler. Ich konnte aus den obigen Fehlermeldungen auch nicht genau identifizieren um welches metro widget es sich handelt.

@TripleX1978 Damit deine VIS2 erstmal startet kannst du hier im Admin einmal schauen welches Projekt importiert wurde und diesen Ordner dann löschen. Danach sollte dein vis-2 Editor erstmal starten
![grafik](https://github.com/ioBroker/ioBroker.vis-2/assets/25422320/59b171ac-f351-46d3-8160-f5014fab377e)

**Comment by foxriver76** [comment]
Closing due to lack of details.

**Comment by HaraldGrhein** [comment]
Habe vermutlich das gleiche Problem. 
ISSUE 303 ist geschlossen. Soll ich ein neues ISSUE aufmachen, und welche Infos werden noch benötigt?

VIS 2 zeigt im Edit und Runtime Screen nur weissen Screen.
Problem tritt mit Stable Repository auf.

Debian GNU/Linux 11 (bullseye)
Uptodate März 2024

Stable Repository:
iobroker 6.13.16
Node.js v18.19.1
Vis-2 29.32


root@smartON:/home/son# iobroker list adapters
system.adapter.admin                   : admin          - v6.13.16
system.adapter.alarm                   : alarm          - v3.3.11
system.adapter.alias-manager           : alias-manager  - v1.2.6
system.adapter.backitup                : backitup       - v2.10.11
system.adapter.cameras                 : cameras        - v2.0.5
system.adapter.cloud                   : cloud          - v4.4.1
system.adapter.device-reminder         : device-reminder - v3.1.2
system.adapter.discovery               : discovery      - v4.2.0
system.adapter.dwd                     : dwd            - v2.8.5
system.adapter.echarts                 : echarts        - v1.7.2
system.adapter.email                   : email          - v1.2.2
system.adapter.energiefluss            : energiefluss   - v3.6.0
system.adapter.espresense              : espresense     - v0.4.4
system.adapter.feiertage               : feiertage      - v1.1.4
system.adapter.followthesun            : followthesun   - v0.5.0
system.adapter.fullcalendar            : fullcalendar   - v2.3.4
system.adapter.fullybrowser            : fullybrowser   - v2.1.2
system.adapter.habpanel                : habpanel       - v0.5.0
system.adapter.history                 : history        - v3.0.1
system.adapter.hue                     : hue            - v3.10.2
system.adapter.hue-extended            : hue-extended   - v2.0.0
system.adapter.icons-mfd-png           : icons-mfd-png  - v1.2.1
system.adapter.icons-mfd-svg           : icons-mfd-svg  - v1.2.0
system.adapter.icons-ultimate-png      : icons-ultimate-png - v1.0.1
system.adapter.influxdb                : influxdb       - v4.0.2
system.adapter.info                    : info           - v2.0.0
system.adapter.iqontrol                : iqontrol       - v2.1.0
system.adapter.javascript              : javascript     - v7.8.0
system.adapter.material                : material       - v1.3.1
system.adapter.modbus                  : modbus         - v6.1.0
system.adapter.mqtt                    : mqtt           - v5.2.0
system.adapter.mqtt-client             : mqtt-client    - v1.6.3
system.adapter.onvif                   : onvif          - v1.1.2
system.adapter.radar2                  : radar2         - v2.1.0
system.adapter.scheduler               : scheduler      - v1.1.9
system.adapter.schoolfree              : schoolfree     - v1.1.1
system.adapter.simple-api              : simple-api     - v2.7.2
system.adapter.slideshow               : slideshow      - v0.1.4
system.adapter.socketio                : socketio       - v6.6.0
system.adapter.solarwetter             : solarwetter    - v1.0.0
system.adapter.sonoff                  : sonoff         - v3.0.3
system.adapter.systeminfo              : systeminfo     - v1.1.0
system.adapter.telegram                : telegram       - v3.0.1
system.adapter.text2command            : text2command   - v3.0.3
system.adapter.time-switch             : time-switch    - v2.2.2
system.adapter.unifi                   : unifi          - v0.6.7
system.adapter.unifi-protect           : unifi-protect  - v0.0.13
system.adapter.vis                     : vis            - v1.5.4
system.adapter.vis-2                   : vis-2          - v2.9.32
system.adapter.vis-2-beta              : vis-2-beta     - v2.1.5
system.adapter.vis-2-widgets-energy    : vis-2-widgets-energy - v0.3.9
system.adapter.vis-2-widgets-gauges    : vis-2-widgets-gauges - v1.0.2
system.adapter.vis-2-widgets-material  : vis-2-widgets-material - v1.3.18
system.adapter.vis-colorpicker         : vis-colorpicker - v2.0.3
system.adapter.vis-google-fonts        : vis-google-fonts - v1.0.4
system.adapter.vis-history             : vis-history    - v1.0.0
system.adapter.vis-hqwidgets           : vis-hqwidgets  - v1.4.0
system.adapter.vis-icontwo             : vis-icontwo    - v1.3.0
system.adapter.vis-inventwo            : vis-inventwo   - v3.3.3
system.adapter.vis-jqui-mfd            : vis-jqui-mfd   - v1.0.12
system.adapter.vis-justgage            : vis-justgage   - v2.1.0
system.adapter.vis-lcars               : vis-lcars      - v1.1.1
system.adapter.vis-map                 : vis-map        - v1.0.5
system.adapter.vis-material            : vis-material   - v0.1.3
system.adapter.vis-material-advanced   : vis-material-advanced - v1.7.4
system.adapter.vis-metro               : vis-metro      - v1.2.0
system.adapter.vis-plumb               : vis-plumb      - v1.0.2
system.adapter.vis-timeandweather      : vis-timeandweather - v1.2.2
system.adapter.vis-weather             : vis-weather    - v2.5.9
system.adapter.web                     : web            - v6.2.3
system.adapter.whatsapp-cmb            : whatsapp-cmb   - v0.2.3
system.adapter.wireguard               : wireguard      - v1.3.1
system.adapter.ws                      : ws             - v2.5.10
system.adapter.yr                      : yr             - v5.3.0
system.adapter.zigbee                  : zigbee         - v1.10.1

**Comment by foxriver76** [comment]
Ohne Browser log bleibt es auch nur eine Vermutung

**Comment by HaraldGrhein** [comment]
Letzte Silly Log Meldung Web Adapter
web.0 2024-03-03 13:01:24.332	silly	redis psubscribe cfg.o.system.config
web.0 2024-03-03 13:01:24.245	debug	2024-03-03T12:01:24.245Z Request authenticate [system.user.admin]
web.0 2024-03-03 13:01:23.534	info	==> Connected system.user.admin from ::ffff:192.168.2.164

Keine Log Meldungen im VIS-2 Adapter. Sieht auf als wenn der nicht aufgerufen wird.

Problem tritt auch mit Beta Repository und Updates von WEB-Server 6.2.5, Web socket 2.5.11, Socket 6.6.1 und VIS-2 2.9.39 auf.

Beim direkten Aufruf über http://192.168.29.32:8082/vis-2/edit.html zeigt sich kurz wieder das kreiselnde iObroker Zeichen, dann weisser Screen.

**Comment by HaraldGrhein** [comment]
Browser Logs.  Ich lese mich ein wie das in Firefox geht und stelle die dann hier ein. Muss jetzt leider weg, wird vielleicht erst morgen klappen. Aber danke schon mal für die schnelle Reaktion! :-)

**Comment by HaraldGrhein** [comment]
[console-export-2024-3-3_13-30-53.txt](https://github.com/ioBroker/ioBroker.vis-2/files/14472939/console-export-2024-3-3_13-30-53.txt)
 Habe es doch noch hinbekommen. .-) Upload des Logs ab Bklick auf Vis 2 Editor

**Comment by HaraldGrhein** [comment]
Der Fehler liegt in meinen zwei VIS-2 Projekten. Sowie ich die Projekt Dateien vom Pfad /opt/iobroker/iobroker-data/files/vis-2.0/"projekt" auf einen neuen Server kopiere tritt dort der Fehler auch auf. 
Damit habe ich eindeutig den Fehler in den Projekten lokalisiert. Zum Glück habe ich noch ein altes Projekt auf dem Server und kenne den html Pfad zum direkten Aufruf. Über diesen bin ich dann wieder in die EDIT Funktion von VIS-2 gekommen. Dort dann meine zwei defekten Projekte erst exportiert, dann lokal gelöscht, dann wieder importiert und der Fehler war weg :-) Wow Glück gehabt. Das hat mich zwei Tage Arbeit und Frust gekostet. Aber mein Problem ist gelöst. Ich kann leider nicht sagen was in den Projekten den Fehler verursacht hat, weiss auch nicht wie ich es herausfinden kann. Aber falls Interesse besteht den Fehler zu beseitigen, die alten defekten Projekte habe ich noch und kann ich zur Verfügung stellen. Um den Fehler nachzustellen muss das Projektverzeichnis nur in den Pfad /opt/iobroker/iobroker-data/files/vis-2.0/ kopiert werden. Danke für die Bereitschaft zur Hilfe!
