### ISSUE TITLE
Anker-Element

### ISSUE THREAD

**Issue by StefanHild** [ioBroker/ioBroker.vis-2#309]
### No existing issues.

- [X] There is no existing issue for my request.

### Related problems

Besonders wenn sich sehr viele kleine Widgets dicht nebeneinander auf einer Seite befinden, sind die Anker-Elemente etwas störend.

### Description

Da man eine Seite meist eher nicht responsiv darstellen will, wäre es daher hilfreich, wenn man die Sichtbarkeit der Anker-Elemente  bei Bedarf aus- oder einschalten könnte.

**Comment by Feuer-sturm** [comment]
@StefanHild Klick Mal auf das Auge (siehe auch https://forum.iobroker.net/topic/71786/vis2-ab-morgen-im-stable/43?_=1705216079602)
