### ISSUE TITLE
[bug]: Attribut: Bildschirm begrenzen verschiebt Widget's

### ISSUE THREAD

**Issue by iAgrippa** [ioBroker/ioBroker.vis-2#312]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

die Anwahl "Seite>Optionen> Bildschirm begrenzen" nimmt nicht Positionen aller Widgets mit !

### To Reproduce

Siege GIF

### Expected behavior

 relative Positionen aller Widgets sollen erhalten bleiben 

### Screenshots & Logfiles

![Begrenzen](https://github.com/ioBroker/ioBroker.vis-2/assets/151877956/0155acdb-9db1-4d0e-a964-93fb24a3b24b)

### Adapter version

2.9.18

### js-controller version

 5.0.17

### Node version

v18.19.0

### Operating system

gängige Browser 

### Additional context

Vielen Dank !

**Comment by foxriver76** [comment]
https://github.com/ioBroker/ioBroker.vis-2/issues/234

**Comment by iAgrippa** [comment]
oh - vielen Dank !
