### ISSUE TITLE
Basic-Image Widget kaum erkennbar in edit mode

### ISSUE THREAD

**Issue by StefanHild** [ioBroker/ioBroker.vis-2#315]
### No existing issues.

- [X] There is no existing issue for my request.

### Related problems

Wenn man für ein Basic-Image Widget im Attribute Quelle eine Grafik auswählt, wird diese im Entwurfsmodus anschließend ausgegraut dargestellt. Erst zur Laufzeit wird die Grafik im Original mit allen Farben dargestellt.

![image](https://github.com/ioBroker/ioBroker.vis-2/assets/36371402/57ba716e-669e-4bb8-a81a-dbb1c62dc879)

DIes ist bisher im VIS 1 nicht so.

### Description

Gibt es hier eine Einstellmöglichkeit, oder ist dies im VIS 2 so gewollt?

**Comment by peoples0815** [comment]
Genau das gleiche Verhalten besteht bei dem Image8 Widget:
![enwurfsmodus (Mittel)](https://github.com/ioBroker/ioBroker.vis-2/assets/39387321/9321b948-3138-4167-a86d-56c19225feec)
![runtime (Mittel)](https://github.com/ioBroker/ioBroker.vis-2/assets/39387321/8ef9f9cf-f9bc-4168-852c-8dc9ae31489c)

**Comment by foxriver76** [comment]
Yes, a light grid should be applied, but there is an issue, that applies it two times leading to the fact, that you can barely see the image. Will be fixed in one of the next versions.

**Comment by peoples0815** [comment]
I Updated but still the same issue

**Comment by foxriver76** [comment]
Still that intensive or a much lighter overlay?

**Comment by peoples0815** [comment]
In basic image its lighter an image8 is the same like bevor, picture is here:
[https://github.com/ioBroker/ioBroker.vis-2/issues/324](url)
