### ISSUE TITLE
Widget Anzeigefehler

### ISSUE THREAD

**Issue by zaphod2** [ioBroker/ioBroker.vis-2#318]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Beim aktualisieren von 2.9.11 auf die 2.9.19 gibt es in der VIS-2 einen Widget Anzeigefehler. Gehe ich zurück auf die 2.9.11 ist es wieder gut.
Neu Installation des Adapters und Update nützt nichts, der Fehler bleibt solange ich die Version erhöhe.

### To Reproduce

aktualisieren von 2.9.11 auf die jeweils höhere Version

### Expected behavior

Widget Anzeigefehler

### Screenshots & Logfiles

![Screenshot 2024-01-17 193305](https://github.com/ioBroker/ioBroker.vis-2/assets/96678159/724d77cd-216c-4042-a792-cd7c3aebe2b6)

### Adapter version

2.9.19

### js-controller version

5.0.17

### Node version

18.19.0

### Operating system

Debian/Proxmox

**Comment by foxriver76** [comment]
Im privaten Modus auch? Sonst bitte Cache leeren. 

Und leider fehlt die Information um welche Widgets es sich habndelt oder ein Export.

**Comment by zaphod2** [comment]
Was für ein privater Modus?
Um welche Widgets es sich handelt weiß ich doch nicht, Wie man sieht ist die Anzeige dann eben so. Einen Export kann ich ja mal probieren.
Ich kann nicht sagen welche Widgets hier genau zu diesem Problem führen.

**Comment by zaphod2** [comment]
Exportiere ich das Projekt, lösche es  und gehe auf eine höhere Version und importiere ich das Projekt wieder bleibt es bei dem Fehler.
Das ist übrigens das Projekt aus Vis1 und ich mache das nicht nochmal neu.

**Comment by foxriver76** [comment]
> Was für ein privater Modus?

der des Browsers deines Vertrauens

**Comment by zaphod2** [comment]
Wüsste ich nicht wie man das im Kiosk (modus?) (Browsers?) einstellt und es funktioniert ja auf Anhieb mit der v 2.9.11

**Comment by zaphod2** [comment]
Ist das Zielführend?

![Screenshot 2024-01-18 165553](https://github.com/ioBroker/ioBroker.vis-2/assets/96678159/a8770bc0-13d3-45d2-92d3-dc22053bfba0)

**Comment by zaphod2** [comment]
Es geht im Inkognito Fenster bei Chrome, gibt es also irgendwo noch einen Fehler bei Chrome im normalen Modus.

**Comment by zaphod2** [comment]
Es war die Vis-Bars. Gelöscht, neue v 0.1.4 installiert und es geht wieder.

**Comment by zaphod2** [comment]
Lösche ich den Vis-Bars Adapter und installiere ich ihn neu ist wieder alles gut. Also irgendetwas ist da beim Update immer verbogen.

**Comment by foxriver76** [comment]
Schau mal ob in Zukunft statt reinstall auch ein Upload des Adapters hilft also `iob u vis-bars` oder wie der Adapter korrekt heißt. Wie aktualisierst du den vis 2 adapter?

**Comment by zaphod2** [comment]
Muss ich probieren dann mal. Aktualisieren tu ich ihn über die Katze und dann von NPM..

**Comment by foxriver76** [comment]
Ok ja dann brauchst du danach einen manuellen Upload. `iob u vis-2` oder auch im Admin wenn der Expertenmodus aktiv ist, ist dann aber nicht wirklich ein but von vis falls es das ist…

**Comment by zaphod2** [comment]
Nächstes Update und wieder Anzeigefehler. Mit `iob u vis-2` ging es dann, aber dann waren alle CSS Daten weg.

**Comment by zaphod2** [comment]
Update auf 2.9.24 und wieder Anzeigefehler. Wieder fast alle Widgets weg.
in den instanzen Vis-2 neu gestartet = keine Änderung
mit `iob u vis-2` in der Konsole = alles wieder okay
Und es sind alle CSS Daten weg.

**Comment by zaphod2** [comment]
Warum geht das nur erst wieder mit dem `iob u vis-2` ?

**Comment by Feuer-sturm** [comment]
@zaphod2 wie aktualisiert du vis-2 denn?

**Comment by foxriver76** [comment]
> Aktualisieren tu ich ihn über die Katze und dann von NPM..

Oben schrieb er das, was vermutlich nach wie vor zutrifft

**Comment by zaphod2** [comment]
![Screenshot 2024-02-07 163941](https://github.com/ioBroker/ioBroker.vis-2/assets/96678159/a40a0e10-be52-47af-ad6f-5a17c73c9ac2)

**Comment by foxriver76** [comment]
Wie bereits erwähnt, wenn du über den Adapter Tab normal updatest, was natürlich voraussetzt, dass du aktuell auf `beta` Repo unterwegs bist, wäre das nicht nötig, aber wenn über das Fenster geupdated wird, wird intern immer `iob url` ausgeführt, was danach einen separaten Upload braucht. Aber mach doch gerne mal ein Admin Issue, dass evtl nach der npm Geschichte der admin einen Upload triggert, da das ja aktuell der empfohlene Weg ist für einzelne Aadpter aus "beta" ziehen.

**Comment by zaphod2** [comment]
![Screenshot 2024-02-08 153105](https://github.com/ioBroker/ioBroker.vis-2/assets/96678159/f38e7f21-b303-43ae-a0ab-0978f5d293a9)

**Comment by Feuer-sturm** [comment]
@zaphod2 Was möchtest du mit dem Screenshot sagen. Du bist im stable unterwegs und hast einen Adapter via der NPM über den Admin installiert. 
Ich habe mal beim Adamin Adapter ein entsprechendes issues bzgl. des uploads angelegt: https://github.com/ioBroker/ioBroker.admin/issues/2356

**Comment by zaphod2** [comment]
Mit der 2.9.32 sind die Anzeigefehler weg.
