### ISSUE TITLE
vis2.x: "Basic Image"-widget, show real picture path

### ISSUE THREAD

**Issue by ice987987** [ioBroker/ioBroker.vis-2#32]
**Describe the bug**  
replace "placeholder/variable" under "Allgemein" -> Quelle with real path

**To Reproduce**  
select a picture under "Quelle"

**Expected behavior**  
show real picture path instead of `_PRJ_NAME/`

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/69053781/205313774-f79ce108-ce82-446d-8747-acfdd5a0fd10.png)

**Versions:**  
- Adapter version: ioBroker.vis v2.0.10
- JS-Controller version: v4.0.23
- Node version: v16.18.1
- Operating system: ioBroker.docker v7.2.1
- Browser: Google Chrome v108.0.5359.72 (Offizieller Build) (64-Bit)

**Comment by Feuer-sturm** [comment]
@ice987987 issue is fixed in vis-2 version 2.2.2
This is how it looks with v2.2.2
![grafik](https://github.com/ioBroker/ioBroker.vis-2/assets/25422320/475f1d12-88c4-4df1-b1d6-57dc8b50c8a5)
