### ISSUE TITLE
[bug]: Image 8 - Opacity immer noch fehlerhaft trotz commit.

### ISSUE THREAD

**Issue by peoples0815** [ioBroker/ioBroker.vis-2#324]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Trotz des Updates auf 2.9.21 besteht das Opacity Issue von hier immernoch:
[https://github.com/ioBroker/ioBroker.vis-2/issues/315]([https://github.com/ioBroker/ioBroker.vis-2/issues/315](https://github.com/ioBroker/ioBroker.vis-2/issues/)

Bei Mouseover über das Basic Image, wird das Bild richtig angezeigt, beim image 8 ändert sich nichts

Die Unterschiede sieht man im Bild
![entwurf](https://github.com/ioBroker/ioBroker.vis-2/assets/39387321/16d47dbc-ba75-42a8-8276-004db051858e)

### To Reproduce

Image 8 oder Basic Widget im Editor einfügen dann stimmt die Opacity nicht

### Expected behavior

Ein aussehen wie folgt
![runtime (Mittel)](https://github.com/ioBroker/ioBroker.vis-2/assets/39387321/0e6881f5-7d04-4543-a70b-3e047f9c062d)

### Screenshots & Logfiles

siehe oben.

### Adapter version

2.9.21

### js-controller version

5.0.17

### Node version

18.19.0

### Operating system

debian

**Comment by foxriver76** [comment]
Kannst du mir das Widget mal exportieren bitte. Das Bild wird ja gar nicht angezeigt.

**Comment by peoples0815** [comment]
Bitteschön:

`[
  {
    "tpl": "tplImage",
    "data": {
      "bindings": [],
      "refreshInterval": 0,
      "g_common": true,
      "src": "_PRJ_NAME/images/buttons/weather/wind.png",
      "name": "Symbol Wind"
    },
    "style": {
      "bindings": [],
      "left": 993,
      "top": 793,
      "width": "80px",
      "height": 80,
      "z-index": 3
    },
    "widgetSet": "basic",
    "_id": "i000001"
  },
  {
    "tpl": "tplStatefulImage8",
    "data": {
      "bindings": [],
      "oid": "javascript.0.Abfallkalender.Abfall_heute",
      "refreshInterval": 1000,
      "g_common": true,
      "count": 14,
      "src_0": "_PRJ_NAME/images/buttons/trash/state_0.png",
      "src_1": "_PRJ_NAME/images/buttons/trash/state_1.png",
      "g_images": true,
      "src_5": "_PRJ_NAME/images/buttons/trash/state_5.png",
      "src_8": "_PRJ_NAME/images/buttons/trash/state_8.png",
      "src_23": "_PRJ_NAME/images/buttons/vacuum_cleaner/vacuum_cleaner_mop_cleaning.png",
      "src_2": "_PRJ_NAME/images/buttons/trash/state_0.png",
      "src_26": "_PRJ_NAME/images/buttons/vacuum_cleaner/vacuum_cleaner_mop_cleaning.png",
      "src_12": "_PRJ_NAME/images/buttons/trash/state_12.png",
      "src_9": "_PRJ_NAME/images/buttons/trash/state_9.png",
      "src_6": "_PRJ_NAME/images/buttons/trash/state_6.png",
      "src_15": "_PRJ_NAME/images/buttons/vacuum_cleaner/vacuum_cleaner_homeing.png",
      "src_3": "_PRJ_NAME/images/buttons/trash/state_3.png",
      "src_4": "_PRJ_NAME/images/buttons/trash/state_4.png",
      "src_7": "_PRJ_NAME/images/buttons/trash/state_0.png",
      "src_10": "_PRJ_NAME/images/buttons/trash/state_10.png",
      "src_11": "_PRJ_NAME/images/buttons/trash/state_0.png",
      "src_13": "_PRJ_NAME/images/buttons/trash/state_0.png",
      "src_14": "_PRJ_NAME/images/buttons/trash/state_14.png",
      "src_16": "_PRJ_NAME/images/buttons/vacuum_cleaner/vacuum_cleaner_default.png",
      "src_17": "_PRJ_NAME/images/buttons/vacuum_cleaner/vacuum_cleaner_default.png",
      "src_18": "_PRJ_NAME/images/buttons/vacuum_cleaner/vacuum_cleaner_default.png",
      "src_19": "_PRJ_NAME/images/buttons/vacuum_cleaner/vacuum_cleaner_default.png",
      "src_20": "_PRJ_NAME/images/buttons/vacuum_cleaner/vacuum_cleaner_default.png",
      "src_21": "_PRJ_NAME/images/buttons/vacuum_cleaner/vacuum_cleaner_default.png",
      "src_22": "_PRJ_NAME/images/buttons/vacuum_cleaner/vacuum_cleaner_default.png",
      "src_24": "_PRJ_NAME/images/buttons/vacuum_cleaner/vacuum_cleaner_default.png",
      "src_25": "_PRJ_NAME/images/buttons/vacuum_cleaner/vacuum_cleaner_default.png",
      "src_27": "_PRJ_NAME/images/buttons/vacuum_cleaner/vacuum_cleaner_default.png",
      "src_28": "_PRJ_NAME/images/buttons/vacuum_cleaner/vacuum_cleaner_default.png",
      "src_29": "_PRJ_NAME/images/buttons/vacuum_cleaner/vacuum_cleaner_default.png",
      "src_30": "_PRJ_NAME/images/buttons/vacuum_cleaner/vacuum_cleaner_default.png",
      "name": "Symbol Abfall",
      "comment": null,
      "class": null,
      "filterkey": null,
      "multi-views": null,
      "locked": null,
      "g_fixed": true
    },
    "style": {
      "bindings": [],
      "left": 1494,
      "top": 793,
      "width": "80",
      "height": "80",
      "z-index": "3"
    },
    "widgetSet": "basic",
    "_id": "i000002"
  }
]`

**Comment by foxriver76** [comment]
Wenn man `overflow-x` sichtbar macht, sieht man, dass das Bild im Edit Mode irgendwie darunter liegt..
