### ISSUE TITLE
[bug]: V2.9.21: Editor und Runtime crasht komplett

### ISSUE THREAD

**Issue by MK-66** [ioBroker/ioBroker.vis-2#326]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Mit der neuen Version V2.9.21 crasht bei mir der Editor und die Runtime komplett. Die Seiten meines Projektes werden nicht angezeigt, weder im Editor noch in der Runtime. 

### To Reproduce

Eine andere Seite in meinem Projekt auswählen geht auch nicht, da der Browser hängt und nicht mehr reagiert. Die Browserauslastung im Windows Taskmanager ist hoch und ich kann nicht mal mehr mit F12 in der Konsole nachsehen, welche Fehlermeldungen es geben könnte. Im ioBroker Log ist nichts zu sehen.

Browsercache löschen bringt leider auch nichts, ebenso wenig wie ein zusätzlicher Upload des Adapters oder ein erneutes Upgrade auf 2.9.21 nach Downgrade auf 2.9.20.

Zurück zu V2.9.20 und alles geht wieder. 

### Expected behavior

Kein Crash.

### Screenshots & Logfiles

-

### Adapter version

2.9.21

### js-controller version

5.0.17

### Node version

18.19.0

### Operating system

Debian 12

**Comment by Feuer-sturm** [comment]
@MK-66 War es ein reines VIS-2 Projekt was geladen wurde? Mit welchem Browser tritt bei dir der Fehler auf? Hast du einmal versucht einen anderen Browser zu verwenden?

**Comment by MK-66** [comment]
@Feuer-sturm: Es war ein importiertes vis-1 Projekt, dass ich bereits seit längerem an vis-2 Stück für Stück angepasst habe und mit dem ich derzeit vis-2 ausprobiere. Bis zur V2.9.20 läuft dieses Projekt tadellos, erst mit 2.9.21 crasht und hängt der Editor sowie die runtime. Bei allen getesteten Browsern Chrome, Edge und Firefox das gleiche Problem.

**Comment by peoples0815** [comment]
Das wird an dem importierten Projekt liegen. Hast du mal versucht von Beginn an eine andere Seite deines Projekts zu laden und nicht den Standard

**Comment by MK-66** [comment]
Ja, ich habe versucht eine andere Seite zu öffnen, das geht teilweise auch. Ich nutze in meinem Projekt allerdings sehr viele „View Im Widgets“, sobald Seiten mit einem View Im Widget dann dargestellt/aufgerufen werden, wird die Seite zum Einen nicht richtig dargestellt und zum anderen friert der Editor komplett ein.

Wie gesagt, das Projekt nutze ich in vis-2 jetzt schon recht lange und bis einschließlich V2.9.20 funktioniert das Projekt tadellos und fehlerfrei.

Erst nach Update V2.9.21 funktioniert das Projekt nicht mehr und der Editor sowie die Runtime frieren komplett ein. Irgendetwas muss in V2.9.21 geändert worden sein, dass diese Probleme auslöst.

**Comment by foxriver76** [comment]
bitte mit 2.9.22 probieren
