### ISSUE TITLE
Control Datapoints not working properly and no Data about Batterystatus

### ISSUE THREAD

**Issue by FlexerJR** [ioBroker/ioBroker.vis-2#331]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Hallo und schönen guten Tag,

früher habe ich mit Vis 1 die Seiten über Blockly, gesteuert. Das hat auch ohne Delay funktioniert.

![image](https://github.com/ioBroker/ioBroker.vis-2/assets/40354380/510c2d69-9931-48d6-bfde-2f17355b6d3d)

Leider funktioniert das mit VIS2 nicht richtig. Teilweiße ist eine Verzögerung von bis zu 1 Minute vorhanden. 

Des Weiteren ist mir aufgefallen, dass es keinen Datenpunkt mehr für die Batterieanzeige gibt. 

Leider kann ich so meine VIS nicht nutzen und bin auf VIS1 zurück gewechselt.

Viele Grüße

### To Reproduce

vis-2.0.control.command

### Expected behavior

Working without delay

### Screenshots & Logfiles

Shown above

### Adapter version

2.9.22

### js-controller version

5.0.17

### Node version

18.17.1

### Operating system

Ubuntu

**Comment by seb2010** [comment]
Ich habe dasselbe Problem. Die Steuerung der Instanzen per control-command funktioniert nicht mehr oder ggf. anders mit unbekannter Syntax.
Egal was ich sende, es kommt irgendwie nicht an (auf eine starke Verzögerung, wie oben beschrieben mit bis zu 1ner Minute, habe ich noch nicht getestet). Ich sende dann bspw. den folgenden Command, indem ich "vis-2.0.control.command" auf "{'instance': '99.209df', 'command': 'reload', 'data': ''}" setze. Doch es passiert einfach nichts. Weder reload, noch changeView noch playSound.

Das Problem besteht sowohl auf Android Endgeräten mit Fully Browser als auch auf dem PC in Chrome. Mit Vis (ohne 2) funktionierte das...

**Comment by foxriver76** [comment]
Battery State kommt meines Wissens nie von vis selbst, kommt also darauf an welche App du da nutzt.

**Comment by foxriver76** [comment]
> Ich habe dasselbe Problem. Die Steuerung der Instanzen per control-command funktioniert nicht mehr oder ggf. anders mit unbekannter Syntax. Egal was ich sende, es kommt irgendwie nicht an (auf eine starke Verzögerung, wie oben beschrieben mit bis zu 1ner Minute, habe ich noch nicht getestet). Ich sende dann bspw. den folgenden Command, indem ich "vis-2.0.control.command" auf "{'instance': '99.209df', 'command': 'reload', 'data': ''}" setze. Doch es passiert einfach nichts. Weder reload, noch changeView noch playSound.
> 
> Das Problem besteht sowohl auf Android Endgeräten mit Fully Browser als auch auf dem PC in Chrome. Mit Vis (ohne 2) funktionierte das...

Funktioniert bei mir problemfrei mit validem JSON: `{"instance": "5.9ecc48", "command": "reload", "data": ""}`, man beachte die `"` vs `'`, weiß nicht ob vis-1 das trotzdem geparsed hat

**Comment by foxriver76** [comment]
Auch das initiale Beispiel läuft bei mir korrekt. Nachgestellt mit

```
setState('vis-2.0.control.instance', '5.9ecc48');
setState('vis-2.0.control.data', 'main/Neue Seite');
setState('vis-2.0.control.command', 'changeView');
```

**Comment by seb2010** [comment]
Ich sehe ab und an Alarm messages im log, das die Datenpunkte vis-2.4.control.data usw. nicht existieren würden. Das wunderliche daran ist, dass es gar keine Instanz 4 gibt. Es gibt nur die Instanz 0. Ggf. hängt es irgendwie damit zusammen. Auch scheint die View auf die falsche Instanz subscriben zu wollen:
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/57917445/1cab1b4c-2381-481e-9eab-9cd182c8e0b5)

**Comment by foxriver76** [comment]
Hm okay, das wäre naheliegend dass da was zusammenhängt. Evtl. waren bei Flexer auch derartige Meldungen? Muss ich mal schauen wie er seine Instanz feststellt.

**Comment by foxriver76** [comment]
ich glaube es ist nur der Code, der die Instanz feststellt: https://github.com/ioBroker/adapter-react-v5/blob/bae98e05d9d0df4443b59bda6b7ac08f3135bf4f/src/GenericApp.js#L139

Zeig mal bitte die URL von deinem Projekt.

**Comment by seb2010** [comment]
http://sjserver01:8082/vis-2/?4inch#Übersicht1
