### ISSUE TITLE
[bug]: reactivity problem mit v2.9.22

### ISSUE THREAD

**Issue by Steiger04** [ioBroker/ioBroker.vis-2#332]
### No existing issues.

- [ ] There is no existing issue for my problem.

### Describe the bug

Das [alte Problem](https://github.com/ioBroker/ioBroker.vis-2/issues/202) der fehlenden Reactivity ist wieder vorhanden. Zusätzlich lässt sich die Größe der Widgets in der GUI nicht mehr ändern.

### To Reproduce

 s.o.

### Expected behavior

 s.o.

### Screenshots & Logfiles

 s.o.

### Adapter version

 v2.9.22

### js-controller version

 v5.0.17

### Node version

 v18.18.2

### Operating system

 win11

**Comment by foxriver76** [comment]
weißt du bist zu welcher version es korrekt ging?

**Comment by Steiger04** [comment]
Die Änderung der Größe via GUI (Widget anklicken und größer ziehen) geht ab v2.9.13 nicht mehr (nicht nur bei meinen Widgets, sondern z.B. auch bei den Messgeräte-Widgets).

![image](https://github.com/ioBroker/ioBroker.vis-2/assets/17086944/4c4ad3a1-187c-4db2-a34c-fa299103fad9)

 Die Reactivity ist mit der aktuellen v2.9.22 verloren gegangen. Ich hoffe das hilft. Falls ich noch was tun kann, dann einfach melden.

**Comment by foxriver76** [comment]
Bitte testen mit 2.9.23

**Comment by Steiger04** [comment]
@foxriver76 Jetzt bekomme ich in der Palette keine installierten Widgets mehr angezeigt.

![image](https://github.com/ioBroker/ioBroker.vis-2/assets/17086944/818c06ad-adc1-4b36-a0ef-3000460c6a30)

Ich habe die Instanzen der Widgets dann gelöscht und noch einmal angelegt und auch vis-2 wiederholt neu gestartet, leider kein Effekt. Irgendwo gehen bei der v2.9.23 die installierten Widgets verloren.

**Comment by foxriver76** [comment]
Weiß nicht, da hat sich absolut nix geändert .. Wenn du über Katze installierst, braucht es nen Upload.

**Comment by Steiger04** [comment]
@foxriver76 Ich habe über Katze und dann npm installiert. Bisher war da nie ein upload erforderlich. Der Fehler ist auch reproduzierbar. Wenn ich wieder auf die v2.9.22 zurückgehe (via npm), dann sind alle Widgets sofort wieder da, aber das oben beschriebene Fehlerbild eben auch. Hast Du das bei Dir nicht nachvollziehen können?

**Comment by Steiger04** [comment]
Mhm....irgendwie komisch. Habe jetzt auf der console ein `iobroker upload vis-2` durchgeführt. Jetzt sind die Widgets tatsächlich da, aber wenn ich über die Katze npm ausführe bekomme ich im Debug-Fenster folgende Ausgabe:

![image](https://github.com/ioBroker/ioBroker.vis-2/assets/17086944/1daacf3f-4b3c-4121-a065-12da894d8e7d)

Bei allen anderen Updates von vis-2 via Katze/npm hat immer alles funktioniert. Hast Du eine Idee warum das so ist?

Test-Ergebnis für v2.9.23: Reactivity ist wieder da, aber Größenänderung der Widgets funktioniert nicht.

**Comment by foxriver76** [comment]
Kannst du für die Größenänderung ein extra Ticket erstellen bitte, mit Info seit wann kaputt und einem Widget im besten Fall mit dem ich es nachstellen kann? 

Bzgl. dem Upload, weiß ich gerade nicht, der vis Adapter hat da selbst keinen großen Einfluss drauf, aber soweit ich mich erinnere wird bei Installationen mit `iob url` installs der finale Upload weg gelassen, da ursprünglich für Tests gedacht. Ob das noch aktuell ist alles kann ich gerade nicht sicher sagen und auch nicht warum es wohl in der Vergangenheit funktioniert hat, der Adapter selbst hat da keinen großen Einfluss drauf was beim upload passiert außer ob alte files erased werden oder nicht.
