### ISSUE TITLE
[bug]:  Größe der Widgets läßt sich ab v2.9.13 nicht mehr ändern

### ISSUE THREAD

**Issue by Steiger04** [ioBroker/ioBroker.vis-2#334]
### No existing issues.

- [x] There is no existing issue for my problem.

### Describe the bug

@foxriver76  Die Änderung der Größe via GUI (Widget anklicken und größer ziehen) geht ab v2.9.13 nicht mehr (nicht nur bei meinen Widgets, sondern z.B. auch bei den Messgeräte-Widgets).

![image](https://github.com/ioBroker/ioBroker.vis-2/assets/17086944/4c4ad3a1-187c-4db2-a34c-fa299103fad9)

### To Reproduce

s.o.

### Expected behavior

s.o.

### Screenshots & Logfiles

s.o.

### Adapter version

v2.9.23

### js-controller version

v5.0.17

### Node version

v18

### Operating system

win11

**Comment by foxriver76** [comment]
Kann ich nicht nachstellen

[Bildschirmaufzeichnung vom 24.01.2024, 14:12:22.webm](https://github.com/ioBroker/ioBroker.vis-2/assets/25484431/8d4ae3d2-ee59-475a-8154-8d43ed2a41bf)

**Comment by Steiger04** [comment]
@foxriver76 wenn Du das Widgets auf die Seite ziehst, dann lass die CSS-Einstellungen einmal so wie sie im Standard sind, also nicht position auf none, sondern relative (s. Bild)

![image](https://github.com/ioBroker/ioBroker.vis-2/assets/17086944/4967c3d2-8112-4ea6-ae4d-f7d75980dc89)

 und versuche dann mal die Höhe des Widgets zu ändern (gestrichelte untere blaue Linie). Das geht nicht. Wenn Du so wie Du es getan hast erst die position änderst und dann die größe anpasst, dann geht das, aber eben nicht mit position relative.

**Comment by foxriver76** [comment]
Erstes kann ich nachstellen. Letzteres speichert er bei mir korrekt ab

**Comment by Steiger04** [comment]
@foxriver76 Ich habe jetzt mal vis-2 komplett deinstalliert und wieder installiert (v2.9.23). Der Paletten-Effekt ist immer noch da.

![palette springt zurück](https://github.com/ioBroker/ioBroker.vis-2/assets/17086944/8bed77ab-fb3b-4b29-9962-5d149e636df0)

**Comment by foxriver76** [comment]
kanns weder in chrome noch FF nachstellen für das Problem des Issues habe ich einen Fix

**Comment by Steiger04** [comment]
@foxriver76 Das scheint wirklich ein Browser-Problem zu seien. Chrome und FF gehen bei mir auch. Ich nutze aber bei mir Opera produktiv und da passiert der Effekt.

**Comment by Steiger04** [comment]
@foxriver76 Habe es gerade in Chrome mit der v2.9.24 probiert. Fehler ist immer noch da.

![widget position relative](https://github.com/ioBroker/ioBroker.vis-2/assets/17086944/cf294046-9fd3-4f9b-87a6-436cbca896a5)

**Comment by foxriver76** [comment]
nene der fix ist da auch nicht drin ;-)

https://github.com/ioBroker/ioBroker.vis-2/pull/338

**Comment by Steiger04** [comment]
@foxriver76 ich werde alt . . .

**Comment by Steiger04** [comment]
@foxriver76  Mit v2.9.25 funktioniert jetzt die Reactivity und die Größenänderung der Widgets wieder. Perfekt! Das Zurückschnappen der Palette mit Opera ist noch da. Da musst Du irgendetwas geändert haben.
