### ISSUE TITLE
[bug]: Crash bei Anwahl "Sichtbarkeit-Nur für Gruppen"

### ISSUE THREAD

**Issue by iAgrippa** [ioBroker/ioBroker.vis-2#341]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

bei Auswahl eines Kontrollkästchen stürzt Editor ab.

![image](https://github.com/ioBroker/ioBroker.vis-2/assets/151877956/5a943f16-52ff-4859-87f4-e3e3c0385273)

### To Reproduce

Widget selektieren und Gruppe auswählen.

### Expected behavior

na

### Screenshots & Logfiles

![image](https://github.com/ioBroker/ioBroker.vis-2/assets/151877956/4208058c-2d88-479f-aab0-070a4f257fbe)

### Adapter version

2.9.23

### js-controller version

5.0.17

### Node version

v18.19.0

### Operating system

Edge Firefox Chrome

### Additional context

vielen Dank !

**Comment by iAgrippa** [comment]
v2.9.24 gleichen Verhalten :-)

**Comment by Feuer-sturm** [comment]
ist i.O mit 2.9.25 :-)

**Comment by iAgrippa** [comment]
ja danke euch ! :-)
