### ISSUE TITLE
[enhancement]: jqui Dialoge haben immer einen weißen Hintergrund 

### ISSUE THREAD

**Issue by seb2010** [ioBroker/ioBroker.vis-2#342]
### No existing issues.

- [X] There is no existing issue for my request.

### Related problems

Wenn ich einen Dialog in der Vis per "gestylt->zu URL springen" einbaue, kann ich die Hintergrund-Farbe des Dialog-Divs nicht setzen. Jedenfalls finde ich die Option dazu nicht.
Die Hintergrund-Farbe ist in der anzuzeigenden View gesetzt und auch im HTML-Code enthalten. Sie greift allerdings nicht. Wenn ich eine custom dialog_class setze und dort per css dann den background einstelle, sind die Ränder des weißen Dialogs allerdings noch viel zu prominent. Voranstellen von html wirkt sich auch nur auf den Button zum Öffnen des Dialogs aus und nicht auf den Dialog selbst.

### Description

Es muss Parameter geben, mit denen man den Style des anzuzeigenden Dialogs steuern kann.

**Comment by foxriver76** [comment]
Um welchen Dialog geht es? Der Passwort Dialog? Bzw kannst du mir das Widget evtl exportieren?

**Comment by seb2010** [comment]
Es ist ein tplJquiButtonLink. Ich habe es aktuell provisorisch mit einer css-Klasse "sebtest" gelöst, die man dort mitgeben kann...

[
  {
    "tpl": "tplJquiButtonLink",
    "data": {
      "bindings": [],
      "buttontext": "",
      "g_common": true,
      "html": "<center><img style=\"position:relative;top:15px\" src=\"/vis-2.0/main/img/Vacuum_robot.png\" width=\"60\"></center><img style=\"position:absolute;top:0px;right:0px\" src=\"/vis-2.0/main/img/baseline_keyboard_arrow_down_white_48dp.png\" width=\"30\">",
      "padding": 5,
      "g_style": true,
      "variant": "standard",
      "color": "",
      "visResizable": true,
      "imageHeight": 100,
      "g_icon": true,
      "modal": true,
      "g_dialog": true,
      "href": null,
      "url": null,
      "target": null,
      "g_URL": true,
      "html_dialog": "",
      "g_css_background": true,
      "g_css_border": true,
      "contains_view": "Vacuum",
      "dialog_width": "870",
      "dialog_height": "530",
      "preload": true,
      "title": "Vacuum",
      "dialog_class": "sebtest",
      "jquery_style": false,
      "no_style": false,
      "html_prepend": "",
      "overflowX": "hidden",
      "overflowY": "hidden"
    },
    "style": {
      "bindings": [],
      "left": 921,
      "top": 706,
      "width": "94",
      "height": "90",
      "background-color": "#424242",
      "border-radius": "10px"
    },
    "widgetSet": "jqui",
    "_id": "i000001"
  }
]
