### ISSUE TITLE
[enhancement]: boolean Widget korrespondiert nicht mit Bindings 

### ISSUE THREAD

**Issue by iAgrippa** [ioBroker/ioBroker.vis-2#346]
### No existing issues.

- [X] There is no existing issue for my request.

### Related problems

In einem BOOL-Html Widget werden mittels Bindings mehrere Datenpunkte logisch "oder" geprüft.

{ v1:0_userdata.0.test.b1;  v2:0_userdata.0.test.b2;  v3:0_userdata.0.test.b3;  v4:0_userdata.0.test.b4;  v1||v2||v3||v4 }

Errechnet wird wie erwartet **TRUE** bzw. **FALSE**.  

![image](https://github.com/ioBroker/ioBroker.vis-2/assets/151877956/6df10cf3-c28f-4c39-a7fa-67164dcec47a)

Allerdings reagiert das BOOL-Html Widget nicht auf das Ergebnis.

`[
  {
    "tpl": "tplValueBoolCtrl",
    "data": {
      "bindings": [
        "oid"
      ],
      "oid": "{w1:0_userdata.0.test.b1;w2:0_userdata.0.test.b2;w3:0_userdata.0.test.b3;w4:0_userdata.0.test.b4;w1||w2||w3||w4}",
      "html_false": "<span style=\"color: #0000FF\">BLAU",
      "html_true": "<span style=\"color: #FF0000\">ROT"
    },
    "style": {
      "bindings": [],
      "left": 406,
      "top": 172,
      "width": "81px",
      "height": "30px"
    },
    "widgetSet": "basic",
    "_id": "i000001"
  }
]`

Ich bin mir unsicher ob hier ein Bug vorliegt (in VIS1 geht es auch nicht! ) deshalb setzte ich hier ein "enhancement".

### Description

ich denke es würde die Sache hier und da vereinfachen wenn das umgesetzt ist.

**Comment by foxriver76** [comment]
see https://github.com/ioBroker/ioBroker.vis-2#special-bindings

So it can only be used in the js part according to the docs, which means something like this would work `{t:1;widget.data.oid}`

**Comment by foxriver76** [comment]
hm verstehe ich nicht, du trägst damit je nach kalkulation in die object id `true` oder `false` ein, was soll das bezwecken?

**Comment by foxriver76** [comment]
ich denke hier liegt ein logischer Fehler im Gedankengang vor, wenn du unterschiedliche Dinge anzeigen möchtest abhängig von dem Binding, nimm dir doch ein normales HTML Widget und arbeite da mit dem Binding fertig.

So was in die Richtung: 
```
[
  {
    "tpl": "tplHtml",
    "data": {
      "bindings": [
        "html"
      ],
      "html": "{w1:0_userdata.0.test.b1;w2:0_userdata.0.test.b2;w3:0_userdata.0.test.b3;w4:0_userdata.0.test.b4;w1||w2||w3||w4 ? '<span style=\"color: #0000FF\">BLAU</span>' : '<span style=\"color: #FF0000\">ROT</span>'}",
      "refreshInterval": null,
      "g_common": true
    },
    "style": {
      "bindings": [],
      "left": 334,
      "top": 260,
      "width": 200,
      "height": 130
    },
    "widgetSet": "basic",
    "_id": "i000001"
  }
]
``

**Comment by iAgrippa** [comment]
> ich denke hier liegt ein logischer Fehler im Gedankengang vor

oh ja,  du hast natürlich recht! 
>du trägst damit je nach kalkulation in die **object id** true oder false ein, was soll das ....

das war der Wecker :-)
