### ISSUE TITLE
[enhancement]: Menü automatisch zuklappen

### ISSUE THREAD

**Issue by micklafisch** [ioBroker/ioBroker.vis-2#348]
### No existing issues.

- [X] There is no existing issue for my request.

### Related problems

Das Menü welches in vis2 erstellt wird kann manuell auf- und muss auch manuell zugeklappt werden. 

### Description

Ein automatischens zuklappen nach der Wahl des Menüeintrags wie in Scroungers Material Design wäre wünschenswert

**Comment by micklafisch** [comment]
und wie wird das jetzt angewendet? 

Adapter ist aktuell, upload nochmals durchgeführt, Cache geleert, keine Option sichtbar:

![image](https://github.com/ioBroker/ioBroker.vis-2/assets/44931749/fb9e7d2b-53f1-4b96-b17d-15ba77bbcf61)
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/44931749/3d1867f0-d6df-4e13-a4cb-89d5a34a95c1)

**Comment by foxriver76** [comment]
Laut dem GitHub Symbol hast du die Version nicht auf dem normalen Wege installiert. Schieb mal ein Upload hinterher, 
Bei mir 2.9.28 normal installiert, Option "Nach Auswahl ausblenden".

![grafik](https://github.com/ioBroker/ioBroker.vis-2/assets/25484431/e97034ca-95a7-4e54-8aeb-5a077383a9fb)

**Comment by micklafisch** [comment]
upload hatte ich schon 2x durchgeführt bevor ich geschrieben habe. Habe jetzt den kompletten Adapter gelöscht und neu über die GUI installiert. Jetzt ist der Punkt da. Danke!
