### ISSUE TITLE
VIS2.x: Editor zeigt seltsame Angaben beim einfügen von <Vis 2 - Basic - View im Widget>

### ISSUE THREAD

**Issue by Haifeif** [ioBroker/ioBroker.vis-2#35]
Widget eingefügt, folgendes Property für <links> wird angezeigt:
![image](https://user-images.githubusercontent.com/59795191/204814328-cbe9055c-33f8-4165-97fd-2df87d0370fa.png)

**Comment by Feuer-sturm** [comment]
@Haifeif with vis-2 version 2.2.2 it looks ok
![grafik](https://github.com/ioBroker/ioBroker.vis-2/assets/25422320/7c662c1d-523b-4b39-84eb-54eef3f5f3d4)
