### ISSUE TITLE
[bug]: Editor Theme should not influence Navigation (as it is like a Widget - runtime related)

### ISSUE THREAD

**Issue by eisbaer721** [ioBroker/ioBroker.vis-2#352]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Beim betätigen des Farbthemenauswahl ändert sich die Farbe im Editorbereich.
Die Runtimes-Ausgaben sind auch unterschiedlich bei geänderten Farben im Navigationsbereich.
 

### To Reproduce

![Screenshot 2024-02-03 143014](https://github.com/ioBroker/ioBroker.vis-2/assets/46114394/d07a3650-d0f7-458b-b28c-52f802acf41b)

dunker Hintergrund:

![Screenshot 2024-02-03 143435](https://github.com/ioBroker/ioBroker.vis-2/assets/46114394/1c24a54b-27f2-4dd2-bb60-d4d35450ace5)

heller Hintergrund:

![Screenshot 2024-02-03 143607](https://github.com/ioBroker/ioBroker.vis-2/assets/46114394/536e99a3-2ffc-4a11-aef9-a981bf2f32eb)

Stellt man auch die Runtime im Editor auf aktiv sieht man die Icons die nicht aktiv sind (Seite1) nicht mehr.
Siehe:  

![Screenshot 2024-02-03 144234](https://github.com/ioBroker/ioBroker.vis-2/assets/46114394/52093b51-49ed-4286-985c-61e67cbfc32e)

Wieder da:

![Screenshot 2024-02-03 144402](https://github.com/ioBroker/ioBroker.vis-2/assets/46114394/bc07545e-8fdc-44ae-8960-fd15c40fd090)

### Expected behavior

Farben im Editor und in der Runtime sollten auf allen Geräten  (PC, Tablet, gleich sein egal welche Farbthemenauswahl man im Menü eingestellt hat. Dieses sollte nur das Vis-2 Editormenü betreffen.

Am besten sollten sogar die Symbole und die Schrift im Navigationsmenü einstellbar sein. 
(Größe, Farbe (aktiv abgewählt oder inaktiv),Schrift (aktiv angewählt oder inaktiv).

### Screenshots & Logfiles

Testprojekt:

`{
  "___settings": {
    "folders": [],
    "openedViews": [
      "default",
      "Seite 1"
    ],
    "ts": "1706965524735.uwt305"
  },
  "default": {
    "name": "Default",
    "settings": {
      "style": {
        "background-color": "black"
      },
      "theme": "",
      "navigation": true,
      "navigationBackground": "black"
    },
    "widgets": {},
    "activeWidgets": {}
  },
  "Seite 1": {
    "name": "Seite 1",
    "parentId": null,
    "settings": {
      "style": {
        "background-color": "black"
      },
      "navigation": true,
      "navigationBackground": "black"
    },
    "widgets": {},
    "activeWidgets": {}
  }
}`

### Adapter version

2.9.26

### js-controller version

5.0.19

### Node version

18.19.0

### Operating system

debian

**Comment by eisbaer721** [comment]
Ja.  Das stimmt.

**Comment by foxriver76** [comment]
Hm also wäre Ziel hier generell - kein Einfluss von theme auf runtime wie du oben auch schon geschrieben hast

**Comment by eisbaer721** [comment]
Das finde ich auch.

**Comment by foxriver76** [comment]
die Navigation wird in der nächsten Version voll konfigurierbar sein was Farben betrifft, als Fallback habe ich das aktuelle Verhalten gelassen, falls jemand speziell damit arbeitet, da da wohl auch einiges an Arbeit rein ging von BF damals.

**Comment by eisbaer721** [comment]
Ich habe es gerade kurz getestet.   Die Auswahl die dazu gekommen ist klappt wunderbar.
Nur leider fehlt noch der Kopfzeilentext.  "Kopfzeilentext des Menüs"
Auf mein Tablet ist leider bei den Einstellungen diese noch schwarz. 
Vielen Dank

![Screenshot 2024-02-06 162120](https://github.com/ioBroker/ioBroker.vis-2/assets/46114394/110c85fa-317a-4dd1-be3b-86589638836f)
![Screenshot 2024-02-06 162211](https://github.com/ioBroker/ioBroker.vis-2/assets/46114394/aad09b99-d13b-4a1c-baee-1771a01a88b5)

**Comment by foxriver76** [comment]
Ah Mist da hatte ich wohl keinen ausgewählt
