### ISSUE TITLE
[bug]: Image8 - zeigt den Auswahlbildpfad für Wert: 0 nicht mehr an

### ISSUE THREAD

**Issue by peoples0815** [ioBroker/ioBroker.vis-2#354]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

![image8-fehler](https://github.com/ioBroker/ioBroker.vis-2/assets/39387321/0f9e7da7-53d1-4cb9-9883-e233a599767f)

Wie im Screenshot zu sehen kann ich das Bild für den Wert:0 nicht mehr auswählen

### To Reproduce

1- Widget Image8 Auswählen
2- Auswahlmenü öffnen

### Expected behavior

Vorhandensein einer Auswahlmöglichkeit für den Wert:0

### Screenshots & Logfiles

siehe oben.

### Adapter version

2.9.28

### js-controller version

5.0.17

### Node version

18.19.0

### Operating system

debian

**Comment by Feuer-sturm** [comment]
In dem Zuge kann man auch gleich den String "Wertsanzahl" korrigieren. :-)
