### ISSUE TITLE
[bug]: vis2 not showing on old iPad (iPad4, iOS 10.3.4, Safari-Browser)

### ISSUE THREAD

**Issue by JonasRueter** [ioBroker/ioBroker.vis-2#362]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Trying to use my old iPad as a display for vis, I found out that the actual visualization is only showing a white screen. 
Hoing to http://ip.of.my.vis:8082 first shows the correct view where you choose between runtime, editor and admin, but I cannot get any further from there.

### To Reproduce

Open Safari on an iPad 4 with iOs 10.3.4, go to http://ip.of.my.vis:8082 and click on VIS 2 RUNTIME

### Expected behavior

should show vis2 which works on any other device so far.

### Screenshots & Logfiles

nothing to add here

### Adapter version

2.9.11

### js-controller version

5.0.17

### Node version

18.19.0

### Operating system

iOs 10.3.4

**Comment by foxriver76** [comment]
and vis1 works on the old iPad? I thought socketio/ws do not support these old devices anymore? Not sure if iPad 4 is really affected here

**Comment by JonasRueter** [comment]
> and vis1 works on the old iPad?
Vis1 worked, though i never used it a lot. But AFAIR it did.
We recently moved into a new house so i wanted to set everything up new
i'll try to set up a 2nd system and try out vis1.

iOS10 is from 2017, so not actually THAT old.
What i read though while trying to figure out some stuff on google (and apollogies i'm not an expert) is that ECMAScript 6 (ES6) is not supported in iOS10, support started with iOS11.
So if vis2 is using some of the newer JS-Syntax that might cause the problem.
I probably have to jailbreak the iPad anyway and might try a newer OS or a different browser that is not tied to webkit as a browser engine, but (as we recently moved ;-) ) that still might take a while.

**Comment by foxriver76** [comment]
we can maybe define browserlist like for admin: https://github.com/ioBroker/ioBroker.admin/blob/8ab8cfd489fde39aa4c104021a774463d8094f8d/packages/admin/src/package.json#L18

Accessing Admin works on your tablet?

**Comment by JonasRueter** [comment]
Ok, so I finally found the time to try some things out and so some research:
seems like the old iPads used to work on vis1 up to version 1.4.4, but since then they got kicked out:
https://forum.iobroker.net/topic/26856/iobroker-und-altes-ipad-2

I think this is very unfortunate, there are a bunch of old devices laying around that still look good, are easy to buy for little money and that could extend the lifetime of old electronics

A fallback for old browsers would be great, for example that it loads a dynamic html-website which is refreshed every now and then (in my case 60 seconds and on user interaction would be enough, but maybe that could be user definable).
I get your points about widgets - maybe they could just grey out in that case with a warning that it does not work (unless explicitly marked by the developer to work on old devices).
I'd mostly use the html-widget with some datapoints, so for me that would be enough. Not sure if I'm alone in this or there might be other users that would be happy about this function.
