### ISSUE TITLE
[bug]: Sentry SSL error

### ISSUE THREAD

**Issue by manuxi** [ioBroker/ioBroker.vis-2#363]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

When I navigate through the views on my tablet (Galaxy Note 10.1 2014 Edition), the following appears every time I call it up

`SSL error when loading https://sentry.iobroker.net/api/232/envelope/?sentry_key=db8b6e837c71447a876069559a00a742&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.91.0`

However, as far as I can tell, I have deactivated Sentry everywhere.

This only occurs on my old tablet in Vis-2. I could not detect this on the newer FireTablet or the old Vis.

### To Reproduce

Navigate through Vis-2

### Expected behavior

No error message is shown

### Screenshots & Logfiles

![image](https://github.com/ioBroker/ioBroker.vis-2/assets/11303615/8dcc8018-6cc0-4b85-8a8a-2fe5a522612c)

### Adapter version

2.9.11

### js-controller version

5.0.17

### Node version

v18.17.1

### Operating system

Buanet Docker image v8

**Comment by Apollon77** [comment]
@GermanBluefox Seems like UI integration is not respecting Sentry "turned off" ...

**Comment by foxriver76** [comment]
@manuxi With next version it will respect and you can then also configure for vis-2 separately. Currently it was only turned of if data reporting was disabled system wide.

**Comment by manuxi** [comment]
Just faced in my Chrome console that sentry seems to be still active?
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/11303615/ad0e7b65-e075-4f78-b8da-e539344771f9)

**Comment by foxriver76** [comment]
You have turned off for vis-2?

**Comment by manuxi** [comment]
Yes. Switched it off everywhere to avoid errors.
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/11303615/25b9f6cc-8d2b-44f7-b989-e2e9bb1b8fc4)

**Comment by foxriver76** [comment]
Evtl ist es noch ein Widgetset was das tut. Vergleich mal bitte beim Start das Log, wenn sentry an ist sollte kommen `Sentry initialized` 

![grafik](https://github.com/ioBroker/ioBroker.vis-2/assets/25484431/c44347b5-962d-4bb9-987d-9ca207422322)

Falls aus sollte das nicht kommen.

Es kann allerdings sein, dass externe Widgetsets trotzallem Sentry initialisieren.

![grafik](https://github.com/ioBroker/ioBroker.vis-2/assets/25484431/e80e50d8-a5b4-4196-bb71-be217297ad68)

Ist das vielleicht der Fall bei dir?

**Comment by foxriver76** [comment]
Und ja die `77` schaut startk nach material-design adapter aus https://github.com/Scrounger/ioBroker.vis-materialdesign/blob/8b7529d493f223dfc4f1d1f632553fcb35bbcc92/widgets/materialdesign/js/widgets/materialdesign.00.helper.js#L984

**Comment by foxriver76** [comment]
So wie ich den Code verstehe hat dieser Adapter die Möglichkeit über diesen State Sentry zu deaktivieren, https://github.com/Scrounger/ioBroker.vis-materialdesign/blob/8b7529d493f223dfc4f1d1f632553fcb35bbcc92/widgets/materialdesign/js/widgets/materialdesign.00.helper.js#L961C19-L961C46 ist alter non-react Code und komplett selbst gebaut daher less convinient leider

**Comment by manuxi** [comment]
Danke für Deine Antworten. Ich verstehe deutsch, bin es aber auf Git gewohnt, englisch zu schreiben. Was ist Dir lieber? ;)
Oh mann, Sorry. Habe nicht gesehen, dass Sentry da (anders als bei den anderen Adaptern) deaktiviert werden kann.
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/11303615/c80d786b-e9c9-49a8-a54f-572e4882a9d8)

**Comment by foxriver76** [comment]
English is preferred on GitHub, but I sometimes mess it up 😂

**Comment by mcm1957** [comment]
> Danke für Deine Antworten. Ich verstehe deutsch, bin es aber auf Git gewohnt, englisch zu schreiben. Was ist Dir lieber? ;) Oh mann, Sorry. Habe nicht gesehen, dass Sentry da (anders als bei den anderen Adaptern) deaktiviert werden kann.

Not quite sure what you refer to when writing "anders als bei anderen Adaptern" but you can disable sentry by clicking at the sentry symbol, i.e. the ackupit up instance ahs sentry deisabled here:

![image](https://github.com/ioBroker/ioBroker.vis-2/assets/28575778/cebff0db-6719-473d-b4fa-53ec8c184617)

This will block sending sentry information ssed by the adapter (backend) code - at least if the adapter uses the ioBroker standard plugin.

**Comment by foxriver76** [comment]
This is unfortunately not possible for vis-materialdesign @mcm1957 as it is frontend and not using adapter react

**Comment by foxriver76** [comment]
And for adapter react is is also only possible since this ticket and then adapters still need to mark sentry plugin separately in io pack
