### ISSUE TITLE
[bug]: Probleme mit Widget Zeiteingabe

### ISSUE THREAD

**Issue by fredfesl** [ioBroker/ioBroker.vis-2#367]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Das Widget Zeiteingabe schreibt die falsche Zeit in den Datenpunkt. Sieht aus wie die UTC-Zeit, da sie um eine Stunde zurück ist.
In den Bildern steht im Widget 4:20 Uhr und im Datenpunkt steht 3:20.

### To Reproduce

Widget Zeiteingabe mit Datenpunkt versehen und Zeit eingeben.

### Expected behavior

Es sollte im Datenpunkt, die gleiche Uhrzeit stehen, wie im Widget eingegeben.

### Screenshots & Logfiles

![2024-02-15 13_22_28-Editor vis und 7 weitere Seiten - Persönlich – Microsoft​ Edge](https://github.com/ioBroker/ioBroker.vis-2/assets/94286446/db4f183e-2bb1-4a83-8fc6-74fb04308e02)
![2024-02-15 13_22_53-objects - IoBroker und 7 weitere Seiten - Persönlich – Microsoft​ Edge](https://github.com/ioBroker/ioBroker.vis-2/assets/94286446/c1538013-93d9-40a5-a608-5e6fa8f9f50e)

### Adapter version

2.9.31

### js-controller version

5.0.19

### Node version

18.19.0

### Operating system

Proxmox VM mit Debian

**Comment by mcm1957** [comment]
@fredfesl 
Just for interrest. Why did you close the issue immiatly again? Dis you find a solution / usage  error?
Or was the close done on error?

**Comment by fredfesl** [comment]
Tut mir leid ich habe kurz darauf doch ein Issue gefunden, was das Problem ähnlich beschreibt. 

https://github.com/ioBroker/ioBroker.vis-2/issues/183

Deswegen dachte ich, das ich es wieder schließe.

**Comment by mcm1957** [comment]
Danke ist so ok
Und danke f link
