### ISSUE TITLE
VIS-2 nur mit installierten Metro-Widgets

### ISSUE THREAD

**Issue by ammawel** [ioBroker/ioBroker.vis-2#37]
Hallo,
mit einer "sauberen" v2.0.16 Installation ohne vorherige Versionen, funktionierten verschiedene Widgets wie vis-inventwo, TimeSwitch oder TrashSchedule nicht. Die Widgets wurden nicht angezeigt, die Seite blieb leer.

In der Konsole des Browsers wurden bei vis-2 schon beim Start ohne Projekt jede Menge Fehlermeldungen zu fehlenden Metro-Widget-Dateien angezeigt. Die Metro-Widgets hatte ich unter dem bisherigen vis nicht installiert.
Nach Installation der Metro-Widgets (und Neustart / Aktualisierung von vis2) startet vis2 deutlich flüssiger, gespeicherte Seiten werden angezeigt, alle Widgets von inventwo, TimeSwitch (bisher nur Einmal-Ereignisse), TrashSchedule werden angezeigt und funktionieren.
Eine Deinstallation der vis1-Metro-Widgets führt wieder zu fehlerhafter Darstellung der o.g. Widgets.

So, wie das jetzt für mich aussieht, ist die Installation der Metro-Widgets für vis-2 von essentieller Bedeutung, eine notwendige Voraussetzung.
Ist das beabsichtigt, ein Fehler unbekannter Ursache meiner Installation, ein Bug oder ein Feature?

[VIS2-Beispiel-Metro-Einträge.log](https://github.com/ioBroker/ioBroker.vis/files/10347123/VIS2-Beispiel-Metro-Eintrage.log)

**Comment by Feuer-sturm** [comment]
issue seems to be fixed wit vis-2 version 2.2.2

**Comment by ammawel** [comment]
@Feuer-sturm 

Hi,
das Schließen des Threads war mMn etwas voreilig ;-)

Hast Du nach dem Löschen der Metro-Widgets auch iobroker komplett neu gestartet? Nur den Vis-2-Adapter neu zu starten reicht nicht.

Nach dem Neustart von iobroker startet zwar der vis-2-Editor, Projekte werden aber nicht geladen. Man erhält in den Entwicklungstools des Browsers noch immer folgende Fehlermeldungen des Screenshots:


![Fehler metro vis-2](https://github.com/ioBroker/ioBroker.vis-2/assets/51128844/92076713-fe37-4bd5-b807-b0b203706848)

**Comment by Feuer-sturm** [comment]
Hallo @ammawel ,
welche VIS-2 Version verwendest du?
Auch nach einem iob stop und iob start funktioniert bei mir der Editor ohne die vor dir angezeigten Metro Errors.

**Comment by ammawel** [comment]
Hallo @Feuer-sturm,
vis-Version: 2.2.2
Ich habe gerade als Test ohne Metro ein neues Projekt angelegt, das funktioniert und lädt zügig. 
Wenn ich danach aber den Vis-Editor schließe und neue öffne - das Testprojekt wird geladen - kommen keine Projektdaten, die Metro-Fehler sind da und der vis-Editor lädt mit leerem Fenster ewig.

**Comment by BassT23** [comment]
Hi @ll,

seit dem letzten update von vis-2 (v2.9.64)

habe ich haufenweise fehlermeldungen:

```
web.1 | 2024-10-24 19:23:32.381 | error | 10 - at Function.renderTo (http://192.168.20.3:8083/vis-2/lib/js/can.custom.js:1449:63)
web.1 | 2024-10-24 19:23:32.376 | error | 9 - at r (http://192.168.20.3:8083/vis-2/lib/js/can.custom.js:1370:22)
web.1 | 2024-10-24 19:23:32.376 | error | 8 - at Function.frag (http://192.168.20.3:8083/vis-2/lib/js/can.custom.js:1405:22)
web.1 | 2024-10-24 19:23:32.375 | error | 7 - at Function.hookup (http://192.168.20.3:8083/vis-2/lib/js/can.custom.js:1418:19)
web.1 | 2024-10-24 19:23:32.375 | error | 6 - at a.each (http://192.168.20.3:8083/vis-2/lib/js/can.custom.js:343:211)
web.1 | 2024-10-24 19:23:32.375 | error | 5 - at HTMLDivElement.<anonymous> (http://192.168.20.3:8083/vis-2/lib/js/can.custom.js:1419:98)
web.1 | 2024-10-24 19:23:32.375 | error | 4 - at http://192.168.20.3:8083/vis-2/lib/js/can.custom.js:1727:17
web.1 | 2024-10-24 19:23:32.372 | error | 3 - at a.each (http://192.168.20.3:8083/vis-2/lib/js/can.custom.js:343:211)
web.1 | 2024-10-24 19:23:32.372 | error | 2 - at Function.<anonymous> (http://192.168.20.3:8083/vis-2/lib/js/can.custom.js:1728:17)
web.1 | 2024-10-24 19:23:32.372 | error | 1 - at Object.eval (tplMetroTileNav.js:21:77)
web.1 | 2024-10-24 19:23:32.370 | error | 0 - TypeError: vis.binds.basic.navigation is not a functionTypeError: vis.binds.basic.navigation is not a function
web.1 | 2024-10-24 19:23:32.368 | error | can't render tplMetroTileNav w000032 on "101_Navi":
```

Metro Tile Nav buttens laufen nicht mehr, ...
reinstall von metro widget hilft nicht :(

**Comment by Feuer-sturm** [comment]
@BassT23 Dieses Ticket ist seit einem Jahr geschlossen, die Wahrscheinlichkeit, dass es zum originalen Ticket einen Zusammenhang gibt ist sehr gering ;-)

Bitte erstelle ein neues Issu mit deinem Fehler. Danke.
