### ISSUE TITLE
[bug]: Dialogaufruf bei Gestylt-Widgets geht nicht, wenn Signalbild aktiv ist

### ISSUE THREAD

**Issue by juergiboy** [ioBroker/ioBroker.vis-2#375]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Mit Version 2.9.32 gehen ja die Signalbilder bei den Gestylt-Widgets wieder.
Allerdings funktioniert jetzt der Dialogaufruf nicht mehr, wenn im Widget ein Signalbild angezeigt wird.

Getestet habe ich das mit den Widgets:
Schaltfläche=>Seitendialog
Symbols=>Seitendialog

Wenn die Bedingung für die Signalbilder nicht erfüllt ist (oder gar keins eingerichtet ist) klappt der Dialogaufruf wie gewünscht.

### To Reproduce

Signalbild bei einem der Dialogwidget konfigurieren
Bedingung für Signalbild erfüllen => Dialogaufruf geht nicht

Bedingung für Signalbild nicht erfüllen => Dialog lässt sich aufrufen

### Expected behavior

Dialog kann auch mit Signalbild aufgerufen werden

### Screenshots & Logfiles

wie beschrieben

### Adapter version

2.9.32

### js-controller version

5.0.19

### Node version

18.19.0

### Operating system

Proxmox VM mit Debian

**Comment by foxriver76** [comment]
wenn eines angezeigt wird oder wenn das signalbild das widget überlappt?

**Comment by juergiboy** [comment]
Du hast es ja offenbar schon gefixed, aber noch die Info von mir:
Für mich sieht es so aus das der Dialog nicht funktioniert wenn ein Signalbild angezeigt wird - egal in welcher Größe.

**Comment by foxriver76** [comment]
Hm ich konnte es nachstellen, dass ein Signalbild welches das Widget überlappt an den Stellen des Bildes den Widget Click verhindert. Z. b. bei den material design widgets von scrounger geht das bei den internen nicht. Ich vermute dass es mit der nächsten Version geht wie es soll.
