### ISSUE TITLE
[bug]: Number of values in Widget "Image 8" 

### ISSUE THREAD

**Issue by manuxi** [ioBroker/ioBroker.vis-2#376]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

I'd like to show 2 images according to a state. If I choose "Number of values" (Werteanzahl) eq 1 I can enter two different images, but the second image is never shown (tested with bool and int).
If I choose "Number of values" eq 2 I can enter three different images and the second image is displayed on state true or 1.

Set "Number of values" to 1 is misleading - but it shows the correct count of possible images (coders count, I guess? ;)).
Set "Number of values" to 2 seems correct, but now I can enter one image more then needed. Confusing.

### To Reproduce

Widget "Image 8", enter "Number of values" eq 1, choose a boolean or int, set two images. You won't see the second image if the state is true/1.

### Expected behavior

Better is the first choice, but the second image should be visible on state eq true/1

### Screenshots & Logfiles

![image](https://github.com/ioBroker/ioBroker.vis-2/assets/11303615/ee6834f8-05ae-4ab1-ad09-7fcb3ddd9b3f)

### Adapter version

2.9.32

### js-controller version

5.0.19

### Node version

v18.17.1

### Operating system

Buanet v8

**Comment by foxriver76** [comment]
Yes this is on purpose but if it was different in vis-1 we can change it. However, "Werteanzahl bis 0" includes 0 and 0 is of course useable by the state which controls it. But if you say second not displayed then of course we need to look into.
