### ISSUE TITLE
[bug]: Keine Anzeige von MaterialWidgets2 Switches

### ISSUE THREAD

**Issue by sigi2345** [ioBroker/ioBroker.vis-2#380]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Keine Anzeige von MaterialWidgets2 Switches

### To Reproduce

Siehe Screenshot

### Expected behavior

Widgets Anzeige

### Screenshots & Logfiles

![Screenshot (560)](https://github.com/ioBroker/ioBroker.vis-2/assets/41079106/73090bd9-6745-4c8f-afb0-d40265b615d7)

### Adapter version

2.9.32

### js-controller version

5.0.19

### Node version

18.9.1

### Operating system

Windows

### Additional context

Vis 2 Widgets Material

Installierte Version:
1.3.20

**Comment by LaForge112** [comment]
I have the same Problem for MaterialWidgets2 Thermostat

**Comment by Feuer-sturm** [comment]
@sigi2345 @LaForge112 wie habt ihr vis-2 aktualisiert? Über Admin Adapter Übersicht oder über den npm install vom Expertenmodus?
Führt Mal bitte ein Upload vom vis2 Adapter erneut durch.

**Comment by sigi2345** [comment]
> @sigi2345 @LaForge112 wie habt ihr vis-2 aktualisiert? Über Admin Adapter Übersicht oder über den npm install vom Expertenmodus? Führt Mal bitte ein Upload vom vis2 Adapter erneut durch.

Gemacht, Fehler bleibt.

**Comment by Feuer-sturm** [comment]
Hab das gleiche Problem. Es liegt aber am vis-2-widgets-material Adapter. Nach einem Downgrade auf die Version 1.3.18 sind die widgets bei mir wieder sichtbar. vis-2 ist bei mir version 2.9.33
@sigi2345 Kannst du das bei dir auch einmal ausprobieren, ob ein downgrade hilft?

**Comment by LaForge112** [comment]
Also here, 1.3.18 works

**Comment by foxriver76** [comment]
https://github.com/ioBroker/ioBroker.vis-2-widgets-material/issues/258

**Comment by sigi2345** [comment]
Ok, works with  V 1.3.21
