### ISSUE TITLE
[bug]: Visibility group

### ISSUE THREAD

**Issue by manuxi** [ioBroker/ioBroker.vis-2#381]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

I created two groups with one user in each. The user is also  member of the admin group:
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/11303615/eb6daf4d-1f5b-4a8e-bfe8-c70e09deaff4)
Shoiwing a widget works so far (e.g for user ft in group firetablet). 
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/11303615/08dc5b9e-c82a-4c37-997a-d3582bc0fd94)

But: when I remove the users from admin group, the widget is hidden.  

### To Reproduce

Create user, group, use visibility on a widget.

### Expected behavior

The widget is not hidden, if the user is member of a dedicated group.

### Screenshots & Logfiles

---

### Page or affected widget

```shell
Using "View in Widget"
```

### Adapter version

2.9.32

### js-controller version

5.0.19

### Node version

v18.17.1

### Operating system

Buanet v8

**Comment by foxriver76** [comment]
Does it work if you define it with the permissions functionality in the project window? Currently these are two differrent functionalities which should be harmonized from my point of view

**Comment by manuxi** [comment]
You mean this here? I already stumbled upon this but don't know what to do there. Although I'm admin I can#t change anything there... 
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/11303615/c420d06d-ec83-4269-b63e-0f1b93bf8f59)

**Comment by foxriver76** [comment]
You for sure logged in as admin? Only admin can edit those. (Username in the upper right corner displayed as admin)

**Comment by manuxi** [comment]
Played around with it for hours. Did work neither in FF nor in Chrome.

**Comment by foxriver76** [comment]
ah actually yes, the rename was a problem, I have pushed a fix

**Comment by foxriver76** [comment]
I will also try to reproduce the original issue.

**Comment by foxriver76** [comment]
I think regarding the initial issue it depends on the group permissions. If you login with a user, the socket connection also uses the "maybe" restricted permissions from the assigned group. Can you show me the configured access rights of the group? If read objects is missing try to set and re-check please.

**Comment by manuxi** [comment]
Can't see v2.9.34, only 2.9.32 and 2.9.35.

> Can you show me the configured access rights of the group?
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/11303615/1760b261-e640-4348-9424-2bf7b6a6f93f)

**Comment by foxriver76** [comment]
hm okay from my expectation it looks good to me. If you give the group all access rights, does it also not display?

**Comment by manuxi** [comment]
On v.2.9.36 I removed the tablet user from the admin group, left him in the tablet_fire group only. Set the permissions in the tablet_fire group to grant all permissions. Does not work.

**Comment by manuxi** [comment]
[BTW] I can confirm that I can set permissions on project level now.
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/11303615/62126cf8-bdcd-499e-86c8-56e10abae28c)

**Comment by foxriver76** [comment]
> [BTW] I can confirm that I can set permissions on project level now. ![image](https://private-user-images.githubusercontent.com/11303615/308548815-62126cf8-bdcd-499e-86c8-56e10abae28c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMzIxMDcsIm5iZiI6MTcwOTEzMTgwNywicGF0aCI6Ii8xMTMwMzYxNS8zMDg1NDg4MTUtNjIxMjZjZjgtYmRjZC00OTllLTg2YzgtNTZlMTBhYmFlMjhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDE0NTAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxYTg0ZDg0YzJhNjE1ODc5ZDliMGRhNWM4YmY3NmFmNDVjNDRmNzcwNmFkMThkNDk3ZGE0MzY5OWRiMzE1MTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bfIvzmnAci_XB11P2zgH-YfHgHHhbz_3JOZmk-4zN_s)

Not fixing the original problem, as it should work as well. However, are you able to reach your goal with these settings?

**Comment by manuxi** [comment]
Thank you for that hint, perhaps I'll try this at some day. Seems to be a very complex issue...
