### ISSUE TITLE
[bug]: Beim öffnen des Editors lädt Seite nicht

### ISSUE THREAD

**Issue by Magilusus** [ioBroker/ioBroker.vis-2#383]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Hallo
Sobald ich die Vis-2 öffne, lädt zwar die Seite kurz aber danach erscheint ein schwarzes Bild und die Seite bleibt weiss.
Neuinstallation, Restart hat alles leider nichts gebracht.
Im Log wird keine Meldung diesbezüglich ausgegeben und wurde auf diversen Browsern getestet.
![Screenshot_20240224_135037_Gallery](https://github.com/ioBroker/ioBroker.vis-2/assets/161132234/8a65fc5b-4d59-4adc-8cb2-fec288276557)
![Screenshot_20240224_135059_Gallery](https://github.com/ioBroker/ioBroker.vis-2/assets/161132234/8b1fda6d-241e-4f6d-896f-1a73ff7d1c80)
![Screenshot_20240224_135110_Gallery](https://github.com/ioBroker/ioBroker.vis-2/assets/161132234/d5bd595f-9dc2-4504-98c4-d57771677dc7)

### To Reproduce

Start visu-2, Seite zeigt kurz an, wird schwarz mit weissen Felder, Seite bleibt weiss

### Expected behavior

Laden des Editors

### Screenshots & Logfiles

![Screenshot 2024-02-24 143738](https://github.com/ioBroker/ioBroker.vis-2/assets/161132234/064cfbee-46aa-4dcb-9eb1-f10b6cda0946)

### Adapter version

2.9.32

### js-controller version

5.0.19

### Node version

18.19.1

### Operating system

Raspberry pi

**Comment by Magilusus** [comment]
Danke für deine Rückmeldung.
Ich habe vom Geschäft aus den Fehler nachgestellt und dir den Log eingefügt.
Reicht dir das so oder benötigst du andere /weitere Angaben?

[192.168.0.18-1708948436549.log](https://github.com/ioBroker/ioBroker.vis-2/files/14404190/192.168.0.18-1708948436549.log)

**Comment by foxriver76** [comment]
Yes thanks 

```
react-dom.production.min.js:127 Uncaught TypeError: Cannot add property g00001, object is not extensible
    at d (visUtils.jsx:385:37)
    at Ct.setupSubscriptions (visCanWidget.jsx:114:9)
    at new Ct (visCanWidget.jsx:91:14)
```

Error is very similiar to already fixed https://github.com/ioBroker/ioBroker.vis-2/issues/322

Can you try to upload `iob u vis-2` once and maybe also test with a private browser tab to ensure that current code is really applied and not some caching issue from old version.

**Comment by Magilusus** [comment]
ja das ist ein ähnliches Problem.

Entschuldige, was ist mit upload gemeint?
ich habe noch versucht den Editor im Inkognitofester zu öffnen, jedoch funktioniert e dort auch nicht.

**Comment by foxriver76** [comment]
Upload wäre z. B. im Terminal der Befehl `iob u vis-2` aber ich vermute dass da noch ein Problem vorliegt.

**Comment by Magilusus** [comment]
Ich habe den upload via SSH durchgeführt, jedoch leider ohne Erfolg.

**Comment by foxriver76** [comment]
log hat damit nix zu tun. Kannst du mir evtl. das Projekt exportieren, das die Probleme macht oder kommst du soweit gar nicht?

**Comment by Magilusus** [comment]
Ich habe soeben auf die v2.9.34 upgedatet, leider immer noch dasselbe Problem.
Das Projekt kann ich nicht exportieren, so weit komme ich nicht.
Neuinstallation / Restart und Upload habe ich auch versucht.

https://github.com/ioBroker/ioBroker.vis-2/assets/161132234/d5916b76-ff7c-4e32-bd9e-26fd4809b6bb

der Log:
[192.168.0.18-1708967488216.log](https://github.com/ioBroker/ioBroker.vis-2/files/14408018/192.168.0.18-1708967488216.log)

**Comment by foxriver76** [comment]
Ja dein Problem wird erst in der darauf folgenden Version gefixt sein.

**Comment by Magilusus** [comment]
Alles klar, besten Dank für deine Hilfe 👍
