### ISSUE TITLE
Vis-2 widget "gestylt Zeiteingabe"

### ISSUE THREAD

**Issue by MrX552** [ioBroker/ioBroker.vis-2#387]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Ich möchte über das Zeiteingabe Widget die Steuerung für HeatingControl übernehmen. Wird aber eine Zeit ausgewählt (hier 05:00), wird in den zugehörigen Datenpunkt folgendes geschrieben: 
2024-02-27T04:00:00.000Z
Danach stürzt vis-2 ab und zeigt nur noch einen weißen Bildschirm, bis man den Datenpunkt wieder auf "05:00" setzt.
Auch bei anderen Adaptern, die das Format HH:MM benötigen passiert das gleiche.

### To Reproduce

1. Vis-2 gestylt Zeiteingabe widget erstellen und mit einem Datenpunkt im Format HH:MM verlinken.
2. In der Visualisierung eine Zeit auswählen

### Expected behavior

Im Datenpunkt sollte die Zeit als HH:MM stehen.

### Screenshots & Logfiles

Die Javascript-Konsole in Safari zeigt folgendes:

TypeError: e.minute is not a function. (In 'e.minute()', 'e.minute' is undefined)
(anonyme Funktion) — AdapterDayjs.js:503
g — validateTime.js:46
o — useValidation.js:10
h — usePickerValue.js:191
M — usePicker.js:21
F — useDesktopPicker.js:62
(anonyme Funktion) — DesktopTimePicker.js:83
yr — react-dom.production.min.js:167:249
Vs — react-dom.production.min.js:193
xl — react-dom.production.min.js:280:392
zl — react-dom.production.min.js:280:323
gl — react-dom.production.min.js:280:180
rl — react-dom.production.min.js:271:91
ol — react-dom.production.min.js:268:432
V — scheduler.production.min.js:13:205
j — scheduler.production.min.js:14:128

### Adapter version

2.9.34

### js-controller version

5.0.19

### Node version

18.17.1

### Operating system

Ubuntu 23.10

**Comment by foxriver76** [comment]
Duplicate of https://github.com/ioBroker/ioBroker.vis-2/issues/183 but yes should be prioritized

**Comment by SMS-2018** [comment]
Gibt es für das Problem schon eine Lösung? Ich habe nämlich das gleiche Problem wie @MrX552

Danke!

**Comment by MrX552** [comment]
Ich nehme für heatingcontrol folgende widgets:

 https://github.com/rg-engineering/ioBroker.vis-2-widgets-weather-and-heating

**Comment by SMS-2018** [comment]
Wo finde ich das denn?
![grafik](https://github.com/user-attachments/assets/3eace0f0-a5ce-4605-adc3-1f6e52500154)

Installiert müsste ich es ja richtig haben? Wobei unter verfügbare Version nix steht:
![grafik](https://github.com/user-attachments/assets/6c9f4c23-ad39-40b7-89b3-b51e086031ac)

**Comment by mcm1957** [comment]
Das Widget ist nur im LATEST Repository als BETA verfügbar:

![image](https://github.com/user-attachments/assets/a73ff2ed-1c96-4b7d-a0d4-350e0e67eb4d)

da es der Maintainer bisher nicht ins STABLE aufnehmen ließ. Bitte ihn ggF diesbezüglich kontaktieren,

In der Kachel siehst du keine verfügbare Version, da du wahrscheinlich das STABLE Repository ausgewählt hast - was für produktive System auch OK und empfohlen ist. Und eine stable Version gibt es derzeit nicht.

**Comment by SMS-2018** [comment]
Hab's bestimmt falsch gemacht: in der Konsole so:
`pi@Homee:~ $ npm i iobroker.vis-2-widgets-weather-and-heating

added 1 package in 3s
npm notice
npm notice New minor version of npm available! 10.8.2 -> 10.9.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.9.0
npm notice To update run: npm install -g npm@10.9.0
npm notice
pi@Homee:~ $ npm install -g npm@10.9.0
npm error code EACCES
npm error syscall rename
npm error path /usr/lib/node_modules/npm
npm error dest /usr/lib/node_modules/.npm-qUIFSsiV
npm error errno -13
npm error Error: EACCES: permission denied, rename '/usr/lib/node_modules/npm' -                                                                                                                                                             > '/usr/lib/node_modules/.npm-qUIFSsiV'
npm error     at async Object.rename (node:internal/fs/promises:782:10)
npm error     at async moveFile (/usr/lib/node_modules/npm/node_modules/@npmcli/                                                                                                                                                             fs/lib/move-file.js:30:5)
npm error     at async Promise.allSettled (index 0)
npm error     at async [reifyPackages] (/usr/lib/node_modules/npm/node_modules/@                                                                                                                                                             npmcli/arborist/lib/arborist/reify.js:325:11)
npm error     at async Arborist.reify (/usr/lib/node_modules/npm/node_modules/@n                                                                                                                                                             pmcli/arborist/lib/arborist/reify.js:142:5)
npm error     at async Install.exec (/usr/lib/node_modules/npm/lib/commands/inst                                                                                                                                                             all.js:150:5)
npm error     at async Npm.exec (/usr/lib/node_modules/npm/lib/npm.js:207:9)
npm error     at async module.exports (/usr/lib/node_modules/npm/lib/cli/entry.j                                                                                                                                                             s:74:5) {
npm error   errno: -13,
npm error   code: 'EACCES',
npm error   syscall: 'rename',
npm error   path: '/usr/lib/node_modules/npm',
npm error   dest: '/usr/lib/node_modules/.npm-qUIFSsiV'
npm error }
npm error
npm error The operation was rejected by your operating system.
npm error It is likely you do not have the permissions to access this file as th                                                                                                                                                             e current user
npm error
npm error If you believe this might be a permissions issue, please double-check                                                                                                                                                              the
npm error permissions of the file and its containing directories, or try running
npm error the command again as root/Administrator.
npm error A complete log of this run can be found in: /home/pi/.npm/_logs/2024-1                                                                                                                                                             0-22T06_51_54_402Z-debug-0.log
`

**Comment by mcm1957** [comment]
**NIEMALS adapter direkt via NPM installieren.** Wenn du das im falschen Verzeichnis machst kannst du deine ganze Instalaltion beschädigen.

**Bitte eröffne im Bedarfsfall ein Topic im Forum (https://forum.iobroker.net)** - hier ist nicht der richtige Platz für umfangreichere Diskussionen.

@foxriver76 
Ev. das issue locken damit hier nicht weitere Fragen in einem an sich geschlossenen Issue diskutiert werden.
