### ISSUE TITLE
[bug]: Widget „Gestylt Eingabe des Datums“ - Editor crasht nach Eingabe

### ISSUE THREAD

**Issue by MK-66** [ioBroker/ioBroker.vis-2#391]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Wenn man beim Widget „Gestylt Eingabe des Datums“ in der „externen“ VIS Runtime ein Datum eingibt, crasht der Editor mit leerer weißer Seite. Der Editor wird erst wieder dargestellt, wenn man den Wert vom Datenpunkt im Admin unter Objekte manuell wieder löscht und danach noch einen Browser Reload macht. 

### To Reproduce

Wenn man übrigens in der „internen“ Editor Runtime (also über den Play Button) das Datum eingibt, crasht zwar der Editor nicht, dafür dann aber die eigentliche externe VIS Runtime (mit leerer weißer Seite). Auch die VIS Runtime wird erst wieder angezeigt, wenn man den Wert im Datenpunkt manuell wieder löscht und danach noch einen Browser Reload macht.

Im Datenpunkt steht nach heutiger Eingabe des Datums am **28**.02.2024 folgendes: 2024-02-27T23:00:00.000Z 
Dieser Wert ist für eine reine Datumseingabe hinsichtlich Weiterverarbeitung in meinen Augen ohnehin etwas unglücklich. 

### Expected behavior

Kein Editor crash und der Datenpunkt sollte nach Möglichkeit auch nur das Datum enthalten und nicht noch die Zeit 23:00:00.000Z die man im Widget ja auch gar nicht eingeben kann.

### Screenshots & Logfiles

**Fehler in der Browserkonsole Firefox**

`TypeError: e.isBefore is not a function
    isBeforeDay AdapterDayjs.js:438
    O validateDate.js:34
    o useValidation.js:10
    h usePickerValue.js:191
    M usePicker.js:21
    F useDesktopPicker.js:62
    Rt DesktopDatePicker.js:61
    React 8
    V scheduler.production.min.js:13
    j scheduler.production.min.js:14
console.ts:40:19
Uncaught TypeError: e.isBefore is not a function
    isBeforeDay AdapterDayjs.js:438
    O validateDate.js:34
    o useValidation.js:10
    h usePickerValue.js:191
    M usePicker.js:21
    F useDesktopPicker.js:62
    Rt DesktopDatePicker.js:61
    React 8
    V scheduler.production.min.js:13
    j scheduler.production.min.js:14
`

### Adapter version

2.9.37

### js-controller version

5.0.19

### Node version

18.19.1

### Operating system

Debian 12

### Additional context

Die Eingabe der Zeit beim Widget „Gestylt Zeiteingabe“ funktioniert inzwischen übrigens, vielen Dank für den Fix.

**Comment by Qualitaetsbanane** [comment]
Hallo,

leider besteht das Problem weiterhin

Wenn man im Editor das Widget einfügt, und darüber ein Datum eingibt, funktioniert es. Wenn der Editor neu geladen wird, wird das Browserfenster dunkel /leer. Wenn man beim Neuladen des Editors die Seite mit dem Datumswidget schließt, lädt der Editor. Wenn man die Seite mit dem Widget wieder sichtbar macht, leert sich die Seite wieder.

Wenn der Datenpunkt, in welches das Widget schreibt, manuell geändert wird (z.B. 29.02.2024), lädt sowohl der Editor als auch die Vis, bis wieder ein Datum eingegeben wird.

Datumsformat wie auch beim Vorredner: 2024-02-27T23:00:00.000Z

### Browser
Firefox

![Fehler](https://github.com/ioBroker/ioBroker.vis-2/assets/161766925/535e9c14-a1c3-4fc1-8cd0-d641a14afcdd)
![Fehler1](https://github.com/ioBroker/ioBroker.vis-2/assets/161766925/cebd5229-9291-4a37-9b88-1b711e05befd)

### Adapterversion
2.9.37 (auch bereits in 2.9.32)

### js-controller
5.0.17

### node.js
18.19.0

### Betriebssystem
linux auf RPi 4

Danke und viele Grüße
