### ISSUE TITLE
Basic Widget <View in widget 8> kann nicht eingefügt werden [bug]: 

### ISSUE THREAD

**Issue by Haifeif** [ioBroker/ioBroker.vis-2#411]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

When I try to drag the widget "View in widget 8" to a page, screen goes white, the GUI is gone. When I reload the page, GUI is right again, but the widget isn't there.

### To Reproduce

Drag Widget to page

### Expected behavior

Insert the widget?

### Screenshots & Logfiles

Come on ...

### Adapter version

2.1.4

### js-controller version

5.0.16

### Node version

18.17.1

### Operating system

Linux raspberrypi 6.1.21-v8+

**Comment by Feuer-sturm** [comment]
@Haifeif to which adapter does 2.1.4 belong? Current beta version of vis-2 is v2.9.47
If the white screen is there with the current beta version please press F12 and post the errors of the "Konsole"

I just tried to reproduce your issue with current vis-2 version and I was able to drag and drop the widget

**Comment by Haifeif** [comment]
2.1.4 is what I can see on my monitor!
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/59795191/a2e2c3be-b401-46b2-9de2-6b7c4627f481)

**Comment by Haifeif** [comment]
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/59795191/617d1f52-902a-4650-8fbd-33c5fe50ad62)

**Comment by Haifeif** [comment]
I did the update, as described in the forum:
cd /opt/iobroker
npm i iobroker.vis-2-beta@latest
iob upload vis-2-beta

Still showing 2.1.4

**Comment by Feuer-sturm** [comment]
@Haifeif vis-2-beta is out of date. This repository was the alpha version of vis2 and will not be used any more.
Please uninstall vis-2-beta adapter and install "vis-2" adapter
![grafik](https://github.com/ioBroker/ioBroker.vis-2/assets/25422320/4230a0b2-a083-4634-86d3-42a582f811e1)

Forum link: https://forum.iobroker.net/topic/71786/vis2-ab-morgen-im-stable

**Comment by Haifeif** [comment]
Thanx! Now it's working - even in version 2.7.0. It did an update during installation, but isn't updating to your version. My repository status was beta while installing. I turned it back to stable, no difference. Is there a hint how to update?

Thanx for your support! A lot of large software companies should work as professional as you do!

Liebe Grüße, Uwe

**Comment by mcm1957** [comment]
Aftercswitchingvrepos press Search for new Adapters or named like this. (button on top menue at adapter page). Repoinfo is not always updared immidiatly when switchingcrepis.

**Comment by Feuer-sturm** [comment]
@Haifeif If you have further trouble to get the current vis-2 version I recommend to open a topic in iobroker forum. There you will get a quick support to fix your problem.

**Comment by Haifeif** [comment]
Thanx!
