### ISSUE TITLE
Can't insert <Vis-inventwo> Radio Button List[bug]: 

### ISSUE THREAD

**Issue by Haifeif** [ioBroker/ioBroker.vis-2#412]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

When I drag a Radiobutton List to a page, they are not visible. I only see the widget "border" and the widget sign. I can setup the properties, but the buttons are still invisible.

### To Reproduce

drag vis-inventwo Radiobutton list to a page

### Expected behavior

Well, I need to seen them!

### Screenshots & Logfiles

![image](https://github.com/ioBroker/ioBroker.vis-2/assets/59795191/a4751531-3e77-4a4a-9ddc-0e0fd8b184dd)

### Page or affected widget

```shell
{
  "name": "l-nav-statistik",
  "parentId": "b2776a98-6400-46b3-b89c-b85ddaefa849",
  "settings": {
    "style": {},
    "sizex": "900",
    "sizey": "77"
  },
  "widgets": {
    "w000026": {
      "tpl": "i-vis-radiobutton-list",
      "data": {
        "bindings": [],
        "oid": "0_userdata.0.Datenpunkte.Menu.Admin-iPad.mnu-statistik",
        "iRadiobtnWidth": 80,
        "g_common": true,
        "iRadiobtnHeight": 75,
        "iRadiobtnSpace": "10",
        "iRadiobtnAlign": "horizontal",
        "iRadiobtnWrap": "iOneRowCol",
        "iRadiobtnsCount": 6,
        "iButtonCol": "linear-gradient(#c1c1c1 10%, black 50%)",
        "g_i-css": true,
        "iButtonActive": "linear-gradient(#ff1212 20%, black 80%)",
        "iButtonColHover": "",
        "iOpacityBack": 0,
        "iCornerRadiusUL": "12",
        "iCornerRadiusUR": "0",
        "iCornerRadiusLR": "12",
        "iCornerRadiusLL": "0",
        "iContentFlexDirection": "vertical",
        "iContentVertAlign": "iStart",
        "iContentOrder": "orderTextImg",
        "iOpacityCtn": 1,
        "iTextColor": "#ffffff",
        "iTextSize": "12",
        "iTextAlign": "iStart",
        "iTextSpaceTop": "0",
        "iTextSpaceBottom": "0",
        "iTextSpaceLeft": "0",
        "iTextSpaceRight": "0",
        "iIconSize": "35",
        "iImgAlign": "iCenter",
        "iImgRotation": "0",
        "iImgSpaceTop": "0",
        "iImgSpaceBottom": "0",
        "iImgSpaceLeft": "0",
        "iImgSpaceRight": "0",
        "iShadowXOffset": "2",
        "iShadowYOffset": "2",
        "iShadowBlur": "2",
        "iShadowSpread": "1",
        "iShadowColor": "#111111",
        "iShadowColorActive": "#111111",
        "iShadowInnerXOffset": "0",
        "iShadowInnerYOffset": "0",
        "iShadowInnerBlur": "0",
        "iShadowInnerSpread": "0",
        "iShadowInnerColor": "#111111",
        "iShadowInnerColorActive": "#111111",
        "iBorderSize": "0",
        "iBorderStyle": "none",
        "iBorderColor": "#ffffff",
        "iBorderColorActive": "#ffffff",
        "iTextFalse1": "Temp",
        "iTextTrue1": "Temp",
        "iValue1": "0",
        "iText-BackgroundSettings1": null,
        "iText-BackColorRadioInfo": null,
        "iButtonBackM1": null,
        "iButtonBackActiveM1": null,
        "iText-ImgSettings1": null,
        "iImageFalse1": null,
        "iImageTrue1": null,
        "iImgColorFalse1": null,
        "iImgColorTrue1": null,
        "iImgColorInvert1": null,
        "g_iRadioBtns-1": true,
        "iTextFalse2": "Staub",
        "iTextTrue2": "Staub",
        "iValue2": "1",
        "iText-BackgroundSettings2": null,
        "iButtonBackM2": null,
        "iButtonBackActiveM2": null,
        "iText-ImgSettings2": null,
        "iImageFalse2": null,
        "iImageTrue2": null,
        "iImgColorFalse2": null,
        "iImgColorTrue2": null,
        "iImgColorInvert2": null,
        "g_iRadioBtns-2": true,
        "iTextFalse3": "Strom",
        "iTextTrue3": "Strom",
        "iValue3": "2",
        "iText-BackgroundSettings3": null,
        "iButtonBackM3": null,
        "iButtonBackActiveM3": null,
        "iText-ImgSettings3": null,
        "iImageFalse3": null,
        "iImageTrue3": null,
        "iImgColorFalse3": null,
        "iImgColorTrue3": null,
        "iImgColorInvert3": null,
        "g_iRadioBtns-3": true,
        "iTextFalse4": "Wetter",
        "iTextTrue4": "Wetter",
        "iValue4": "3",
        "iText-BackgroundSettings4": null,
        "iButtonBackM4": null,
        "iButtonBackActiveM4": null,
        "iText-ImgSettings4": null,
        "iImageFalse4": null,
        "iImageTrue4": null,
        "iImgColorFalse4": null,
        "iImgColorTrue4": null,
        "iImgColorInvert4": null,
        "g_iRadioBtns-4": true,
        "iTextFalse5": "Umwelt",
        "iTextTrue5": "Umwelt",
        "iValue5": "4",
        "iText-BackgroundSettings5": null,
        "iButtonBackM5": null,
        "iButtonBackActiveM5": null,
        "iText-ImgSettings5": null,
        "iImageFalse5": null,
        "iImageTrue5": null,
        "iImgColorFalse5": null,
        "iImgColorTrue5": null,
        "iImgColorInvert5": null,
        "g_iRadioBtns-5": true,
        "g_css_font_text": true
      },
      "style": {
        "bindings": [],
        "left": -1,
        "top": 0,
        "width": "900px",
        "height": "77px",
        "z-index": 20,
        "position": "",
        "absoluteWidth": "900px"
      },
      "widgetSet": "vis-inventwo"
    }
  },
  "activeWidgets": {}
}
```

### Adapter version

2.7.0

### js-controller version

5.0.16

### Node version

18.17.1

### Operating system

Raspberry Pi Linux

**Comment by Haifeif** [comment]
Sorry, I used the wrong pages.

Page source code:
{
  "name": "l-nav-statistik",
  "parentId": "b2776a98-6400-46b3-b89c-b85ddaefa849",
  "settings": {
    "style": {},
    "sizex": "900",
    "sizey": "77"
  },
  "widgets": {
    "w000026": {
      "tpl": "i-vis-radiobutton-list",
      "data": {
        "bindings": [],
        "oid": "0_userdata.0.Datenpunkte.Menu.Admin-iPad.mnu-statistik",
        "iRadiobtnWidth": 80,
        "g_common": true,
        "iRadiobtnHeight": 75,
        "iRadiobtnSpace": "10",
        "iRadiobtnAlign": "horizontal",
        "iRadiobtnWrap": "iOneRowCol",
        "iRadiobtnsCount": 6,
        "iButtonCol": "linear-gradient(#c1c1c1 10%, black 50%)",
        "g_i-css": true,
        "iButtonActive": "linear-gradient(#ff1212 20%, black 80%)",
        "iButtonColHover": "",
        "iOpacityBack": 0,
        "iCornerRadiusUL": "12",
        "iCornerRadiusUR": "0",
        "iCornerRadiusLR": "12",
        "iCornerRadiusLL": "0",
        "iContentFlexDirection": "vertical",
        "iContentVertAlign": "iStart",
        "iContentOrder": "orderTextImg",
        "iOpacityCtn": 1,
        "iTextColor": "#ffffff",
        "iTextSize": "12",
        "iTextAlign": "iStart",
        "iTextSpaceTop": "0",
        "iTextSpaceBottom": "0",
        "iTextSpaceLeft": "0",
        "iTextSpaceRight": "0",
        "iIconSize": "35",
        "iImgAlign": "iCenter",
        "iImgRotation": "0",
        "iImgSpaceTop": "0",
        "iImgSpaceBottom": "0",
        "iImgSpaceLeft": "0",
        "iImgSpaceRight": "0",
        "iShadowXOffset": "2",
        "iShadowYOffset": "2",
        "iShadowBlur": "2",
        "iShadowSpread": "1",
        "iShadowColor": "#111111",
        "iShadowColorActive": "#111111",
        "iShadowInnerXOffset": "0",
        "iShadowInnerYOffset": "0",
        "iShadowInnerBlur": "0",
        "iShadowInnerSpread": "0",
        "iShadowInnerColor": "#111111",
        "iShadowInnerColorActive": "#111111",
        "iBorderSize": "0",
        "iBorderStyle": "none",
        "iBorderColor": "#ffffff",
        "iBorderColorActive": "#ffffff",
        "iTextFalse1": "Temp",
        "iTextTrue1": "Temp",
        "iValue1": "0",
        "iText-BackgroundSettings1": null,
        "iText-BackColorRadioInfo": null,
        "iButtonBackM1": null,
        "iButtonBackActiveM1": null,
        "iText-ImgSettings1": null,
        "iImageFalse1": null,
        "iImageTrue1": null,
        "iImgColorFalse1": null,
        "iImgColorTrue1": null,
        "iImgColorInvert1": null,
        "g_iRadioBtns-1": true,
        "iTextFalse2": "Staub",
        "iTextTrue2": "Staub",
        "iValue2": "1",
        "iText-BackgroundSettings2": null,
        "iButtonBackM2": null,
        "iButtonBackActiveM2": null,
        "iText-ImgSettings2": null,
        "iImageFalse2": null,
        "iImageTrue2": null,
        "iImgColorFalse2": null,
        "iImgColorTrue2": null,
        "iImgColorInvert2": null,
        "g_iRadioBtns-2": true,
        "iTextFalse3": "Strom",
        "iTextTrue3": "Strom",
        "iValue3": "2",
        "iText-BackgroundSettings3": null,
        "iButtonBackM3": null,
        "iButtonBackActiveM3": null,
        "iText-ImgSettings3": null,
        "iImageFalse3": null,
        "iImageTrue3": null,
        "iImgColorFalse3": null,
        "iImgColorTrue3": null,
        "iImgColorInvert3": null,
        "g_iRadioBtns-3": true,
        "iTextFalse4": "Wetter",
        "iTextTrue4": "Wetter",
        "iValue4": "3",
        "iText-BackgroundSettings4": null,
        "iButtonBackM4": null,
        "iButtonBackActiveM4": null,
        "iText-ImgSettings4": null,
        "iImageFalse4": null,
        "iImageTrue4": null,
        "iImgColorFalse4": null,
        "iImgColorTrue4": null,
        "iImgColorInvert4": null,
        "g_iRadioBtns-4": true,
        "iTextFalse5": "Umwelt",
        "iTextTrue5": "Umwelt",
        "iValue5": "4",
        "iText-BackgroundSettings5": null,
        "iButtonBackM5": null,
        "iButtonBackActiveM5": null,
        "iText-ImgSettings5": null,
        "iImageFalse5": null,
        "iImageTrue5": null,
        "iImgColorFalse5": null,
        "iImgColorTrue5": null,
        "iImgColorInvert5": null,
        "g_iRadioBtns-5": true,
        "g_css_font_text": true
      },
      "style": {
        "bindings": [],
        "left": -1,
        "top": 0,
        "width": "900px",
        "height": "77px",
        "z-index": 20,
        "position": "",
        "absoluteWidth": "900px"
      },
      "widgetSet": "vis-inventwo"
    }
  },
  "activeWidgets": {}
}

Screen shot
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/59795191/b9345f9c-d60f-4460-a0d9-8bacf259df3e)

**Comment by Feuer-sturm** [comment]
@Haifeif Please first update your vis-2 to the current stable version 2.9.32 (minimum) or to the current beta version 2.9.47
It is not helpfull to search for issues in older vis-2 version which might be fixed already.

**Comment by Haifeif** [comment]
OK, I try.

**Comment by Haifeif** [comment]
Stupid me: I switched back from beta to stable - and didn't check the box for stable! Just uncheked beta. So ioBroker wasn't able to show me updates! So I was unable to update VIS-2.

Now it's done, but no difference. Still not working!

![image](https://github.com/ioBroker/ioBroker.vis-2/assets/59795191/d736cfca-b0b1-411d-b2dc-73e9f5e1d571)

Page source code

{
  "name": "l-home",
  "parentId": "c57bd1f5-2787-48cb-b2c8-41ac0c373718",
  "settings": {
    "style": {
      "background_class": "hq-background-h-gradient-green-1"
    },
    "sizex": "1080",
    "sizey": "740",
    "useBackground": false
  },
  "widgets": {
    "w000009": {
      "tpl": "tplContainerView",
      "data": {
        "name": "Main",
        "comment": null,
        "class": null,
        "filterkey": "Navigation",
        "multi-views": null,
        "locked": null,
        "g_fixed": true,
        "contains_view": "l-nav-main",
        "g_common": true
      },
      "style": {
        "left": 921,
        "top": "0",
        "width": "156px",
        "height": "740"
      }
    },
    "w000031": {
      "tpl": "i-vis-radiobutton-list",
      "data": {
        "oid": "0_userdata.0.Datenpunkte.Menu.Admin-iPad.mnu-statistik",
        "iRadiobtnWidth": 80,
        "g_common": true,
        "iRadiobtnHeight": 75,
        "iRadiobtnSpace": "10",
        "iRadiobtnAlign": "horizontal",
        "iRadiobtnWrap": "iMatrix",
        "iRadiobtnsCount": 8,
        "iButtonCol": "#333333",
        "g_i-css": true,
        "iButtonActive": "#455618",
        "iButtonColHover": "",
        "iOpacityBack": "1",
        "iCornerRadiusUL": "12",
        "iCornerRadiusUR": "0",
        "iCornerRadiusLR": "12",
        "iCornerRadiusLL": "0",
        "iContentFlexDirection": "vertical",
        "iContentVertAlign": "iSpace-between",
        "iContentOrder": "orderImgText",
        "iOpacityCtn": "1",
        "iTextColor": "#ffffff",
        "iTextSize": "12",
        "iTextAlign": "iStart",
        "iTextSpaceTop": "0",
        "iTextSpaceBottom": "0",
        "iTextSpaceLeft": "0",
        "iTextSpaceRight": "0",
        "iIconSize": "35",
        "iImgAlign": "iCenter",
        "iImgRotation": "0",
        "iImgSpaceTop": "0",
        "iImgSpaceBottom": "0",
        "iImgSpaceLeft": "0",
        "iImgSpaceRight": "0",
        "iShadowXOffset": "2",
        "iShadowYOffset": "2",
        "iShadowBlur": "2",
        "iShadowSpread": "1",
        "iShadowColor": "#111111",
        "iShadowColorActive": "#111111",
        "iShadowInnerXOffset": "0",
        "iShadowInnerYOffset": "0",
        "iShadowInnerBlur": "0",
        "iShadowInnerSpread": "0",
        "iShadowInnerColor": "#111111",
        "iShadowInnerColorActive": "#111111",
        "iBorderSize": "0",
        "iBorderStyle": "none",
        "iBorderColor": "#ffffff",
        "iBorderColorActive": "#ffffff",
        "iTextFalse1": "Temperatur",
        "iTextTrue1": "Temperatur",
        "iValue1": "0",
        "iText-BackgroundSettings1": null,
        "iButtonBackM1": "rgba(99,77,210,1)",
        "iButtonBackActiveM1": "rgba(208,15,115,1)",
        "iText-ImgSettings1": null,
        "iImageFalse1": null,
        "iImageTrue1": null,
        "iImgColorFalse1": null,
        "iImgColorTrue1": null,
        "iImgColorInvert1": null,
        "g_iRadioBtns-1": true,
        "iTextFalse2": "Luft",
        "iTextTrue2": "Luft",
        "iValue2": "1",
        "iText-BackgroundSettings2": null,
        "iButtonBackM2": null,
        "iButtonBackActiveM2": null,
        "iText-ImgSettings2": null,
        "iImageFalse2": null,
        "iImageTrue2": null,
        "iImgColorFalse2": null,
        "iImgColorTrue2": null,
        "iImgColorInvert2": null,
        "g_iRadioBtns-2": true,
        "iTextFalse3": "Wetter",
        "iTextTrue3": "Wetter",
        "iValue3": "2",
        "iText-BackgroundSettings3": null,
        "iButtonBackM3": null,
        "iButtonBackActiveM3": null,
        "iText-ImgSettings3": null,
        "iImageFalse3": null,
        "iImageTrue3": null,
        "iImgColorFalse3": null,
        "iImgColorTrue3": null,
        "iImgColorInvert3": null,
        "g_iRadioBtns-3": true,
        "g_css_font_text": true
      },
      "style": {
        "left": "0",
        "top": "662",
        "width": "900",
        "height": "77",
        "z-index": 20,
        "color": null,
        "text-align": null,
        "text-shadow": null,
        "font-family": null,
        "font-style": null,
        "font-variant": null,
        "font-weight": null,
        "font-size": null,
        "line-height": null,
        "letter-spacing": null,
        "word-spacing": null
      }
    },
    "w000032": {
      "tpl": "tplStatefulIFrame8",
      "data": {
        "oid": "0_userdata.0.Datenpunkte.Menu.Admin-iPad.mnu-statistik",
        "refreshInterval": "0",
        "g_common": true,
        "count": 4,
        "src_0": "http://192.168.178.101:8082/flot/index.html?l%5B0%5D%5Bid%5D=zigbee.0.00158d0007558132.temperature&l%5B0%5D%5Boffset%5D=0&l%5B0%5D%5Baggregate%5D=minmax&l%5B0%5D%5Bcolor%5D=%23FF0000&l%5B0%5D%5Bmin%5D=15&l%5B0%5D%5Bmax%5D=25&l%5B0%5D%5Bthickness%5D=3&l%5B0%5D%5Bshadowsize%5D=3&l%5B0%5D%5Bname%5D=Bett&l%5B0%5D%5Bxmove%5D=0&l%5B0%5D%5Byaxe%5D=right&l%5B0%5D%5Bxaxe%5D=bottom&l%5B0%5D%5Binstance%5D=history.0&l%5B1%5D%5Bid%5D=zigbee.0.cc86ecfffea50cb0.local_temp&l%5B1%5D%5Boffset%5D=0&l%5B1%5D%5Baggregate%5D=minmax&l%5B1%5D%5Bcolor%5D=%2300FF00&l%5B1%5D%5Bmin%5D=15&l%5B1%5D%5Bmax%5D=25&l%5B1%5D%5Bthickness%5D=3&l%5B1%5D%5Bshadowsize%5D=3&l%5B1%5D%5Bname%5D=Heizk%C3%B6rper&l%5B1%5D%5Bxmove%5D=0&l%5B1%5D%5Byaxe%5D=off&l%5B1%5D%5Bxaxe%5D=off&l%5B1%5D%5Binstance%5D=history.0&l%5B2%5D%5Bid%5D=zigbee.0.54ef4410001a0b66.temperatur&l%5B2%5D%5Boffset%5D=0&l%5B2%5D%5Baggregate%5D=minmax&l%5B2%5D%5Bcolor%5D=%230000FF&l%5B2%5D%5Bmin%5D=15&l%5B2%5D%5Bmax%5D=25&l%5B2%5D%5Bthickness%5D=3&l%5B2%5D%5Bshadowsize%5D=3&l%5B2%5D%5Bname%5D=Regal&l%5B2%5D%5Bxmove%5D=0&l%5B2%5D%5Byaxe%5D=off&l%5B2%5D%5Bxaxe%5D=off&l%5B2%5D%5Binstance%5D=history.0&l%5B3%5D%5Bid%5D=mqtt.0.Sensoren.CO2.Uwe.Temperatur&l%5B3%5D%5Boffset%5D=0&l%5B3%5D%5Baggregate%5D=minmax&l%5B3%5D%5Bcolor%5D=%23FFFF00&l%5B3%5D%5Bmin%5D=15&l%5B3%5D%5Bmax%5D=25&l%5B3%5D%5Bthickness%5D=3&l%5B3%5D%5Bshadowsize%5D=3&l%5B3%5D%5Bname%5D=CO2+Sensor&l%5B3%5D%5Bxmove%5D=0&l%5B3%5D%5Bxaxe%5D=off&l%5B3%5D%5Byaxe%5D=off&l%5B3%5D%5Binstance%5D=history.0&l%5B4%5D%5Bid%5D=zigbee.0.ec1bbdfffeb077f8.opened&l%5B4%5D%5Binstance%5D=history.0&l%5B4%5D%5Boffset%5D=0&l%5B4%5D%5Baggregate%5D=minmax&l%5B4%5D%5Bcolor%5D=%23FF00FF&l%5B4%5D%5Bmin%5D=0&l%5B4%5D%5Bmax%5D=1&l%5B4%5D%5Bthickness%5D=0&l%5B4%5D%5Bshadowsize%5D=0&l%5B4%5D%5Bname%5D=Fenster+offen&l%5B4%5D%5Bxmove%5D=0&l%5B4%5D%5BchartType%5D=line&l%5B4%5D%5Bfill%5D=0.2&l%5B4%5D%5Byaxe%5D=off&l%5B4%5D%5Bxaxe%5D=off&l%5B4%5D%5BafterComma%5D=2&l%5B4%5D%5Bdashes%5D=false&l%5B4%5D%5BdashLength%5D=10&l%5B4%5D%5BspaceLength%5D=10&l%5B4%5D%5Bmultiplicator%5D=1&l%5B5%5D%5Bid%5D=zigbee.0.cc86ecfffea50cb0.target_temperature&l%5B5%5D%5Binstance%5D=history.0&l%5B5%5D%5Boffset%5D=0&l%5B5%5D%5Baggregate%5D=minmax&l%5B5%5D%5Bcolor%5D=%2300FFFF&l%5B5%5D%5Bmin%5D=15&l%5B5%5D%5Bmax%5D=25&l%5B5%5D%5Bthickness%5D=1&l%5B5%5D%5Bshadowsize%5D=0&l%5B5%5D%5Bxmove%5D=0&l%5B5%5D%5BafterComma%5D=2&l%5B5%5D%5Bdashes%5D=true&l%5B5%5D%5BdashLength%5D=10&l%5B5%5D%5BspaceLength%5D=10&l%5B5%5D%5Bmultiplicator%5D=1&l%5B5%5D%5Bxaxe%5D=off&l%5B5%5D%5Byaxe%5D=off&l%5B5%5D%5Bname%5D=Ventil&timeType=relative&relativeEnd=now&range=720&aggregateType=count&aggregateSpan=3000&legend=nw&hoverDetail=true&useComma=false&zoom=false&noedit=true&animation=0&live=30&start=2022-01-05&start_time=04%3A00&end=2022-01-05&end_time=00%3A00&barLabels=topover&titleColor=%23f8ff00&titleSize=28&width=900&height=630&noBorder=noborder&window_bg=%23000000&x_labels_color=%23ffffff&y_labels_color=%23ffffff&border_color=%23faf7f7&grid_color=%23bebbbb&barColor=%23e06b6b&barWidth=0.1&legColumns=2&legBg=%23ffffff&timeFormat=%25H%3A%25M+%3Cbr%3E+%25d.%25m&barFontSize=%23ffffff&barFontColor=%23f4eeee&title=CO2+Gehalt&legBgOpacity=1&titlePos=top%3A35%3Bleft%3A50",
        "src_1": "http://192.168.178.101:8082/flot/index.html?l%5B0%5D%5Bid%5D=mqtt.0.Sensoren.CO2.Uwe.CO2&l%5B0%5D%5Binstance%5D=history.0&l%5B0%5D%5Boffset%5D=0&l%5B0%5D%5Baggregate%5D=minmax&l%5B0%5D%5Bcolor%5D=%23FF0000&l%5B0%5D%5Bmin%5D=400&l%5B0%5D%5Bmax%5D=3000&l%5B0%5D%5Bthickness%5D=3&l%5B0%5D%5Bshadowsize%5D=3&l%5B0%5D%5Bunit%5D=ppm&l%5B0%5D%5Bname%5D=CO2&l%5B0%5D%5Bxmove%5D=0&l%5B0%5D%5Bxaxe%5D=bottom&l%5B1%5D%5Bid%5D=zigbee.0.ec1bbdfffeb077f8.opened&l%5B1%5D%5Binstance%5D=history.0&l%5B1%5D%5Boffset%5D=0&l%5B1%5D%5Baggregate%5D=minmax&l%5B1%5D%5Bcolor%5D=%23a8f7b6&l%5B1%5D%5Bmin%5D=0&l%5B1%5D%5Bmax%5D=1&l%5B1%5D%5Bthickness%5D=0&l%5B1%5D%5Bshadowsize%5D=0&l%5B1%5D%5Bxmove%5D=0&l%5B1%5D%5BchartType%5D=line&l%5B1%5D%5Bpoints%5D=false&l%5B1%5D%5Bfill%5D=0.2&l%5B1%5D%5BafterComma%5D=0&l%5B1%5D%5Bdashes%5D=false&l%5B1%5D%5BdashLength%5D=10&l%5B1%5D%5BspaceLength%5D=10&l%5B1%5D%5Bmultiplicator%5D=1&l%5B1%5D%5Byaxe%5D=off&l%5B1%5D%5Bxaxe%5D=off&l%5B1%5D%5Bname%5D=Fenster+offen&l%5B2%5D%5Bid%5D=zigbee.0.ec1bbdfffeb4da16.opened&l%5B2%5D%5Binstance%5D=history.0&l%5B2%5D%5Boffset%5D=0&l%5B2%5D%5Baggregate%5D=minmax&l%5B2%5D%5Bcolor%5D=%233dd1f8&l%5B2%5D%5Bmin%5D=-0.1&l%5B2%5D%5Bmax%5D=1.1&l%5B2%5D%5Bthickness%5D=1&l%5B2%5D%5Bshadowsize%5D=0&l%5B2%5D%5Bname%5D=T%C3%BCre+offen&l%5B2%5D%5Bxmove%5D=0&l%5B2%5D%5BchartType%5D=line&l%5B2%5D%5Byaxe%5D=off&l%5B2%5D%5Bxaxe%5D=off&l%5B2%5D%5BafterComma%5D=0&l%5B2%5D%5Bdashes%5D=true&l%5B2%5D%5BdashLength%5D=10&l%5B2%5D%5BspaceLength%5D=10&l%5B2%5D%5Bmultiplicator%5D=1&timeType=relative&relativeEnd=now&range=1440&aggregateType=count&aggregateSpan=300&legend=nw&hoverDetail=true&useComma=false&zoom=false&noedit=true&animation=0&live=30&start=2022-01-05&start_time=04%3A00&end=2022-01-05&end_time=00%3A00&title=CO2+Gehalt&titlePos=top%3A35%3Bleft%3A50&titleColor=%2382f8a8&titleSize=16&barLabels=topover&legBgOpacity=1&barColor=%23000000&timeFormat=%25H%3A%25M&legColumns=1&m%5B0%5D%5Bl%5D=0&m%5B0%5D%5Bv%5D=1200&m%5B0%5D%5Bf%5D=false&m%5B0%5D%5Bc%5D=%23f7f579&m%5B0%5D%5Bt%5D=1&m%5B0%5D%5Bs%5D=0&m%5B0%5D%5Bd%5D=&m%5B0%5D%5Bp%5D=l&m%5B0%5D%5Bpy%5D=0&m%5B0%5D%5Bfc%5D=%23FF0000&m%5B0%5D%5Bfs%5D=&m%5B0%5D%5Bvl%5D=1200&m%5B1%5D%5Bl%5D=0&m%5B1%5D%5Bv%5D=2000&m%5B1%5D%5Bf%5D=false&m%5B1%5D%5Bc%5D=%23f76e94&m%5B1%5D%5Bt%5D=1&m%5B1%5D%5Bs%5D=0&m%5B1%5D%5Bd%5D=&m%5B1%5D%5Bp%5D=l&m%5B1%5D%5Bpy%5D=0&m%5B1%5D%5Bfc%5D=%2300FF00&m%5B1%5D%5Bfs%5D=&m%5B1%5D%5Bvl%5D=2000&width=900&height=630&noBorder=noborder&window_bg=%23000000&x_labels_color=%23ffffff&y_labels_color=%23ffffff&border_color=%23faf7f7&grid_color=%23bebbbb&barWidth=0.1&legBg=%23ffffff&barFontSize=%23ffffff&barFontColor=%23f4eeee",
        "noSandbox": null,
        "g_frames": true
      },
      "style": {
        "left": "",
        "top": "",
        "width": "900",
        "height": "630"
      }
    }
  },
  "activeWidgets": {}
}

**Comment by Feuer-sturm** [comment]
@Haifeif you are still using an old vis version (2.1.4). Please make a topic in iobroker forum where we can check and fix your installation

**Comment by Haifeif** [comment]
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/59795191/1f118747-e25f-4668-8214-0f5ceec97ea3)
No, I do not! - I hope  ...

**Comment by Feuer-sturm** [comment]
@Haifeif Now you are on the vis2 stable version :-)
In your first post of your issue you are trying to use an inventwo widget.
Please find here a statement from the developer https://forum.iobroker.net/topic/68577/vis-inventwo-adapter-kompatibilit%C3%A4t-mit-vis-2/8

Your issue can not  be solved by the vis-2 adapter, you need to wait for the new inventwo adapter.

**Comment by Haifeif** [comment]
Thanx, I shall!
