### ISSUE TITLE
vis-2-beta v2.1.2: Navigation Symbol tauschen

### ISSUE THREAD

**Issue by HJS72** [ioBroker/ioBroker.vis-2#42]
In der Navigation einer Seite kann ich ein custom Symbol nicht austauschen.
Ich hab ein Symbol hochgeladen, dies wird auch angezeigt.
Ich kann Symbol löschen und es wird der Text angezeigt.

Beim Versuch ein anderes Symbol hochzuladen wird aber immer auf das erste Symbol gewechselt.

**Comment by GermanBluefox** [comment]
Ich habe jetzt die Möglichkeit eingebaut, dass man SVG direkt laden kann.
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/4582016/3433509c-71de-4c36-a04f-dd7dbe7f6a24)
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/4582016/312c6fdf-296a-4535-8a9a-54725a0b10ea)


Allerdings man muss auf currentColor attribute achten: https://github.com/ioBroker/ioBroker.vis-2#svg-and-currentcolor
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/4582016/60048f3b-e263-433c-a284-77be36fe04e5)


PNG und JPG werden NIE die Farbe ändern. Stell mal vor, du hast dein Photo hochgeladen und erwartest, dass dieses Photo die Farbe ändern muss.

**Comment by foxriver76** [comment]
@HJS72 ist das Problem gefixt seit Bluefoxs Änderung?
