### ISSUE TITLE
[bug]: New Page - Custom Resolution not possible

### ISSUE THREAD

**Issue by StoniHome** [ioBroker/ioBroker.vis-2#425]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

When adding a new Page it is not possible to choose 'custom Setting' under Resolution.

The Field with Resolution leave blank and width x hight is grayed out and cannot set.

### To Reproduce

+ New Page

goto 'Attribute'

goto 'Option' --> 'Resolution'

set 'Resolution' to ' custom setting'

add 'width x hight' --> 1050x400

### Expected behavior

Choose Resolution --> 'Custom Setting'

Set width x hight --> eg. 1050x400

### Screenshots & Logfiles

![page1](https://github.com/ioBroker/ioBroker.vis-2/assets/101056396/725d3c76-91f0-4c7c-b2f9-68da29aaef59)

### Adapter version

2.9.50

### js-controller version

5.0.19

### Node version

v18.19.0

### Operating system

Synology Docker latest Version

**Comment by StoniHome** [comment]
fixed with v2.9.53

**Comment by Nitro-one** [comment]
Hello, I still have the same problem.
v2.11.1

**Comment by mcm1957** [comment]
> Hello, I still have the same problem. v2.11.1 And Custom setting are not saved. It always appears undefined.

This issue is closed since MAY. 
If you encounter a problem, please open a new issue and eventually link to this isse as refernce. Dio not expect, that closes issues are scanned in any way.
