### ISSUE TITLE
Mehrstufiges Navigationsmenü

### ISSUE THREAD

**Issue by quorle** [ioBroker/ioBroker.vis-2#458]
### No existing issues.

- [X] There is no existing issue for my request.

### Related problems

Momentan kann man kein Mehrstufiges Menü aufbauen mit dem integrierten Menü. Es wäre sinnvoll ein strukturiertes Menü aufbauen zu können, was individuell eingestellt wird. Beispiel siehe unten.

### Description

Es sollte eine mehrstufige Menüstruktur möglich sein.

Beispiel:

**### - Home**
1. Erdgeschoss
2. Obergeschoss
3. Keller
4. Sonstiges

### **- Ergeschoss**
1. Wohnzimmer
2. Badezimmer
3. WC
4. etc....

### **- Obergeschoss**
1. Kind 1
2. Kind 2
3. Schlafen
4. etc...

**Comment by Feuer-sturm** [comment]
Issue ist doppelt zu https://github.com/ioBroker/ioBroker.vis-2/issues/253

**Comment by Feuer-sturm** [comment]
@quorle @ice987987 Gerne einen Daumen hoch im verlinkten issue
