### ISSUE TITLE
[enhancement]: Ignore in versions

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/ioBroker.vis-2#471]
### No existing issues.

- [X] There is no existing issue for my request.

### Related problems

![image](https://github.com/user-attachments/assets/b9210c90-bb12-4778-a32e-56efc21a43b0)

### Description

Implement new definition of ignoreInVersions

**Comment by mcm1957** [comment]
Please see the following issue too which must be fixed at vis-2

https://github.com/ioBroker/ioBroker.js-controller/issues/2818
