### ISSUE TITLE
View in widget 8 lässt editor abstürzen in vis2

### ISSUE THREAD

**Issue by AqWePatchwerk** [ioBroker/ioBroker.vis-2#49]
Hi,

Wenn man das widget "View in widget 8" im editor auf eine view zieht stürzt der gesamte editor ab. Sobald das widget per drag & drop auf der view losgelassen wird öffnet sich eine komplett leere Seite und nichts passiert. Wenn ich dann den editor per F5 neu lade ist der Stand wieder so wie bevor das widget auf die view gezogen wurde.

Versions:
 - Vis2 Adapter version: 2.0.31
 - JS-Controller version: <js-controller-version> 4.0.24
 - Node version: <node-version> v16.20.0
 - Operating system: 
rasberry pi 4
Plattform: linux
Betriebssystem: linux
Architektur: arm
CPUs: 4
Geschwindigkeit: 1500 MHz
Modell: ARMv7 Processor rev 3 (v7l)
RAM: 7.7 GB

**Comment by Feuer-sturm** [comment]
with vis-2 version 2.2.2 I can not reproduce the issue any more.
@AqWePatchwerk please double check. If the issue is still active, we can reopen it.

**Comment by Knobi83** [comment]
Das Problem besteht weiterhin. Bei Änderungen im Widget View in 8 stürzt die VIS-2 ab und lädt sich auch nicht neu.
