### ISSUE TITLE
[bug]: Navigation tab - no hiding

### ISSUE THREAD

**Issue by itProfi** [ioBroker/ioBroker.vis-2#494]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

When select "Hide after selection" - notnig happend

### To Reproduce

Select option - Hide after selection

### Expected behavior

Must hide Navigation tab

### Screenshots & Logfiles

![Скриншот 27-11-2024 224541](https://github.com/user-attachments/assets/f17f6b11-cfa1-46aa-9b18-03b3bf951399)

### Adapter version

2.10.8

### js-controller version

7.0.3

### Node version

v20.18.0

### Operating system

Debian 11

**Comment by hombach** [comment]
Same here

**Comment by Feuer-sturm** [comment]
duplicate to https://github.com/ioBroker/ioBroker.vis-2/issues/492

**Comment by itProfi** [comment]
All ok with version release v2.11.1
