### ISSUE TITLE
Vis2 Fehlerhafte widgets 

### ISSUE THREAD

**Issue by crunchip77** [ioBroker/ioBroker.vis-2#62]
vis v2.0.8

das widget 

> jqui-mfd Shutter + jqui Dialog

 löst folgenden Log aus beim laden
`<html>
<body>

ws.0 | 2022-11-27 23:12:31.730 | error | 10 - at Function.renderTo (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1449:63)
-- | -- | -- | --
ws.0 | 2022-11-27 23:12:31.729 | error | 9 - at r (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1370:22)
ws.0 | 2022-11-27 23:12:31.727 | error | 8 - at Function.frag (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1405:22)
ws.0 | 2022-11-27 23:12:31.726 | error | 7 - at Function.hookup (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1418:19)
ws.0 | 2022-11-27 23:12:31.725 | error | 6 - at a.each (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:343:211)
ws.0 | 2022-11-27 23:12:31.724 | error | 5 - at HTMLDivElement.<anonymous> (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1419:98)
ws.0 | 2022-11-27 23:12:31.723 | error | 4 - at http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1727:17
ws.0 | 2022-11-27 23:12:31.721 | error | 3 - at a.each (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:343:211)
ws.0 | 2022-11-27 23:12:31.720 | error | 2 - at Function.<anonymous> (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1728:17)
ws.0 | 2022-11-27 23:12:31.719 | error | 1 - at Object.eval (tplMfdShutterDialog.js:75:65)
ws.0 | 2022-11-27 23:12:31.718 | error | 0 - TypeError: vis.preloadImages is not a functionTypeError: vis.preloadImages is not a function
ws.0 | 2022-11-27 23:12:31.716 | error | can't render tplMfdShutterDialog w00986 on "Home":

</body>
</html>`

das widget 

> hqwidgets Odometer
wird im Editor korrekt angezeigt, auch wenn man **im Editor auf die Runtime umschalten**,
beim Vis in einem neuen Tab öffnen sieht es allerdings so aus
![image](https://user-images.githubusercontent.com/41550245/204163047-cc8c4725-5ed3-4ae6-bf10-a6375b960bc3.png)

beim widget

> jqui-mfd Light/Dimmer
wird das Symbol nicht geladen, weder im Editor noch in der Vis, jqui-mfd door und auch window funktionieren wiederum

widget 
> vis-inventwo
Multi<br> <span style='color:#888888;'>Switch - State/Button - Navigation - Background</span>
funktioniert das View in Popup (navigieren zu einer anderen View) nicht, es passiert gar nichts beim betätigen

das widget

> metro static - Tile Dialog
öffnet zwar das Fenster, es wird jedoch nichts abgespielt (Tagesschau)

das widget

> jqui-mfd ctrl - Light
kein Symbol und ebenfalls im log
`<html>
<body>

ws.0 | 2022-11-28 06:50:25.803 | error | 10 - at Function.renderTo (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1449:63)
-- | -- | -- | --
ws.0 | 2022-11-28 06:50:25.802 | error | 9 - at r (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1370:22)
ws.0 | 2022-11-28 06:50:25.801 | error | 8 - at Function.frag (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1405:22)
ws.0 | 2022-11-28 06:50:25.800 | error | 7 - at Function.hookup (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1418:19)
ws.0 | 2022-11-28 06:50:25.799 | error | 6 - at a.each (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:343:211)
ws.0 | 2022-11-28 06:50:25.799 | error | 5 - at HTMLDivElement.<anonymous> (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1419:98)
ws.0 | 2022-11-28 06:50:25.798 | error | 4 - at http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1727:17
ws.0 | 2022-11-28 06:50:25.797 | error | 3 - at a.each (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:343:211)
ws.0 | 2022-11-28 06:50:25.796 | error | 2 - at Function.<anonymous> (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1728:17)
ws.0 | 2022-11-28 06:50:25.795 | error | 1 - at Object.eval (tplMfdLightCtrl.js:70:65)
ws.0 | 2022-11-28 06:50:25.794 | error | 0 - TypeError: vis.preloadImages is not a functionTypeError: vis.preloadImages is not a function
ws.0 | 2022-11-28 06:50:25.793 | error | can't render tplMfdLightCtrl w00110 on "220_Licht_OG":

</body>
</html>`

widget
![image](https://user-images.githubusercontent.com/41550245/204205427-32e66253-16e9-455e-a70f-841315a00914.png)

> tpl Mfd Milight Dialog Rgbww
`<html>
<body>

ws.0 | 2022-11-28 07:02:23.988 | error | 10 - at Function.renderTo (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1449:63)
-- | -- | -- | --
ws.0 | 2022-11-28 07:02:23.987 | error | 9 - at r (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1370:22)
ws.0 | 2022-11-28 07:02:23.986 | error | 8 - at Function.frag (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1405:22)
ws.0 | 2022-11-28 07:02:23.985 | error | 7 - at Function.hookup (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1418:19)
ws.0 | 2022-11-28 07:02:23.983 | error | 6 - at a.each (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:343:211)
ws.0 | 2022-11-28 07:02:23.982 | error | 5 - at HTMLDivElement.<anonymous> (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1419:98)
ws.0 | 2022-11-28 07:02:23.981 | error | 4 - at http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1727:17
ws.0 | 2022-11-28 07:02:23.979 | error | 3 - at a.each (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:343:211)
ws.0 | 2022-11-28 07:02:23.978 | error | 2 - at Function.<anonymous> (http://10.1.1.10:8082/vis-2-beta/lib/js/can.custom.js:1728:17)
ws.0 | 2022-11-28 07:02:23.977 | error | 1 - at Object.eval (tplMfdLightCtrl.js:70:65)
ws.0 | 2022-11-28 07:02:23.975 | error | 0 - TypeError: vis.preloadImages is not a functionTypeError: vis.preloadImages is not a function
ws.0 | 2022-11-28 07:02:23.974 | error | can't render tplMfdLightCtrl w00095 on "210_Licht_EG":

</body>
</html>`

**Comment by Feuer-sturm** [comment]
@crunchip77 can you please re validate your issue with vis-2 adpater version 2.2.2 if the problems are still there?

**Comment by crunchip77** [comment]
no problems
