### ISSUE TITLE
vis2 import klappt nicht mit gruppierten Widgets

### ISSUE THREAD

**Issue by denjo1982** [ioBroker/ioBroker.vis-2#67]
bei mir läuft vis2 einwandfrei aber wenn ich mein altes projekt einfüge wird der browser bildschirm komplett schwarz. wenn ich dann die seite aktualisiere kommt vis2 erst und baut alles auf aber wird dann wieder schwarz wenn es fertig geladen ist. wenn ich mein altes projekt schnell lösche beim aufbau wird alles vernüftig aufgebaut. bedeutet also das bei mir das importieren nicht klappt.
Ich hoffe man versteht mich wie ich das meine 😄

ich habe version 2.0.7

ich habe auf folgende meldung im log:

`<html>
<body>

web.0
--
  | 2022-11-26 20:40:48.597	error	10 - at Object.eval (tplMfdShutterDialog.js:286:10)
  |  
  | web.0
  | 2022-11-26 20:40:48.596	error	9 - at Function.txt (http://192.168.178.98:8082/vis-2-beta/lib/js/can.custom.js:2194:47)
  |  
  | web.0
  | 2022-11-26 20:40:48.595	error	8 - at p.bind (http://192.168.178.98:8082/vis-2-beta/lib/js/can.custom.js:1350:19)
  |  
  | web.0
  | 2022-11-26 20:40:48.594	error	7 - at i.bindAndSetup [as bind] (http://192.168.178.98:8082/vis-2-beta/lib/js/can.custom.js:595:151)
  |  
  | web.0
  | 2022-11-26 20:40:48.593	error	6 - at t.Compute._bindsetup (http://192.168.178.98:8082/vis-2-beta/lib/js/can.custom.js:850:27)
  |  
  | web.0
  | 2022-11-26 20:40:48.592	error	5 - at t.Compute.<anonymous> (http://192.168.178.98:8082/vis-2-beta/lib/js/can.custom.js:1285:35)
  |  
  | web.0
  | 2022-11-26 20:40:48.590	error	4 - at t.Compute._on (http://192.168.178.98:8082/vis-2-beta/lib/js/can.custom.js:1315:19)
  |  
  | web.0
  | 2022-11-26 20:40:48.589	error	3 - at t.getValueAndBind (http://192.168.178.98:8082/vis-2-beta/lib/js/can.custom.js:773:167)
  |  
  | web.0
  | 2022-11-26 20:40:48.588	error	2 - at Object.eval (tplMfdShutterDialog.js:291:21)
  |  
  | web.0
  | 2022-11-26 20:40:48.585	error	1 - at _ (http://192.168.178.98:8082/adapter/info/lib/js/commons.js:45:16)
  |  
  | web.0
  | 2022-11-26 20:40:48.584	error	0 - ReferenceError: translateWord is not definedReferenceError: translateWord is not defined
  |  
  | web.0
  | 2022-11-26 20:40:48.582	error	can't render tplMfdShutterDialog w00022 on "Tabs":

</body>
</html>`

**Comment by Feuer-sturm** [comment]
with vis-2 adapter (https://forum.iobroker.net/topic/67676/vis-2-0-neuer-adapter-als-beta) version 2.2.2 it is possible to group widegets. This commented behavior is ok now https://github.com/ioBroker/ioBroker.vis-2/issues/67#issuecomment-1685109120

@denjo1982 please double check as well. If the issue is still active, we can reopen it.

**Comment by chrisdu** [comment]
Hallo, ich hab das Problem nach wie vor, hab jetzt die Version 2.9.12 installiert. Aber bei Seiten mit gruppierten Widgets bekomme ich den weißen Bildschirm. Es ist nur seltsam das auf meinem Testsystem in Proxmox alles läuft??!!
iob diag zeigt keine Fehler.
