### ISSUE TITLE
No license found for vis-2. Please get one on https://iobroker.net !

### ISSUE THREAD

**Issue by Hohenbostler** [ioBroker/ioBroker.vis-2#69]
**Describe the bug**  
Hi zusammen. Ich wollte seit langem mal die VIS-2 ausprobieren. Leider bekomme ich oben stehende Meldung als Error. 
Ein LIzanzupdate von 1 auf 2 habe ich auf www.iobroker.net erledigt. 
Auch sehe ich die aktuelle Lizenz im iobroker. 

**Screenshots & Logfiles**  
`<html>
<body>

host.Synology | 2023-08-21 10:20:17.261 | info | "system.adapter.vis-2.0" disabled
-- | -- | -- | --
host.Synology | 2023-08-21 10:20:11.089 | info | Restart adapter system.adapter.vis-2.0 because enabled
host.Synology | 2023-08-21 10:20:11.088 | error | instance system.adapter.vis-2.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
vis-2.0 | 2023-08-21 10:20:10.481 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
vis-2.0 | 2023-08-21 10:20:10.480 | info | terminating
vis-2.0 | 2023-08-21 10:20:09.976 | error | Exception-Code: ENOENT: ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.vis-2/www/config.js'
vis-2.0 | 2023-08-21 10:20:09.975 | error | Error: ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.vis-2/www/config.js' at Object.openSync (node:fs:603:3) at Object.writeFileSync (node:fs:2324:35) at generateConfigPage (/opt/iobroker/node_modules/iobroker.vis-2/main.js:200:12) at async buildHtmlPages (/opt/iobroker/node_modules/iobroker.vis-2/main.js:769:27) at async Object.main [as ready] (/opt/iobroker/node_modules/iobroker.vis-2/main.js:941:5)
vis-2.0 | 2023-08-21 10:20:09.974 | error | unhandled promise rejection: ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.vis-2/www/config.js'
vis-2.0 | 2023-08-21 10:20:09.973 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
vis-2.0 | 2023-08-21 10:20:09.797 | error | No license found for vis-2. Please get one on https://iobroker.net !

</body>
</html>`

**Versions:**  
 - Adapter version: 2.2.2
Plattform: docker
Betriebssystem: linux
Architektur: x64
CPUs: 2
Geschwindigkeit: 2001 MHz
Modell: Intel(R) Celeron(R) CPU J3355 @ 2.00GHz
RAM: 9.58 GB
System-Betriebszeit: 13 T. 20:09:59
Node.js: v18.17.1
time: 1692607691317
timeOffset: -120
Anzahl der Adapter: 491
NPM: 9.6.7
Datenträgergröße: 3.49 TB
freier Festplattenspeicher: 3.03 TB
Betriebszeit: 00:56:32
Aktive Instanzen: 30
Weg: /opt/iobroker/
Hostname: Synology

![image](https://github.com/ioBroker/ioBroker.vis-2/assets/42488069/39c4cffa-40eb-43ee-aa24-df8398132a11)
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/42488069/b94c06db-a6e1-44ba-875f-c878ed8010ae)

**Comment by GermanBluefox** [comment]
Kann es sein, dass vis-2 wurde aus Git installiert?

**Comment by Hohenbostler** [comment]
> Kann es sein, dass vis-2 wurde aus Git installiert?

Ja du hast recht. Vorhin hatte ich es über npm installiert da ging es. Sorry. Fall kann geschlossen werden.

**Comment by BrightM91** [comment]
ich habe leider das gleiche Problem, aber der Adapter wurde von NPM installiert. ansonsten wie oben, die Lizenz wurde aktualisiert und eingegeben und in der Prüfung als ok befunden. Beim Aufruf von VIS 2.0 ist jedoch die oben genannte Fehlermeldung im Log
