### ISSUE TITLE
Vis Edit without Login

### ISSUE THREAD

**Issue by Eistee82** [ioBroker/ioBroker.vis-2#72]
**Describe the bug**  
It is posible to edit the vis with the link http://iobroker:8082/vis-2/edit.html when I am logged out of iobroker. So there is no securety for the vis

**To Reproduce**  
Open Link http://iobroker:8082/vis-2/edit.html

**Expected behavior**  
Login to Edit Vis

**Versions:**  
 - Adapter version: 2.2.2
 - JS-Controller version: 5.0.12
 - Node version: 18.17.1
 - Operating system: debian

**Comment by foxriver76** [comment]
as long as the webserver has no auth activated this is the intended behavior, same as in vis-1

**Comment by Eistee82** [comment]
Is it posible to make edit with Login and use the vis without Login? Maybe we need to configure two web instances. One for edit and one for View

**Comment by foxriver76** [comment]
Personally I am running a web instance, which requires auth and has admin access, and another one which is just using a user which is allowed to set states, not modify objects which is accessible without auth.
