### ISSUE TITLE
VIS2 lädt keine Widgets

### ISSUE THREAD

**Issue by Secrenz** [ioBroker/ioBroker.vis-2#73]
VIS2 startet bei mir zwar, aber er lädt keine Widgets oder allgemein den Editor.
![VIS2](https://github.com/ioBroker/ioBroker.vis-2/assets/50425124/3d4bbc79-af63-45fc-9a16-66a41299f283)
Hatte schon jemand das selbe Problem?

**Comment by Secrenz** [comment]
Erledigt, habe "Vis 2 Widgets Material" & "Ultimate icon set for visualisation as PNG" installiert, danach kam alles.

**Comment by Secrenz** [comment]
Erledigt, habe "Vis 2 Widgets Material" & "Ultimate icon set for visualisation as PNG" installiert, danach kam alles.

**Comment by Secrenz** [comment]
On a test installation it also works without installing anything else

**Comment by Feuer-sturm** [comment]
@Secrenz can it be a Migration issue from vis-2-beta to vis-2 or vis-1 to vis-2 during first startup of vis-2.
Did you have one of the vis adapters with an existing project installed?

**Comment by Secrenz** [comment]
@Feuer-sturm Yes, I had VIS1 installed. I uninstalled it later.
First I had a problem with the web socket

**Comment by foxriver76** [comment]
Should be fixed with 2.3.3 as there was a problem previously if adapters are installed that have one widgets with errors.
