### ISSUE TITLE
VIS2 - Kein Scrollen mit iPhone

### ISSUE THREAD

**Issue by Secrenz** [ioBroker/ioBroker.vis-2#74]
Vielleicht bin ich der einzige, aber scrollen funktioniert bei mir am Handy gar nicht.
Liegt ein Widget außerhalb des Displaybereichs kann ich nicht die Seite runterscrollen.

Wird das durch die VIS irgendwo gesperrt?

**Comment by Feuer-sturm** [comment]
Ist bereits unter #22 gemeldet
