### ISSUE TITLE
Change background color for navigation pane

### ISSUE THREAD

**Issue by srkonus** [ioBroker/ioBroker.vis-2#76]
**Is your feature request related to a problem? Please describe.**
Navigation pane has a white background and is different to the background of the view

**Describe the solution you'd like**
Navigation pane has the same background color or image like the view

**Comment by GermanBluefox** [comment]
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/4582016/32bf3697-d4a2-4d38-9128-da210cb7a2bd)
