### ISSUE TITLE
Vis zeigt Seiten nicht wenn im Editor nicht geöffnet

### ISSUE THREAD

**Issue by smilie108** [ioBroker/ioBroker.vis-2#77]
**Describe the bug**  
1. Wenn ich vom Editor zur RUntime wechsel werden nur seiten dargestellt die im Editor offen und sichtbar sind wenn ich zb nur seite home offen habe geht die navigation zu den anderen seiten nicht. 
2. View in wideget 8 für zum absturz des editors
3. 
Installiert sind die aktuellen adapter von vis2-alpha und web

**Versions:**  
 - Adapter version: <adapter-version>
 - web.0  v6.1.0
vis-2-beta.0 v2.1.5
 - JS-Controller version: <js-controller-version> 4.0.24
 - Node version: <node-version> v18.17.0
 - Operating system: <os-name>
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian

**Additional context**

**Comment by Feuer-sturm** [comment]
Die Weiterentwicklung von vis-2 findet nicht mehr mit vis-2-beta sondern mit dem vis-2 Adapter statt. Siehe xxx

Bitte vis-2 in der aktuellen Version (2.2.2) installieren und dein issue nachprüfen.

**Comment by GermanBluefox** [comment]
> View in wideget 8 für zum absturz des editors

Bitte logs von der Browser-console
