### ISSUE TITLE
Import Funktion eines Projekts von VIS auf VIS2 ohne Funktion

### ISSUE THREAD

**Issue by m0uh85** [ioBroker/ioBroker.vis-2#78]
**Describe the bug**  
Projekt aus VIS exportiert - Projekt in VIS2 importiert.
Meldung: "Projekt erfolgreich importiert" - Projekt wird zur Auswahl angezeigt, beim Klick auf das Projekt öffnet sich aber nichts.
Neues Test Projekt erstellt, lässt sich fehlerfrei öffnen.

**To Reproduce**  
VIS Projekt importieren

**Versions:**  
 - Adapter version: v2.2.4
 - JS-Controller version: 5.0.12
 - Node version: v18.17.1
 - Operating system: Debian 11 Buster 64 Bit

**Comment by c-hum** [comment]
Gleiches Verhalten auch bei mir.

Adapter version: v2.2.4
JS-Controller version: 5.0.12
Node version: v18.17.1

**Comment by Feuer-sturm** [comment]
@m0uh85 @c-hum 
Ohne entsprechenden Fehlermeldungen aus der Browser console wird eine weitere Analyse nicht möglich sein. 

Wie hier x beschrieben wird es aber keine vollständige Garantie geben, dass alle widgets aus vis1 1:1 übernommen werden können. Probiert mal einen Import der einzelnen views, so dass ihr eingrenzen könnt, wo etwas nichts mehr funktioniert.

**Comment by m0uh85** [comment]
DevTools failed to load source map: Could not load content for http://192.168.178.67:8082/vis-2-beta/static/js/main.6c4ff8e5.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.178.67:8082/vis-2-beta/static/js/554.68737bc5.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
bootstrap.jsx:20 iobroker.vis-2-beta@2.1.4 using theme "colored"
main.6c4ff8e5.js:2 
██╗ ██████╗ ██████╗ ██████╗  ██████╗ ██╗  ██╗███████╗██████╗ 
██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝██╔══██╗
██║██║   ██║██████╔╝██████╔╝██║   ██║█████╔╝ █████╗  ██████╔╝
██║██║   ██║██╔══██╗██╔══██╗██║   ██║██╔═██╗ ██╔══╝  ██╔══██╗
██║╚██████╔╝██████╔╝██║  ██║╚██████╔╝██║  ██╗███████╗██║  ██║
╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

main.6c4ff8e5.js:2 Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters
main.6c4ff8e5.js:2 Help us to create open source project with reactJS!
main.6c4ff8e5.js:2 See you :)
socket.io.js:66 [2023-09-10T10:43:32.982Z] Try to connect
554.68737bc5.chunk.js:2 Cannot load instance settings
(anonymous) @ 554.68737bc5.chunk.js:2
Promise.then (async)
(anonymous) @ 554.68737bc5.chunk.js:2
Promise.then (async)
onReady @ 554.68737bc5.chunk.js:2
(anonymous) @ main.6c4ff8e5.js:2
Promise.then (async)
(anonymous) @ main.6c4ff8e5.js:2
value @ main.6c4ff8e5.js:2
value @ main.6c4ff8e5.js:2
value @ main.6c4ff8e5.js:2
(anonymous) @ main.6c4ff8e5.js:2
SocketClient.findAnswer @ socket.io.js:304
socket.onmessage @ socket.io.js:212
Runtime.jsx:286 Cannot read project file "main-new/vis-views.json": Not exists
(anonymous) @ Runtime.jsx:286
d @ regeneratorRuntime.js:44
(anonymous) @ regeneratorRuntime.js:125
(anonymous) @ regeneratorRuntime.js:69
r @ asyncToGenerator.js:3
u @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:12
o @ asyncToGenerator.js:22
(anonymous) @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:19
(anonymous) @ Runtime.jsx:405
(anonymous) @ Runtime.jsx:506
d @ regeneratorRuntime.js:44
(anonymous) @ regeneratorRuntime.js:125
(anonymous) @ regeneratorRuntime.js:69
r @ asyncToGenerator.js:3
o @ asyncToGenerator.js:22
Promise.then (async)
r @ asyncToGenerator.js:12
o @ asyncToGenerator.js:22
Promise.then (async)
r @ asyncToGenerator.js:12
o @ asyncToGenerator.js:22
Promise.then (async)
r @ asyncToGenerator.js:12
o @ asyncToGenerator.js:22
Promise.then (async)
r @ asyncToGenerator.js:12
o @ asyncToGenerator.js:22
Promise.then (async)
r @ asyncToGenerator.js:12
o @ asyncToGenerator.js:22
Promise.then (async)
r @ asyncToGenerator.js:12
o @ asyncToGenerator.js:22
(anonymous) @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:19
(anonymous) @ Runtime.jsx:518
(anonymous) @ 554.68737bc5.chunk.js:2
Do @ main.6c4ff8e5.js:2
xs @ main.6c4ff8e5.js:2
Hs @ main.6c4ff8e5.js:2
Ms @ main.6c4ff8e5.js:2
(anonymous) @ main.6c4ff8e5.js:2
Vl @ main.6c4ff8e5.js:2
ol @ main.6c4ff8e5.js:2
V @ main.6c4ff8e5.js:2
T @ main.6c4ff8e5.js:2

> @m0uh85 @c-hum Ohne entsprechenden Fehlermeldungen aus der Browser console wird eine weitere Analyse nicht möglich sein.
> 
> Wie hier https://forum.iobroker.net/topic/67676/vis-2-0-neuer-adapter-als-beta beschrieben wird es aber keine vollständige Garantie geben, dass alle widgets aus vis1 1:1 übernommen werden können. Probiert mal einen Import der einzelnen views, so dass ihr eingrenzen könnt, wo etwas nichts mehr funktioniert.

Hilft dir das?

Wenn ich den Adapter VIS lösche und neuinstalliere sind meine Projekte immer noch vorhanden. Wie lösche ich den komplett alles? Weil bei der 1. Installation hat alles problemlos funktioniert und ich habe an meine VIS nichts geändert seither. Deshalbe denke ich nicht das es was mit irgend einem einzelnen View zu tun hat.

**Comment by c-hum** [comment]
Es scheint irgendetwas beim Import schief zu laufen. Nach dem Import auf der Startseite des Editors lässt sich das Projekt nich anklicken, die Konsole meldet: "_Cannot read project file "main/vis-views.json": Not exists_". Wenn ich in den zugehörigen Ordner "/vis-2.0/main" schaue, ist dort auch nur der img-Ordner und sonst nichts. 

Lege ich nun ein leeres Projekt an und versuche den Import über die "normale" Oberfläche (also wenn ich im leeren Neuprojekt bin), dann erscheint beim Import folgende Fehlermeldung: _Cannot upload project: [object Object]_

Leider reicht es auch nicht, die Daten aus dem alten VIS in den Ordner des neuen VIS-2 zu ko pieren.

Ich hoffe das hilft weiter?

**Comment by GermanBluefox** [comment]
This will be fixed with next js-controller version 5.0.x

**Comment by PiemurIsBack** [comment]
Ich habe ebenfalls das Problem beim Import von VIS-Projekten in VIS2.
Ich wollte mir das Uhula-Beispielprojekt MD_Demo ansehen. 
Beim Import wird mir angezeigt, dass dies erfolgreich sein soll, aber ich kann das Projekt nicht öffnen und lande immer wieder im Projekt-Auswahlfenster.

Laut F12  instrument.ts:144 Cannot read project file "MD_Demo/vis-views.json": Not exists

Wenn ich mir das Projekt mittels Dateien ansehen möchte, ist nur das Verzeichnis Vis-2/MD_Demo angelegt.
Die Json und css Dateien sind nicht vorhanden.

Hier läuft igendetwas beim Import schief.


Versions:
Adapter version: v2.3.0 
JS-Controller version: 5.0.12
Node version: v18.17.0 
Operating system: rapsy 64bit lite bullseye

`bootstrap.jsx:16 iobroker.vis-2@2.3.0 using theme "colored"
Prompt.js:14 
██╗ ██████╗ ██████╗ ██████╗  ██████╗ ██╗  ██╗███████╗██████╗ 
██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝██╔══██╗
██║██║   ██║██████╔╝██████╔╝██║   ██║█████╔╝ █████╗  ██████╔╝
██║██║   ██║██╔══██╗██╔══██╗██║   ██║██╔═██╗ ██╔══╝  ██╔══██╗
██║╚██████╔╝██████╔╝██║  ██║╚██████╔╝██║  ██╗███████╗██║  ██║
╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

Prompt.js:15 Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters
Prompt.js:16 Help us to create open source project with reactJS!
Prompt.js:17 See you :)
socket.io.js:66 [2023-10-09T08:47:06.227Z] Try to connect
instrument.ts:144 Cannot read project file "MD_Demo/vis-views.json": Not exists
(anonym) @ instrument.ts:144
(anonym) @ Runtime.jsx:373
h @ regeneratorRuntime.js:45
(anonym) @ regeneratorRuntime.js:133
(anonym) @ regeneratorRuntime.js:74
r @ asyncToGenerator.js:3
u @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:12
s @ asyncToGenerator.js:22
(anonym) @ asyncToGenerator.js:27
(anonym) @ asyncToGenerator.js:19
(anonym) @ Runtime.jsx:497
(anonym) @ Runtime.jsx:609
h @ regeneratorRuntime.js:45
(anonym) @ regeneratorRuntime.js:133
(anonym) @ regeneratorRuntime.js:74
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:22
Promise.then (async)
r @ asyncToGenerator.js:12
s @ asyncToGenerator.js:22
Promise.then (async)
r @ asyncToGenerator.js:12
s @ asyncToGenerator.js:22
Promise.then (async)
r @ asyncToGenerator.js:12
s @ asyncToGenerator.js:22
Promise.then (async)
r @ asyncToGenerator.js:12
s @ asyncToGenerator.js:22
Promise.then (async)
r @ asyncToGenerator.js:12
s @ asyncToGenerator.js:22
Promise.then (async)
r @ asyncToGenerator.js:12
s @ asyncToGenerator.js:22
(anonym) @ asyncToGenerator.js:27
(anonym) @ asyncToGenerator.js:19
(anonym) @ Runtime.jsx:621
(anonym) @ GenericApp.js:301
Do @ react-dom.production.min.js:144
xs @ react-dom.production.min.js:261
Hs @ react-dom.production.min.js:260
Ms @ react-dom.production.min.js:259
(anonym) @ react-dom.production.min.js:283
Vl @ react-dom.production.min.js:281
ol @ react-dom.production.min.js:270
V @ scheduler.production.min.js:13
T @ scheduler.production.min.js:14`

**Comment by m0uh85** [comment]
JS-Controller version: 5.0.13 

Damit funktioniert es.
