### ISSUE TITLE
VIS-2 view in widget scrolling does not work

### ISSUE THREAD

**Issue by MK-66** [ioBroker/ioBroker.vis-2#79]
In a view in widget it is not possible to scroll within the view.
This is not possible even if body overflow is set to scroll in the project settings.

![vis2-settings-240](https://github.com/ioBroker/ioBroker.vis-2/assets/56516310/40571960-b7b0-4a44-ad3f-cb230b164b74)

In VIS-1 you can scroll normally in a view in widget.

**Comment by GermanBluefox** [comment]
Which vis-2 version? Please try 2.2.6

**Comment by MK-66** [comment]
vis-2 version 2.2.6: There is still no scrolling in a basic Vew in Widget possible

**Comment by GermanBluefox** [comment]
Die Einstellungen für overflow werden hier eingestellt:
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/4582016/0552a882-4951-4af2-ba2f-c0c297b16c19)

Aber es funktioniert erst ab 2.2.8

**Comment by Feuer-sturm** [comment]
@MK-66 is it fixed with current version?

**Comment by MK-66** [comment]
@Feuer-sturm 
Sorry for giving no feedback, issue was fixed. 
I don't remember since which version, but I think since 2.3.x it was fixed. 
V2.3.3, 2.3.4 and 2.3.5 are definitely ok.

**Comment by Feuer-sturm** [comment]
@MK-66 Thanks :-)
