### ISSUE TITLE
Seitenhintergrund weiß beim scrollen

### ISSUE THREAD

**Issue by ipod86** [ioBroker/ioBroker.vis-2#80]
Hallo,

es bleibt egal was ich versuche, beim scrollen der Hintergrund unter dem beim laden gerenderten Beriech weiß.

![1](https://github.com/ioBroker/ioBroker.vis-2/assets/66136363/6846bdd4-c800-4c1f-9994-8df79cb08556)
![2](https://github.com/ioBroker/ioBroker.vis-2/assets/66136363/82357adc-d31b-482c-b21a-e828d8e26c4d)

VIS-2   v 2.2.4
WEB    v 6.1.1

**Comment by Feuer-sturm** [comment]
@ipod86 Kannst du bitte einmal dieses issue mit vis-2 version 2.2.7 prüfen ob es jetzt i.O. ist?

**Comment by ipod86** [comment]
Teste sobald ich die 2.2.8 angeboten bekomme.

**Comment by ipod86** [comment]
> @ipod86 Kannst du bitte einmal dieses issue mit vis-2 version 2.2.8 prüfen ob es jetzt i.O. ist?
> 
> Edit: Sehe gerade, das dies issue erst in 2.2.8 (aktuell ist 2.2.7) gefixt ist

Jepp,

jetzt passt es.

**Comment by bierhurra** [comment]
Hallo,

ich habe folgende Versionen installiert:
VIS 2 2.12.12
WEB 7.0.8

Ich habe, seit ich VIS 2 teste, das selbe Problem. Egal ob ich versuche im Hintergrund Farben oder Bilder einstelle, bleiben diese im Editor auf den dargestellten Ausschnitt begrenzt. Der Rest ist weiß. 

https://github.com/user-attachments/assets/824b73b9-0f5c-431f-986a-c389f65a9878
