### ISSUE TITLE
 jqui widget "navigation icon" wird in Vis 2 nicht hervorgehoben

### ISSUE THREAD

**Issue by Homezecke** [ioBroker/ioBroker.vis-2#85]
der Button jqui widget "navigation icon" wird nach dem Anklicken nicht hervorgehoben bzw selektiert dargestellt. In VIS1 geht das. Dies ist jedoch nützlich, da bei mehreren Buttons der jeweilige sich von den anderen abhebt, und daran erkannt werden kann zu welcher Seite navigiert wurde.

**Comment by Feuer-sturm** [comment]
@Homezecke Welche vis-2 Version hast du installiert?

**Comment by Homezecke** [comment]
Version 2.2.5

**Comment by Feuer-sturm** [comment]
@Homezecke please verify with current version (>= 2.3.3)
