### ISSUE TITLE
Translation ra_Show_all_folders is missing

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.vis-2#89]
**Describe the bug**  
The translation for ra_Show_all_folders is missing if you make a mousover over the red symbol

This menu is e.g. shown if you want to select a "symbol" in the widget "Schalter oder Knöpfe"

**Screenshots & Logfiles**  
![grafik](https://github.com/ioBroker/ioBroker.vis-2/assets/25422320/36a7bca4-3c0c-449a-87c8-6c4ab0b43fc0)

**Versions:**  
- vis-2 version 2.2.7

**Comment by foxriver76** [comment]
should be fixed, can you verify?

**Comment by Feuer-sturm** [comment]
is fixed in vis-2 version 2.3.2 
:-)
