### ISSUE TITLE
Vis2 Widget Attribute ausblenden (Vis Adapter Entwicklung)

### ISSUE THREAD

**Issue by jkvarel** [ioBroker/ioBroker.vis-2#91]
Wie in Vis 1 möchte ich auch gerne in Vis 2 bei unseren Widgets (vis-inventwo) Attribute ausblenden, die im Moment nicht relevant sind.
Leider ist die Funktion "hideShowAttr" deprecated und ich habe so nichts neues gefunden. Gibt es keine Möglichkeit mehr Attribute aus- und einzublenden? Wird es wieder eine geben?

Gibt es sonst irgendeinen Weg dass ich die Ansicht manipulieren kann? 

Ich möchte gerne dabei bleiben, dass das Universal- und Multi-Widget ihren Namen behalten und die wichtigsten Interkationen in einem vereinen. Nur wenn alle Attribute sichtbar sind wird es sehr unübersichtlich.

**Comment by GermanBluefox** [comment]
Es gibt ganz neue Möglichkeiten dafür: https://github.com/ioBroker/ioBroker.vis-2/blob/master/src/src/Attributes/Widget/SCHEMA.md

Und hier ist ein Beispiel, wie es zu benutzen: https://github.com/ioBroker/ioBroker.vis-2-widgets-material/blob/main/src-widgets/src/Actual.jsx#L179

Also bitte keine data-artributes mehr.

**Comment by foxriver76** [comment]
Hat die Info von BF dir weitergeholfen oder benötigst du im Kontext dieses Issues noch Informationen oder Anpassungen @jkvarel
