### ISSUE TITLE
Vis2 Widgets aktualisieren nicht wenn Wert von Binding sich ändert und Widget mit JS Funktion erstellt wurde

### ISSUE THREAD

**Issue by jkvarel** [ioBroker/ioBroker.vis-2#92]
In Vis 1 wird das ganze Widget aktualisiert wenn sich der Wert von einem Binding ändert.

In Vis 2 nicht. Was nicht schlecht ist. Dort werden die durch magic tags hinzugefügten Elemente aktualisiert. Leider wird nichts aktualisiert, wenn das ganze Widget in einer JS Funktion erstellt wird. Aufgrund der Komplexität kann ich die Widgets nicht nicht in der HTML Datei mit magic tags erstellen. 

Wie kann ich die Widgets aktualisieren, wenn sich die Werte von Bindings ändern? Gibt es eine Möglichkeit im data Object vom Widget die nicht aufgelösten Felder, also noch mit Bindings zu bekommen?  Dann könnte ich eigene Events erstellen, um gezielt die Elemente in den Widgets zu aktualisieren.

**Comment by GermanBluefox** [comment]
Also um die Frage zu beantworten, brauche ich Code.
So habe ich nicht verstanden warum es geht. Ich wurde gerne einen Crash-Course anbieten wie man die Widgets mit React jetzt entwickelt. Bitte schreibe mich unter "info at iobroker.net " und ich zeige dir.

**Comment by jkvarel** [comment]
Als Beispiel beim Universal Widget. Das Widget wird in der vis-inventwo.html definiert. Der Inhalt des Widgets wird von einer JS Funktion generiert. https://github.com/inventwo/ioBroker.vis-inventwo/blob/master/widgets/vis-inventwo.html#L176
https://github.com/inventwo/ioBroker.vis-inventwo/blob/master/widgets/vis-inventwo/js/vis-inventwo.js#L4217

Werte aus Datenpunkten werden durch Bindings dort verwendet. In Vis 1 lädt die Vis das Widget bei Datenpunktänderung das Widget komplett neu. In Vis 2 nicht mehr. Das wird wahrscheinlich daran liegen, dass die Widgets nicht mit React entwickelt wurden? Ich habe bisher keine Erfahrung mit React. 

Wenn die Widgets neu in React entwickelt werden müssen, müssten alle ihre Vis neu machen? Weils dann neue Widgets sind?
