### ISSUE TITLE
FR: Dedicated User Management for vis

### ISSUE THREAD

**Issue by stevenengland** [ioBroker/ioBroker.vis-2#94]
**Is your feature request related to a problem? Please describe.**
Today I am not able to easily distinct which users or groups should be able to access runtime/editor and then which of them is able to see a project, view, etc. A long discussion regarding this is here: https://forum.iobroker.net/topic/54281/vis-views-benutzer-zugriffsberechtigung/21

**Describe the solution you'd like**
A clear, dedicated (and documented ;)) mechanism to administrate users for what I produce with the help of the vis(2) adapter. 
Meaning: 
* Within the vis adapter configuration there might be a tab to enable ACL and who should be able to access runtime/editor parts 
* In vis editor module there should be tooling that makes it possible to set ACL for the whole tree (project, view, widget).
* The user repository might be the same as the iobroker user repository not a seperate one.

**Describe alternatives you've considered**
Workarounds found in the net that are either tedious or not feasable.

**Comment by mwiesener** [comment]
Is there anything new or a schedule? It will probably be built into vis-2. So I switched to vis-2, still the same error so far?

**Comment by foxriver76** [comment]
next version will get a permission system on project level which is accesible through the project selection

![grafik](https://github.com/ioBroker/ioBroker.vis-2/assets/25484431/96736511-a72d-4202-8b63-6c7107df050d)

![Bildschirmfoto vom 2024-01-12 10-08-09](https://github.com/ioBroker/ioBroker.vis-2/assets/25484431/f57ecbd2-6a25-4239-b2e1-e00e3a5222ea)

![grafik](https://github.com/ioBroker/ioBroker.vis-2/assets/25484431/ac754626-c92b-44c4-9678-0243c9563a4d)

If this works as designed, we will extend it to views too. Any maybe later also for widgets.

**Comment by PackElend** [comment]
This is great news any ETA planned?

So it could be that we will soon have iobroker permissions,  roles throughout.

**Comment by foxriver76** [comment]
I think the version with the permissions on project level will be released on Monday in beta. 

For the further stuff no ETA always depends if there is more important things going on in some projects and how I have time besides my main job 😬

**Comment by Feuer-sturm** [comment]
@foxriver76 Just to understand, what is the use-case to have such permissions on widget level? To have this feature on view level I can understand but I can't currently imagine in which use cases it is really helpfull on widget level.

**Comment by foxriver76** [comment]
I could imagine eg having a button to open a door which should only be visible to specific users.

**Comment by foxriver76** [comment]
Please check with 2.9.18. Has permissions for projects and views. Please report bugs in separate issues.

We will check if permissions on widget level are really desirable.

**Comment by PackElend** [comment]
> We will check if permissions on widget level are really desirable.

I find this very reasonable: 

> I could imagine eg having a button to open a door which should only be visible to specific users.

think about guest or kids, so you prevent that important things are password protected.

**Comment by foxriver76** [comment]
with 2.9.20 the permission integration is finished, also for single widgets.
