### ISSUE TITLE
Widget "Wert schreiben" - Bindings

### ISSUE THREAD

**Issue by Blockmove** [ioBroker/ioBroker.vis-2#98]
Version vis-2 2.3.0

Beim Widget "Wert schreiben" gibt es keine  Bindings.
Zumindest für die Einträge Wert, Step, Höchster Wert, Minimaler Wert wäre dies sehr nützlich

**Comment by GermanBluefox** [comment]
ist Object ID und Typ Increment selektiert?
![image](https://github.com/ioBroker/ioBroker.vis-2/assets/4582016/8a815516-aec6-4f20-8782-9f478f533a9e)

**Comment by Blockmove** [comment]
Ja, ist aktiviert. Mit statischen Werten funktionieren die Grenzen auch. Mit Bindings (bei mir zumindest) nicht.
![Wert schreiben Binding](https://github.com/ioBroker/ioBroker.vis-2/assets/1595204/8ee9f391-c0bd-4cb3-9750-a22e14ff87aa)

Vis-2 2.3.2
Webserver 6.1.6
js-controller 5.13
nodejs 18.18

**Comment by foxriver76** [comment]
Ist das noch aktuell? Bei mir funktioniert das mit 2.3.6 jedenfalls. 

![grafik](https://github.com/ioBroker/ioBroker.vis-2/assets/25484431/e864d945-29b1-4f12-87c6-49677d81fe49)
